export interface GraphPanelDef {
  id: string;
  title: string;
  description: string;
  chartType: 'line' | 'area' | 'bar' | 'pie';
  metricQueries: string[];
  axes?: { y?: { label: string; unit?: string }; y2?: { label: string; unit?: string } };
  legend?: string[];
}

export const dbmAwsRdsPostgresqlGraphPanels: GraphPanelDef[] = [
  {
    id: 'DBM10416',
    title: 'CPU Utilization',
    description: 'RDS PostgreSQL CPU utilization percentage',
    chartType: 'area',
    metricQueries: ['aws.rds.postgresql.CPUUtilization'],
    axes: { y: { label: 'CPU', unit: '%' } },
    legend: ['CPU %'],
  },
  {
    id: 'DBM10417',
    title: 'Database Connections',
    description: 'Active database connections over time',
    chartType: 'line',
    metricQueries: ['aws.rds.postgresql.DatabaseConnections'],
    axes: { y: { label: 'Connections' } },
    legend: ['Connections'],
  },
  {
    id: 'DBM10418',
    title: 'Freeable Memory',
    description: 'Freeable memory on the DB instance',
    chartType: 'area',
    metricQueries: ['aws.rds.postgresql.FreeableMemory'],
    axes: { y: { label: 'Memory', unit: 'bytes' } },
    legend: ['Free Memory'],
  },
  {
    id: 'DBM10419',
    title: 'Storage (Free/Used)',
    description: 'Storage space: free vs allocated',
    chartType: 'area',
    metricQueries: ['aws.rds.postgresql.FreeStorageSpace', 'aws.rds.postgresql.AllocatedStorage'],
    axes: { y: { label: 'Storage', unit: 'bytes' } },
    legend: ['Free', 'Allocated'],
  },
  {
    id: 'DBM10420',
    title: 'IOPS (Read/Write)',
    description: 'Read and write IOPS per second',
    chartType: 'line',
    metricQueries: ['aws.rds.postgresql.ReadIOPS', 'aws.rds.postgresql.WriteIOPS'],
    axes: { y: { label: 'IOPS' } },
    legend: ['Read', 'Write'],
  },
  {
    id: 'DBM10421',
    title: 'Latency (Read/Write)',
    description: 'Read and write latency in milliseconds',
    chartType: 'line',
    metricQueries: ['aws.rds.postgresql.ReadLatency', 'aws.rds.postgresql.WriteLatency'],
    axes: { y: { label: 'Latency', unit: 'ms' } },
    legend: ['Read', 'Write'],
  },
  {
    id: 'DBM10422',
    title: 'Throughput (Read/Write)',
    description: 'Read and write throughput in bytes per second',
    chartType: 'area',
    metricQueries: ['aws.rds.postgresql.ReadThroughput', 'aws.rds.postgresql.WriteThroughput'],
    axes: { y: { label: 'Throughput', unit: 'bytes/s' } },
    legend: ['Read', 'Write'],
  },
  {
    id: 'DBM10423',
    title: 'Network (Receive/Transmit)',
    description: 'Network receive and transmit throughput',
    chartType: 'area',
    metricQueries: ['aws.rds.postgresql.NetworkReceiveThroughput', 'aws.rds.postgresql.NetworkTransmitThroughput'],
    axes: { y: { label: 'Network', unit: 'bytes/s' } },
    legend: ['Receive', 'Transmit'],
  },
  {
    id: 'DBM10424',
    title: 'Disk Queue Depth',
    description: 'Number of outstanding IOs (read/write requests) waiting to access the disk',
    chartType: 'line',
    metricQueries: ['aws.rds.postgresql.DiskQueueDepth'],
    axes: { y: { label: 'Queue Depth' } },
    legend: ['Queue Depth'],
  },
  {
    id: 'DBM10425',
    title: 'Replica Lag',
    description: 'Read replica lag behind the primary instance',
    chartType: 'line',
    metricQueries: ['aws.rds.postgresql.ReplicaLag'],
    axes: { y: { label: 'Lag', unit: 'seconds' } },
    legend: ['Replica Lag'],
  },
  {
    id: 'DBM10426',
    title: 'Database Load (PI)',
    description: 'Performance Insights average active sessions by wait event',
    chartType: 'area',
    metricQueries: ['aws.rds.postgresql.db.load.avg'],
    axes: { y: { label: 'AAS' } },
    legend: ['DB Load'],
  },
  {
    id: 'DBM10427',
    title: 'Top SQL by Load',
    description: 'Top SQL queries ranked by average active sessions',
    chartType: 'bar',
    metricQueries: ['aws.rds.postgresql.db.load.avg.topSql'],
    axes: { y: { label: 'AAS' } },
    legend: ['Top SQL'],
  },
  {
    id: 'DBM10428',
    title: 'Transaction IDs',
    description: 'Maximum used transaction IDs (approaching wraparound)',
    chartType: 'line',
    metricQueries: ['aws.rds.postgresql.MaximumUsedTransactionIDs'],
    axes: { y: { label: 'XID' } },
    legend: ['Max Used XID'],
  },
  {
    id: 'DBM10429',
    title: 'WAL Usage',
    description: 'Write-Ahead Log generation rate',
    chartType: 'area',
    metricQueries: ['aws.rds.postgresql.TransactionLogsDiskUsage', 'aws.rds.postgresql.TransactionLogsGeneration'],
    axes: { y: { label: 'WAL', unit: 'bytes' } },
    legend: ['Disk Usage', 'Generation Rate'],
  },
  {
    id: 'DBM10430',
    title: 'Swap Usage',
    description: 'Swap space used by the DB instance',
    chartType: 'area',
    metricQueries: ['aws.rds.postgresql.SwapUsage'],
    axes: { y: { label: 'Swap', unit: 'bytes' } },
    legend: ['Swap Usage'],
  },
];
