/**
 * Stat Panel Registry — UPTIME (UPT)
 * 16 stat panel registry definitions
 */

import type { StatPanelDefinition } from "./types";

export const UPT_STAT_PANEL_REGISTRY: StatPanelDefinition[] = [
  // │ UPTIME (UPT) — 12 stat panels (8 index + 4 detail)
  // └──────────────────────────────────────────────────────────────────────────────
  {
    statPanelId: "UPT20001",
    module: "UPT",
    title: "Total Monitors",
    icon: "carbon:activity",
    color: "primary",
    unit: "count",
    size: "small",
    dataSource: "stats.total",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total uptime monitors",
    view: "monitoring/uptime/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "UPT20002",
    module: "UPT",
    title: "Up",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "count",
    size: "small",
    dataSource: "stats.up",
    hasTrend: false,
    hasTimeRange: false,
    description: "Monitors currently up",
    view: "monitoring/uptime/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "UPT20003",
    module: "UPT",
    title: "Down",
    icon: "carbon:close-filled",
    color: "error",
    unit: "count",
    size: "small",
    dataSource: "stats.down",
    hasTrend: false,
    hasTimeRange: false,
    description: "Monitors currently down",
    view: "monitoring/uptime/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "UPT20004",
    module: "UPT",
    title: "Degraded",
    icon: "carbon:warning-filled",
    color: "warning",
    unit: "count",
    size: "small",
    dataSource: "stats.degraded",
    hasTrend: false,
    hasTimeRange: false,
    description: "Monitors in degraded state",
    view: "monitoring/uptime/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "UPT20005",
    module: "UPT",
    title: "Paused",
    icon: "carbon:pause-filled",
    color: "info",
    unit: "count",
    size: "small",
    dataSource: "stats.paused",
    hasTrend: false,
    hasTimeRange: false,
    description: "Paused monitors",
    view: "monitoring/uptime/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "UPT20006",
    module: "UPT",
    title: "Avg Uptime (24h)",
    icon: "carbon:percentage",
    color: "success",
    unit: "%",
    size: "small",
    dataSource: "stats.avgUptime",
    hasTrend: false,
    hasTimeRange: false,
    description: "Average uptime percentage in last 24 hours",
    view: "monitoring/uptime/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "UPT20007",
    module: "UPT",
    title: "Avg Response",
    icon: "carbon:time",
    color: "info",
    unit: "ms",
    size: "small",
    dataSource: "stats.avgResponseTime",
    hasTrend: false,
    hasTimeRange: false,
    description: "Average response time",
    view: "monitoring/uptime/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "UPT20008",
    module: "UPT",
    title: "Active Monitors",
    icon: "carbon:activity",
    color: "primary",
    unit: "count",
    size: "small",
    dataSource: "monitors.filter(active && !paused).length",
    hasTrend: false,
    hasTimeRange: false,
    description: "Non-paused active monitors",
    view: "monitoring/uptime/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "UPT20009",
    module: "UPT",
    title: "Detail: Status",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "",
    size: "small",
    dataSource: "monitor.status",
    hasTrend: false,
    hasTimeRange: false,
    description: "Monitor current status (detail panel)",
    view: "monitoring/uptime/MonitorDetailPanel.vue",
    position: "detail-stats",
  },
  {
    statPanelId: "UPT20010",
    module: "UPT",
    title: "Detail: Uptime (24h)",
    icon: "carbon:percentage",
    color: "success",
    unit: "%",
    size: "small",
    dataSource: "monitor.uptimeStats.uptime24h",
    hasTrend: false,
    hasTimeRange: false,
    description: "Monitor 24h uptime percentage (detail panel)",
    view: "monitoring/uptime/MonitorDetailPanel.vue",
    position: "detail-stats",
  },
  {
    statPanelId: "UPT20011",
    module: "UPT",
    title: "Detail: Response Time",
    icon: "carbon:time",
    color: "info",
    unit: "ms",
    size: "small",
    dataSource: "monitor.uptimeStats.avgResponseTime24h",
    hasTrend: false,
    hasTimeRange: false,
    description: "Monitor average response time (detail panel)",
    view: "monitoring/uptime/MonitorDetailPanel.vue",
    position: "detail-stats",
  },
  {
    statPanelId: "UPT20012",
    module: "UPT",
    title: "Detail: Interval",
    icon: "carbon:time",
    color: "primary",
    unit: "s",
    size: "small",
    dataSource: "monitor.interval",
    hasTrend: false,
    hasTimeRange: false,
    description: "Monitor check interval (detail panel)",
    view: "monitoring/uptime/MonitorDetailPanel.vue",
    position: "detail-stats",
  },

  // UPT Row 3: SSL Monitoring (UPT20013–UPT20016)
  {
    statPanelId: "UPT20013",
    module: "UPT",
    title: "SSL Registered",
    icon: "carbon:security",
    color: "success",
    unit: "count",
    size: "small",
    dataSource: "stats.sslTotal",
    hasTrend: false,
    hasTimeRange: false,
    description: "Number of HTTPS/SSL monitors with active SSL certificate data",
    view: "monitoring/uptime/index.vue",
    position: "main-stats",
  },
  {
    statPanelId: "UPT20014",
    module: "UPT",
    title: "SSL Near Expiry",
    icon: "carbon:warning-alt",
    color: "warning",
    unit: "count",
    size: "small",
    dataSource: "stats.sslNearExpire",
    hasTrend: false,
    hasTimeRange: false,
    description: "Number of SSL monitors with less than 30 days until expiry",
    view: "monitoring/uptime/index.vue",
    position: "main-stats",
  },
  {
    statPanelId: "UPT20015",
    module: "UPT",
    title: "Shortest SSL Expiry",
    icon: "carbon:time",
    color: "error",
    unit: "days",
    size: "small",
    dataSource: "stats.sslMinDays",
    hasTrend: false,
    hasTimeRange: false,
    description: "Fewest days remaining until SSL expiry across all monitors",
    view: "monitoring/uptime/index.vue",
    position: "main-stats",
  },
  {
    statPanelId: "UPT20016",
    module: "UPT",
    title: "Longest SSL Expiry",
    icon: "carbon:certificate",
    color: "primary",
    unit: "days",
    size: "small",
    dataSource: "stats.sslMaxDays",
    hasTrend: false,
    hasTimeRange: false,
    description: "Most days remaining until SSL expiry across all monitors",
    view: "monitoring/uptime/index.vue",
    position: "main-stats",
  },
];
