import type { StatPanelDefinition } from "./types";

export const DBM_COCKROACHDB_STAT_PANELS: StatPanelDefinition[] = [
  {
    statPanelId: "DBM20601",
    module: "DBM",
    title: "Total Instances",
    icon: "carbon:data-base",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total registered CockroachDB instances",
    dataSource: "dbCockroachdbStore.instances.length",
    view: "/db-monitoring/cockroachdb",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20602",
    module: "DBM",
    title: "Healthy Clusters",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Clusters with healthy status",
    dataSource: "dbCockroachdbStore.healthyCount",
    view: "/db-monitoring/cockroachdb",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20603",
    module: "DBM",
    title: "Active Nodes",
    icon: "carbon:group",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Live nodes in the cluster",
    dataSource: "crdb.liveness.livenodes",
    view: "/db-monitoring/cockroachdb",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20604",
    module: "DBM",
    title: "Total Ranges",
    icon: "carbon:grid",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: true,
    hasTimeRange: false,
    description: "Total ranges across the cluster",
    dataSource: "crdb.ranges",
    view: "/db-monitoring/cockroachdb",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20605",
    module: "DBM",
    title: "QPS",
    icon: "carbon:activity",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Queries per second",
    dataSource: "rate(crdb.sql.query_count[1m])",
    view: "/db-monitoring/cockroachdb",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20606",
    module: "DBM",
    title: "Active Connections",
    icon: "carbon:connection-two-way",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: true,
    hasTimeRange: false,
    description: "Current SQL connections",
    dataSource: "crdb.sql_conns",
    view: "/db-monitoring/cockroachdb",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20607",
    module: "DBM",
    title: "Storage Utilization",
    icon: "carbon:hard-disk",
    color: "warning",
    unit: "%",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Storage capacity utilization percentage",
    dataSource: "crdb.capacity_used / crdb.capacity * 100",
    view: "/db-monitoring/cockroachdb",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20608",
    module: "DBM",
    title: "Under-Replicated Ranges",
    icon: "carbon:warning-filled",
    color: "error",
    unit: "",
    size: "default",
    hasTrend: true,
    hasTimeRange: false,
    description: "Ranges with fewer replicas than the replication factor",
    dataSource: "crdb.ranges_underreplicated",
    view: "/db-monitoring/cockroachdb",
    position: "overview-middle",
  },
];
