import type { StatPanelDefinition } from "./types";

// Allocated ID range: DBM21401-DBM21408
export const DBM_TIMESCALEDB_STAT_PANELS: StatPanelDefinition[] = [
  {
    statPanelId: "DBM21401",
    module: "DBM",
    title: "Total Instances",
    icon: "carbon:data-base",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total registered TimescaleDB instances",
    dataSource: "dbTimescaledbStore.instances.length",
    view: "/db-monitoring/timescaledb",
    position: "overview-top",
  },
  {
    statPanelId: "DBM21402",
    module: "DBM",
    title: "Healthy",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Instances with healthy status",
    dataSource: "dbTimescaledbStore.healthyCount",
    view: "/db-monitoring/timescaledb",
    position: "overview-top",
  },
  {
    statPanelId: "DBM21403",
    module: "DBM",
    title: "Warning",
    icon: "carbon:warning-filled",
    color: "warning",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Instances with warning status",
    dataSource: "dbTimescaledbStore.warningCount",
    view: "/db-monitoring/timescaledb",
    position: "overview-top",
  },
  {
    statPanelId: "DBM21404",
    module: "DBM",
    title: "Offline",
    icon: "carbon:close-filled",
    color: "error",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Instances currently offline",
    dataSource: "dbTimescaledbStore.offlineCount",
    view: "/db-monitoring/timescaledb",
    position: "overview-top",
  },
  {
    statPanelId: "DBM21405",
    module: "DBM",
    title: "Active Connections",
    icon: "carbon:connect",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Currently active database connections",
    dataSource: "db.timescaledb.connections.active",
    view: "/db-monitoring/timescaledb",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM21406",
    module: "DBM",
    title: "Total Hypertable Size",
    icon: "carbon:hard-disk",
    color: "primary",
    unit: "bytes",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Total storage used by hypertables",
    dataSource: "db.timescaledb.hypertable.total_size_bytes",
    view: "/db-monitoring/timescaledb",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM21407",
    module: "DBM",
    title: "Compression Ratio",
    icon: "carbon:compress",
    color: "info",
    unit: "x",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Average compression ratio across hypertables",
    dataSource: "db.timescaledb.compression.ratio",
    view: "/db-monitoring/timescaledb",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM21408",
    module: "DBM",
    title: "Job Success Rate",
    icon: "carbon:task",
    color: "success",
    unit: "%",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Background job success rate percentage",
    dataSource: "db.timescaledb.job.success_rate",
    view: "/db-monitoring/timescaledb",
    position: "overview-middle",
  },
];
