/**
 * Stat Panel Registry — AI INTELLIGENCE (AID + CRM + PRM)
 * 12 stat panel registry definitions
 */

import type { StatPanelDefinition } from "./types";

export const AID_STAT_PANEL_REGISTRY: StatPanelDefinition[] = [
  // │ AI INTELLIGENCE — Anomaly Detection (AID) — 4 stat panels
  // └──────────────────────────────────────────────────────────────────────────────
  {
    statPanelId: "AID20001",
    module: "AID",
    title: "Total Anomalies",
    icon: "carbon:warning-hex",
    color: "warning",
    valueColor: "#f59e0b",
    unit: "count",
    size: "small",
    dataSource: "aiIntelligenceStore.stats.total",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total anomaly events detected",
    view: "ai-intelligence/anomaly-detection/index.vue",
    position: "stats-row",
  },
  {
    statPanelId: "AID20002",
    module: "AID",
    title: "Critical Anomalies",
    icon: "carbon:warning-alt-filled",
    color: "error",
    valueColor: "#ef4444",
    unit: "count",
    size: "small",
    dataSource: "aiIntelligenceStore.stats.critical",
    hasTrend: false,
    hasTimeRange: false,
    description: "Critical severity anomaly events",
    view: "ai-intelligence/anomaly-detection/index.vue",
    position: "stats-row",
  },
  {
    statPanelId: "AID20003",
    module: "AID",
    title: "Active Rules",
    icon: "carbon:rule",
    color: "info",
    valueColor: "#06b6d4",
    unit: "count",
    size: "small",
    dataSource: "aiIntelligenceStore.activeRules.length",
    hasTrend: false,
    hasTimeRange: false,
    description: "Enabled detection rules",
    view: "ai-intelligence/anomaly-detection/rules.vue",
    position: "stats-row",
  },
  {
    statPanelId: "AID20004",
    module: "AID",
    title: "Avg Anomaly Score",
    icon: "carbon:score",
    color: "primary",
    valueColor: "#3b82f6",
    unit: "",
    size: "small",
    dataSource: "aiIntelligenceStore.stats.avgAnomalyScore",
    hasTrend: false,
    hasTimeRange: false,
    description: "Average anomaly score (0–1)",
    view: "ai-intelligence/anomaly-detection/index.vue",
    position: "stats-row",
  },
  // │ CORRECTIVE MAINTENANCE (CRM) — 4 stat panels
  // └──────────────────────────────────────────────────────────────────────────────
  {
    statPanelId: "CRM20001",
    module: "CRM",
    title: "Total Plans",
    icon: "carbon:document-tasks",
    color: "primary",
    valueColor: "#3b82f6",
    unit: "count",
    size: "small",
    dataSource: "aiIntelligenceStore.remediationStats.total",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total remediation plans generated",
    view: "ai-intelligence/corrective-maintenance/index.vue",
    position: "stats-row",
  },
  {
    statPanelId: "CRM20002",
    module: "CRM",
    title: "Pending Approval",
    icon: "carbon:task-approved",
    color: "warning",
    valueColor: "#f59e0b",
    unit: "count",
    size: "small",
    dataSource: "aiIntelligenceStore.remediationStats.pendingApproval",
    hasTrend: false,
    hasTimeRange: false,
    description: "Plans awaiting approval",
    view: "ai-intelligence/corrective-maintenance/index.vue",
    position: "stats-row",
  },
  {
    statPanelId: "CRM20003",
    module: "CRM",
    title: "Success Rate",
    icon: "carbon:checkmark-outline",
    color: "success",
    valueColor: "#22c55e",
    unit: "%",
    size: "small",
    dataSource: "aiIntelligenceStore.remediationStats.successRate",
    hasTrend: false,
    hasTimeRange: false,
    description: "Percentage of completed vs failed plans",
    view: "ai-intelligence/corrective-maintenance/index.vue",
    position: "stats-row",
  },
  {
    statPanelId: "CRM20004",
    module: "CRM",
    title: "Avg LLM Latency",
    icon: "carbon:time",
    color: "info",
    valueColor: "#06b6d4",
    unit: "ms",
    size: "small",
    dataSource: "aiIntelligenceStore.plans",
    hasTrend: false,
    hasTimeRange: false,
    description: "Average LLM plan generation latency",
    view: "ai-intelligence/corrective-maintenance/index.vue",
    position: "stats-row",
  },
  // │ PREDICTIVE MAINTENANCE (PRM) — 4 stat panels
  // └──────────────────────────────────────────────────────────────────────────────
  {
    statPanelId: "PRM20001",
    module: "PRM",
    title: "Active Models",
    icon: "carbon:model",
    color: "primary",
    valueColor: "#3b82f6",
    unit: "count",
    size: "small",
    dataSource: "predictiveMaintenanceStore.enabledModels.length",
    hasTrend: false,
    hasTimeRange: false,
    description: "Enabled prediction models",
    view: "ai-intelligence/predictive-maintenance/index.vue",
    position: "stats-row",
  },
  {
    statPanelId: "PRM20002",
    module: "PRM",
    title: "Critical Resources",
    icon: "carbon:warning-hex-filled",
    color: "error",
    valueColor: "#ef4444",
    unit: "count",
    size: "small",
    dataSource: "predictiveMaintenanceStore.criticalResources.length",
    hasTrend: false,
    hasTimeRange: false,
    description: "Resources with health score < 40",
    view: "ai-intelligence/predictive-maintenance/index.vue",
    position: "stats-row",
  },
  {
    statPanelId: "PRM20003",
    module: "PRM",
    title: "High-Risk Predictions",
    icon: "carbon:forecast-hail",
    color: "warning",
    valueColor: "#f59e0b",
    unit: "count",
    size: "small",
    dataSource: "predictiveMaintenanceStore.predictions",
    hasTrend: false,
    hasTimeRange: false,
    description: "Predictions with failure probability > 70%",
    view: "ai-intelligence/predictive-maintenance/index.vue",
    position: "stats-row",
  },
  {
    statPanelId: "PRM20004",
    module: "PRM",
    title: "Avg Health Score",
    icon: "carbon:health-cross",
    color: "success",
    valueColor: "#22c55e",
    unit: "/100",
    size: "small",
    dataSource: "predictiveMaintenanceStore.healthScores",
    hasTrend: false,
    hasTimeRange: false,
    description: "Average health score across all resources",
    view: "ai-intelligence/predictive-maintenance/index.vue",
    position: "stats-row",
  },
];
