import type { StatPanelDefinition } from "./types";

export const DBM_MSSQL_STAT_PANELS: StatPanelDefinition[] = [
  {
    statPanelId: "DBM20901",
    module: "DBM",
    title: "Total Instances",
    icon: "carbon:data-base",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total registered MSSQL instances",
    dataSource: "dbMssqlStore.totalInstances",
    view: "/db-monitoring/mssql",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20902",
    module: "DBM",
    title: "Online",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Instances currently online",
    dataSource: "dbMssqlStore.stats?.onlineInstances",
    view: "/db-monitoring/mssql",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20903",
    module: "DBM",
    title: "Batch Req/s",
    icon: "carbon:activity",
    color: "primary",
    unit: "/s",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Batch requests per second",
    dataSource: "db.mssql.batch_requests_per_sec",
    view: "/db-monitoring/mssql",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20904",
    module: "DBM",
    title: "Page Life Expectancy",
    icon: "carbon:timer",
    color: "primary",
    unit: "s",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Buffer pool page life expectancy in seconds",
    dataSource: "db.mssql.page_life_expectancy",
    view: "/db-monitoring/mssql",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20905",
    module: "DBM",
    title: "Buffer Cache Hit",
    icon: "carbon:target",
    color: "success",
    unit: "%",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Buffer cache hit ratio percentage",
    dataSource: "db.mssql.buffer_cache_hit_ratio",
    view: "/db-monitoring/mssql",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20906",
    module: "DBM",
    title: "User Connections",
    icon: "carbon:connection-two-way",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: true,
    hasTimeRange: false,
    description: "Current user connections",
    dataSource: "db.mssql.user_connections",
    view: "/db-monitoring/mssql",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20907",
    module: "DBM",
    title: "Deadlocks",
    icon: "carbon:warning-filled",
    color: "error",
    unit: "/s",
    size: "default",
    hasTrend: true,
    hasTimeRange: false,
    description: "Deadlocks per second",
    dataSource: "db.mssql.deadlocks_per_sec",
    view: "/db-monitoring/mssql",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20908",
    module: "DBM",
    title: "Compilations/s",
    icon: "carbon:code",
    color: "warning",
    unit: "/s",
    size: "default",
    hasTrend: true,
    hasTimeRange: false,
    description: "SQL compilations per second",
    dataSource: "db.mssql.sql_compilations_per_sec",
    view: "/db-monitoring/mssql",
    position: "overview-middle",
  },
];
