/**
 * Stat Panel Registry — AWS DynamoDB (DBM)
 * 8 stat panel registry definitions (DBM20301–DBM20308)
 */

import type { StatPanelDefinition } from './types';

export const DBM_AWS_DYNAMODB_STAT_PANELS: StatPanelDefinition[] = [
  {
    statPanelId: 'DBM20301',
    module: 'DBM',
    title: 'Total Tables',
    icon: 'carbon:table',
    color: 'primary',
    unit: '',
    size: 'default',
    hasTrend: true,
    hasTimeRange: true,
    description: 'Total number of DynamoDB tables across all monitored regions',
    dataSource: 'dbDynamoDBStore.totalTables',
    view: '/monitoring/db/dynamodb',
    position: 'overview-top',
  },
  {
    statPanelId: 'DBM20302',
    module: 'DBM',
    title: 'Active Tables',
    icon: 'carbon:checkmark-filled',
    color: 'success',
    unit: '',
    size: 'default',
    hasTrend: true,
    hasTimeRange: true,
    description: 'Number of DynamoDB tables currently in ACTIVE status',
    dataSource: 'dbDynamoDBStore.activeTables',
    view: '/monitoring/db/dynamodb',
    position: 'overview-top',
  },
  {
    statPanelId: 'DBM20303',
    module: 'DBM',
    title: 'Throttled Tables (24h)',
    icon: 'carbon:warning-filled',
    color: 'error',
    unit: '',
    size: 'default',
    hasTrend: true,
    hasTimeRange: true,
    description: 'Number of tables experiencing throttling in the last 24 hours',
    dataSource: 'dbDynamoDBStore.throttledTables24h',
    view: '/monitoring/db/dynamodb',
    position: 'overview-top',
  },
  {
    statPanelId: 'DBM20304',
    module: 'DBM',
    title: 'Global Tables',
    icon: 'carbon:globe',
    color: 'info',
    unit: '',
    size: 'default',
    hasTrend: false,
    hasTimeRange: false,
    description: 'Number of DynamoDB global tables with multi-region replication enabled',
    dataSource: 'dbDynamoDBStore.globalTables',
    view: '/monitoring/db/dynamodb',
    position: 'overview-middle',
  },
  {
    statPanelId: 'DBM20305',
    module: 'DBM',
    title: 'Avg Latency',
    icon: 'carbon:timer',
    color: 'success',
    unit: 'ms',
    size: 'default',
    hasTrend: true,
    hasTimeRange: true,
    description: 'Average successful request latency across all tables (warning >50ms, critical >100ms)',
    dataSource: 'dbDynamoDBStore.avgLatency',
    view: '/monitoring/db/dynamodb',
    position: 'overview-middle',
  },
  {
    statPanelId: 'DBM20306',
    module: 'DBM',
    title: 'Total Errors',
    icon: 'carbon:warning-alt',
    color: 'error',
    unit: '',
    size: 'default',
    hasTrend: true,
    hasTimeRange: true,
    description: 'Total system and user errors across all DynamoDB tables',
    dataSource: 'dbDynamoDBStore.totalErrors',
    view: '/monitoring/db/dynamodb',
    position: 'overview-middle',
  },
  {
    statPanelId: 'DBM20307',
    module: 'DBM',
    title: 'DAX Clusters',
    icon: 'carbon:layer-group',
    color: 'purple',
    unit: '',
    size: 'default',
    hasTrend: false,
    hasTimeRange: false,
    description: 'Number of DAX (DynamoDB Accelerator) clusters deployed',
    dataSource: 'dbDynamoDBStore.daxClusters',
    view: '/monitoring/db/dynamodb',
    position: 'overview-bottom',
  },
  {
    statPanelId: 'DBM20308',
    module: 'DBM',
    title: 'Active Alerts',
    icon: 'carbon:notification-filled',
    color: 'warning',
    unit: '',
    size: 'default',
    hasTrend: false,
    hasTimeRange: false,
    description: 'Currently active alerts for DynamoDB tables (throttling, errors, latency)',
    dataSource: 'dbDynamoDBStore.activeAlerts',
    view: '/monitoring/db/dynamodb',
    position: 'overview-bottom',
  },
];
