/**
 * Stat Panel Registry — TRACES (TRC)
 * 8 stat panel registry definitions
 */

import type { StatPanelDefinition } from "./types";

export const TRC_STAT_PANEL_REGISTRY: StatPanelDefinition[] = [
  // │ TRACES (TRC) — 8 stat panels (4 index + 4 detail)
  // └──────────────────────────────────────────────────────────────────────────────
  {
    statPanelId: "TRC20001",
    module: "TRC",
    title: "Traces",
    icon: "carbon:flow",
    color: "purple",
    unit: "count",
    size: "small",
    dataSource: "tracesStore.filteredTraces.length",
    hasTrend: true,
    hasTimeRange: true,
    description: "Total traces in current time range",
    view: "telemetry/traces/index.vue",
    position: "stats-row",
  },
  {
    statPanelId: "TRC20002",
    module: "TRC",
    title: "Services",
    icon: "carbon:service-id",
    color: "primary",
    unit: "count",
    size: "small",
    dataSource: "tracesStore.services.length",
    hasTrend: false,
    hasTimeRange: false,
    description: "Unique services in traces",
    view: "telemetry/traces/index.vue",
    position: "stats-row",
  },
  {
    statPanelId: "TRC20003",
    module: "TRC",
    title: "OK",
    icon: "carbon:checkmark-outline",
    color: "success",
    unit: "count",
    size: "small",
    dataSource: "okCount",
    hasTrend: true,
    hasTimeRange: true,
    description: "Successful traces count",
    view: "telemetry/traces/index.vue",
    position: "stats-row",
  },
  {
    statPanelId: "TRC20004",
    module: "TRC",
    title: "Errors",
    icon: "carbon:warning-alt",
    color: "error",
    unit: "count",
    size: "small",
    dataSource: "errorsCount",
    hasTrend: true,
    hasTimeRange: true,
    description: "Error traces count",
    view: "telemetry/traces/index.vue",
    position: "stats-row",
  },
  {
    statPanelId: "TRC20005",
    module: "TRC",
    title: "Duration",
    icon: "carbon:time",
    color: "info",
    unit: "ms",
    size: "small",
    dataSource: "trace.duration",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total trace duration (detail view)",
    view: "telemetry/traces/detail.vue",
    position: "detail-stats-row",
  },
  {
    statPanelId: "TRC20006",
    module: "TRC",
    title: "Spans",
    icon: "carbon:flow",
    color: "primary",
    unit: "count",
    size: "small",
    dataSource: "trace.spans.length",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total span count in trace (detail view)",
    view: "telemetry/traces/detail.vue",
    position: "detail-stats-row",
  },
  {
    statPanelId: "TRC20007",
    module: "TRC",
    title: "Services",
    icon: "carbon:service-id",
    color: "purple",
    unit: "count",
    size: "small",
    dataSource: "unique services in trace",
    hasTrend: false,
    hasTimeRange: false,
    description: "Unique services in trace detail",
    view: "telemetry/traces/detail.vue",
    position: "detail-stats-row",
  },
  {
    statPanelId: "TRC20008",
    module: "TRC",
    title: "Errors",
    icon: "carbon:warning-alt",
    color: "error",
    unit: "count",
    size: "small",
    dataSource: "error spans count",
    hasTrend: false,
    hasTimeRange: false,
    description: "Error spans in trace detail",
    view: "telemetry/traces/detail.vue",
    position: "detail-stats-row",
  },
];
