import type { StatPanelDefinition } from "./types";

export const DBM_CLICKHOUSE_STAT_PANELS: StatPanelDefinition[] = [
  {
    statPanelId: "DBM20201",
    module: "DBM",
    title: "Total Instances",
    icon: "carbon:data-base",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total registered ClickHouse instances",
    dataSource: "dbClickhouseStore.instances.length",
    view: "/db-monitoring/clickhouse",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20202",
    module: "DBM",
    title: "Healthy",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Instances with healthy status",
    dataSource: "dbClickhouseStore.healthyCount",
    view: "/db-monitoring/clickhouse",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20203",
    module: "DBM",
    title: "Degraded",
    icon: "carbon:warning-filled",
    color: "warning",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Instances with degraded performance",
    dataSource: "dbClickhouseStore.degradedCount",
    view: "/db-monitoring/clickhouse",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20204",
    module: "DBM",
    title: "Unreachable",
    icon: "carbon:close-filled",
    color: "error",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Instances currently unreachable",
    dataSource: "dbClickhouseStore.unreachableCount",
    view: "/db-monitoring/clickhouse",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20205",
    module: "DBM",
    title: "Active Queries",
    icon: "carbon:query",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Currently running queries",
    dataSource: "db.clickhouse.system.Query",
    view: "/db-monitoring/clickhouse",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20206",
    module: "DBM",
    title: "Memory Usage",
    icon: "carbon:memory",
    color: "warning",
    unit: "bytes",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Total memory tracked by ClickHouse",
    dataSource: "db.clickhouse.system.MemoryTracking",
    view: "/db-monitoring/clickhouse",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20207",
    module: "DBM",
    title: "Max Replication Lag",
    icon: "carbon:time",
    color: "error",
    unit: "s",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Maximum absolute delay across replicas",
    dataSource: "db.clickhouse.async.ReplicasMaxAbsoluteDelay",
    view: "/db-monitoring/clickhouse",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20208",
    module: "DBM",
    title: "Disk Usage",
    icon: "carbon:hard-disk",
    color: "primary",
    unit: "%",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Average disk utilization percentage",
    dataSource: "db.clickhouse.disk.used_percent",
    view: "/db-monitoring/clickhouse",
    position: "overview-middle",
  },
];
