/**
 * Stat Panel Registry — MariaDB (DBM)
 * 6 stat panel registry definitions
 */

import type { StatPanelDefinition } from "./types";

export const DBM_MARIADB_STAT_PANELS: StatPanelDefinition[] = [
  {
    statPanelId: "DBM21001",
    module: "DBM",
    title: "Query Cache Hit Ratio",
    icon: "carbon:chart-relationship",
    color: "primary",
    unit: "ratio",
    size: "default",
    dataSource: "queryCache.hitRatio",
    hasTrend: true,
    hasTimeRange: true,
    description: "MariaDB query cache hit ratio (higher is better)",
    view: "monitoring/db-mysql/components/QueryCacheSection.vue",
    position: "overview-mariadb",
  },
  {
    statPanelId: "DBM21002",
    module: "DBM",
    title: "Aria Pagecache Hit Ratio",
    icon: "carbon:chart-areaspline",
    color: "success",
    unit: "ratio",
    size: "default",
    dataSource: "aria.pagecacheHitRatio",
    hasTrend: true,
    hasTimeRange: true,
    description: "MariaDB Aria engine pagecache hit ratio",
    view: "monitoring/db-mysql/components/AriaEngineSection.vue",
    position: "overview-mariadb",
  },
  {
    statPanelId: "DBM21003",
    module: "DBM",
    title: "Thread Pool Utilization",
    icon: "carbon:chart-multitype",
    color: "info",
    unit: "ratio",
    size: "default",
    dataSource: "threadPool.utilization",
    hasTrend: true,
    hasTimeRange: true,
    description: "MariaDB thread pool utilization (pool-of-threads)",
    view: "monitoring/db-mysql/components/ThreadPoolSection.vue",
    position: "overview-mariadb",
  },
  {
    statPanelId: "DBM21004",
    module: "DBM",
    title: "ColumnStore Extent Utilization",
    icon: "carbon:storage-knowledge",
    color: "primary",
    unit: "ratio",
    size: "default",
    dataSource: "columnStore.extentUtilization",
    hasTrend: true,
    hasTimeRange: true,
    description: "MariaDB ColumnStore extent map utilization",
    view: "monitoring/db-mysql/components/ColumnStoreSection.vue",
    position: "overview-mariadb",
  },
  {
    statPanelId: "DBM21005",
    module: "DBM",
    title: "Spider Conn Pool Utilization",
    icon: "carbon:network-2",
    color: "warning",
    unit: "ratio",
    size: "default",
    dataSource: "spider.connPoolUtilization",
    hasTrend: true,
    hasTimeRange: true,
    description: "MariaDB Spider engine connection pool utilization",
    view: "monitoring/db-mysql/components/SpiderSection.vue",
    position: "overview-mariadb",
  },
  {
    statPanelId: "DBM21006",
    module: "DBM",
    title: "Query Cache Fragmentation",
    icon: "carbon:chart-bubble",
    color: "error",
    unit: "ratio",
    size: "default",
    dataSource: "queryCache.fragmentation",
    hasTrend: true,
    hasTimeRange: true,
    description: "MariaDB query cache fragmentation (lower is better)",
    view: "monitoring/db-mysql/components/QueryCacheSection.vue",
    position: "overview-mariadb",
  },
];
