import type { StatPanelDefinition } from "./types";

// Allocated ID range: DBM21301-DBM21308
export const DBM_SQLITE3_STAT_PANELS: StatPanelDefinition[] = [
  {
    statPanelId: "DBM21301",
    module: "DBM",
    title: "Total Databases",
    icon: "carbon:data-base",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total registered SQLite3 databases",
    dataSource: "dbSqlite3Store.databases.length",
    view: "/db-monitoring/sqlite3",
    position: "overview-top",
  },
  {
    statPanelId: "DBM21302",
    module: "DBM",
    title: "Total File Size",
    icon: "carbon:hard-disk",
    color: "primary",
    unit: "bytes",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Aggregate file size of all databases",
    dataSource: "dbSqlite3Store.totalFileSize",
    view: "/db-monitoring/sqlite3",
    position: "overview-top",
  },
  {
    statPanelId: "DBM21303",
    module: "DBM",
    title: "WAL Mode Count",
    icon: "carbon:journal",
    color: "success",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Databases using WAL journal mode",
    dataSource: "dbSqlite3Store.walModeCount",
    view: "/db-monitoring/sqlite3",
    position: "overview-top",
  },
  {
    statPanelId: "DBM21304",
    module: "DBM",
    title: "Integrity Issues",
    icon: "carbon:warning-filled",
    color: "error",
    unit: "",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Databases with integrity check failures",
    dataSource: "dbSqlite3Store.criticalCount",
    view: "/db-monitoring/sqlite3",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM21305",
    module: "DBM",
    title: "Avg Cache Hit Ratio",
    icon: "carbon:chart-line",
    color: "info",
    unit: "%",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Average page cache hit ratio across databases",
    dataSource: "sqlite.cache.hit_ratio",
    view: "/db-monitoring/sqlite3",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM21306",
    module: "DBM",
    title: "Lock Contentions",
    icon: "carbon:locked",
    color: "warning",
    unit: "",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Active lock contentions across databases",
    dataSource: "sqlite.lock.contention_count",
    view: "/db-monitoring/sqlite3",
    position: "overview-middle",
  },
];
