import type { StatPanelDefinition } from "./types";

export const QRY_STAT_PANELS: StatPanelDefinition[] = [
  {
    statPanelId: "QRY20001",
    module: "QRY",
    title: "Total Queries",
    icon: "carbon:query-queue",
    color: "primary",
    unit: "",
    size: "default",
    dataSource: "db_mysql_queries",
    hasTrend: false,
    hasTimeRange: true,
    description: "Total query count across all engines",
    view: "db-monitoring/query-analytics/QANView.vue",
    position: "qan-stats-total",
  },
  {
    statPanelId: "QRY20002",
    module: "QRY",
    title: "Avg Latency",
    icon: "carbon:timer",
    color: "info",
    unit: "ms",
    size: "default",
    dataSource: "db_mysql_queries",
    hasTrend: true,
    hasTimeRange: true,
    description: "Average query latency",
    view: "db-monitoring/query-analytics/QANView.vue",
    position: "qan-stats-avg-latency",
  },
  {
    statPanelId: "QRY20003",
    module: "QRY",
    title: "Slow Queries",
    icon: "carbon:warning-alt",
    color: "warning",
    unit: "",
    size: "default",
    dataSource: "db_mysql_queries",
    hasTrend: true,
    hasTimeRange: true,
    description: "Queries with latency > 100ms",
    view: "db-monitoring/query-analytics/QANView.vue",
    position: "qan-stats-slow",
  },
  {
    statPanelId: "QRY20004",
    module: "QRY",
    title: "Unique Fingerprints",
    icon: "carbon:fingerprint",
    color: "success",
    unit: "",
    size: "default",
    dataSource: "db_mysql_queries",
    hasTrend: false,
    hasTimeRange: true,
    description: "Distinct query patterns",
    view: "db-monitoring/query-analytics/QANView.vue",
    position: "qan-stats-fingerprints",
  },
];
