import type { StatPanelDefinition } from "./types";

export const DBM_MYSQL_STAT_PANELS: StatPanelDefinition[] = [
  {
    statPanelId: "DBM20001",
    module: "DBM",
    title: "Total Instances",
    icon: "carbon:data-base",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total registered MySQL/MariaDB/Percona instances",
    dataSource: "dbMysqlStore.stats.instanceCount",
    view: "/monitoring/db/mysql",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20002",
    module: "DBM",
    title: "Online",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Instances currently online",
    dataSource: "dbMysqlStore.onlineCount",
    view: "/monitoring/db/mysql",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20003",
    module: "DBM",
    title: "Degraded",
    icon: "carbon:warning-filled",
    color: "warning",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Instances with degraded performance",
    dataSource: "dbMysqlStore.degradedCount",
    view: "/monitoring/db/mysql",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20004",
    module: "DBM",
    title: "Offline",
    icon: "carbon:close-filled",
    color: "error",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Instances currently offline",
    dataSource: "dbMysqlStore.offlineCount",
    view: "/monitoring/db/mysql",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20005",
    module: "DBM",
    title: "Connection Utilization",
    icon: "carbon:connection-two-way",
    color: "primary",
    unit: "%",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Average connection utilization across instances",
    dataSource: "db.mysql.connection_utilization",
    view: "/monitoring/db/mysql",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20006",
    module: "DBM",
    title: "Buffer Pool Hit Ratio",
    icon: "carbon:cached",
    color: "success",
    unit: "%",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Average InnoDB buffer pool hit ratio",
    dataSource: "db.mysql.buffer_pool_hit_ratio",
    view: "/monitoring/db/mysql",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20007",
    module: "DBM",
    title: "Replication Lag",
    icon: "carbon:time",
    color: "warning",
    unit: "s",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Max replication lag across replicas",
    dataSource: "db.mysql.replication_lag_seconds",
    view: "/monitoring/db/mysql",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20008",
    module: "DBM",
    title: "Active Alerts",
    icon: "carbon:notification-filled",
    color: "error",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Number of active monitoring alerts",
    dataSource: "db.mysql.active_alerts",
    view: "/monitoring/db/mysql",
    position: "overview-middle",
  },
];
