/**
 * Stat Panel Registry — STATUS PAGE (STP)
 * 8 stat panel registry definitions
 */

import type { StatPanelDefinition } from "./types";

export const STP_STAT_PANEL_REGISTRY: StatPanelDefinition[] = [
  // │ STATUS PAGE (STP) — 8 stat panels
  // └──────────────────────────────────────────────────────────────────────────────
  {
    statPanelId: "STP20001",
    module: "STP",
    title: "Total Pages",
    icon: "carbon:document",
    color: "primary",
    unit: "count",
    size: "small",
    dataSource: "stats.total",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total status pages",
    view: "monitoring/status-page/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "STP20002",
    module: "STP",
    title: "Operational",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "count",
    size: "small",
    dataSource: "stats.operational",
    hasTrend: false,
    hasTimeRange: false,
    description: "Fully operational pages",
    view: "monitoring/status-page/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "STP20003",
    module: "STP",
    title: "Degraded",
    icon: "carbon:warning-filled",
    color: "warning",
    unit: "count",
    size: "small",
    dataSource: "stats.degraded",
    hasTrend: false,
    hasTimeRange: false,
    description: "Degraded status pages",
    view: "monitoring/status-page/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "STP20004",
    module: "STP",
    title: "Outage",
    icon: "carbon:close-filled",
    color: "error",
    unit: "count",
    size: "small",
    dataSource: "stats.outage",
    hasTrend: false,
    hasTimeRange: false,
    description: "Pages in outage state",
    view: "monitoring/status-page/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "STP20005",
    module: "STP",
    title: "Public Pages",
    icon: "carbon:globe",
    color: "info",
    unit: "count",
    size: "small",
    dataSource: "stats.publicPages",
    hasTrend: false,
    hasTimeRange: false,
    description: "Publicly accessible status pages",
    view: "monitoring/status-page/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "STP20006",
    module: "STP",
    title: "Private Pages",
    icon: "carbon:locked",
    color: "purple",
    unit: "count",
    size: "small",
    dataSource: "stats.privatePages",
    hasTrend: false,
    hasTimeRange: false,
    description: "Private/internal status pages",
    view: "monitoring/status-page/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "STP20007",
    module: "STP",
    title: "Active Incidents",
    icon: "carbon:warning-alt",
    color: "error",
    unit: "count",
    size: "small",
    dataSource: "stats.activeIncidents",
    hasTrend: false,
    hasTimeRange: false,
    description: "Currently active incidents",
    view: "monitoring/status-page/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "STP20008",
    module: "STP",
    title: "Total Monitors",
    icon: "carbon:activity",
    color: "info",
    unit: "count",
    size: "small",
    dataSource: "stats.totalMonitors",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total monitors across status pages",
    view: "monitoring/status-page/index.vue",
    position: "stats-row-2",
  },
];
