import type { StatPanelDefinition } from "./types";

// Allocated ID range: DBM20501-DBM20510
export const DBM_AWS_RDS_AURORA_STAT_PANELS: StatPanelDefinition[] = [
  {
    statPanelId: "DBM20501",
    module: "DBM",
    title: "Total Clusters",
    icon: "carbon:data-base",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total registered Aurora clusters",
    dataSource: "dbAwsRdsAuroraStore.clusters.length",
    view: "/db-monitoring/aws-rds-aurora",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20502",
    module: "DBM",
    title: "Total Instances",
    icon: "carbon:cloud-service-management",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total Aurora instances across all clusters",
    dataSource: "dbAwsRdsAuroraStore.totalInstanceCount",
    view: "/db-monitoring/aws-rds-aurora",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20503",
    module: "DBM",
    title: "Healthy Clusters",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Aurora clusters with available status",
    dataSource: "dbAwsRdsAuroraStore.healthyClusterCount",
    view: "/db-monitoring/aws-rds-aurora",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20504",
    module: "DBM",
    title: "Warnings",
    icon: "carbon:warning-filled",
    color: "warning",
    unit: "",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Clusters in modifying/upgrading state",
    dataSource: "dbAwsRdsAuroraStore.warningClusterCount",
    view: "/db-monitoring/aws-rds-aurora",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20505",
    module: "DBM",
    title: "Critical",
    icon: "carbon:close-filled",
    color: "error",
    unit: "",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Clusters in failed or failing-over state",
    dataSource: "dbAwsRdsAuroraStore.criticalClusterCount",
    view: "/db-monitoring/aws-rds-aurora",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20506",
    module: "DBM",
    title: "Serverless Clusters",
    icon: "carbon:scale",
    color: "info",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Aurora Serverless v2 clusters",
    dataSource: "dbAwsRdsAuroraStore.serverlessClusterCount",
    view: "/db-monitoring/aws-rds-aurora",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20507",
    module: "DBM",
    title: "Global Databases",
    icon: "carbon:earth-filled",
    color: "purple",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Aurora Global Database clusters",
    dataSource: "dbAwsRdsAuroraStore.globalClusterCount",
    view: "/db-monitoring/aws-rds-aurora",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20508",
    module: "DBM",
    title: "DB Load (AAS)",
    icon: "carbon:chart-line",
    color: "info",
    unit: "AAS",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Current database load in average active sessions",
    dataSource: "aurora.db_load_aas",
    view: "/db-monitoring/aws-rds-aurora",
    position: "detail-top",
  },
  {
    statPanelId: "DBM20509",
    module: "DBM",
    title: "Replica Lag",
    icon: "carbon:time",
    color: "warning",
    unit: "ms",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Maximum replica lag across reader instances",
    dataSource: "aurora.replica_lag_ms",
    view: "/db-monitoring/aws-rds-aurora",
    position: "detail-top",
  },
  {
    statPanelId: "DBM20510",
    module: "DBM",
    title: "Cache Hit Ratio",
    icon: "carbon:bullseye",
    color: "success",
    unit: "%",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Buffer cache hit ratio for writer instance",
    dataSource: "aurora.buffer_cache_hit_ratio",
    view: "/db-monitoring/aws-rds-aurora",
    position: "detail-top",
  },
];
