/**
 * Stat Panel Registry — DB MONITORING INVENTORY (INV)
 * 8 stat panel definitions
 */

import type { StatPanelDefinition } from "./types";

export const INV_STAT_PANEL_REGISTRY: StatPanelDefinition[] = [
  {
    statPanelId: "INV20001",
    module: "INV",
    title: "Total Instances",
    icon: "carbon:data-base",
    color: "primary",
    unit: "count",
    size: "small",
    dataSource: "stats.total",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total registered database instances",
    view: "db-monitoring/inventory/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "INV20002",
    module: "INV",
    title: "Online",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "count",
    size: "small",
    dataSource: "stats.online",
    hasTrend: false,
    hasTimeRange: false,
    description: "Database instances currently online",
    view: "db-monitoring/inventory/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "INV20003",
    module: "INV",
    title: "Offline",
    icon: "carbon:warning-filled",
    color: "error",
    unit: "count",
    size: "small",
    dataSource: "stats.offline",
    hasTrend: false,
    hasTimeRange: false,
    description: "Database instances currently offline",
    view: "db-monitoring/inventory/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "INV20004",
    module: "INV",
    title: "Degraded",
    icon: "carbon:warning",
    color: "warning",
    unit: "count",
    size: "small",
    dataSource: "stats.degraded",
    hasTrend: false,
    hasTimeRange: false,
    description: "Database instances in degraded state",
    view: "db-monitoring/inventory/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "INV20005",
    module: "INV",
    title: "DB Types",
    icon: "carbon:category",
    color: "info",
    unit: "count",
    size: "small",
    dataSource: "stats.typeCount",
    hasTrend: false,
    hasTimeRange: false,
    description: "Distinct database types in use",
    view: "db-monitoring/inventory/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "INV20006",
    module: "INV",
    title: "Providers",
    icon: "carbon:cloud",
    color: "info",
    unit: "count",
    size: "small",
    dataSource: "stats.providerCount",
    hasTrend: false,
    hasTimeRange: false,
    description: "Distinct providers in use",
    view: "db-monitoring/inventory/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "INV20007",
    module: "INV",
    title: "Active Rules",
    icon: "carbon:rule",
    color: "primary",
    unit: "count",
    size: "small",
    dataSource: "stats.activeRules",
    hasTrend: false,
    hasTimeRange: false,
    description: "Active monitoring rules",
    view: "db-monitoring/inventory/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "INV20008",
    module: "INV",
    title: "Maintenance",
    icon: "carbon:tools",
    color: "info",
    unit: "count",
    size: "small",
    dataSource: "stats.maintenance",
    hasTrend: false,
    hasTimeRange: false,
    description: "Instances in scheduled maintenance",
    view: "db-monitoring/inventory/index.vue",
    position: "stats-row-1",
  },
];
