/**
 * Stat Panel Registry — NETWORK MAP (NWM)
 * 8 stat panel registry definitions
 */

import type { StatPanelDefinition } from "./types";

export const NWM_STAT_PANEL_REGISTRY: StatPanelDefinition[] = [
  // │ NETWORK MAP (NWM) — 8 stat panels
  // └──────────────────────────────────────────────────────────────────────────────
  {
    statPanelId: "NWM20001",
    module: "NWM",
    title: "Total Nodes",
    icon: "carbon:network-3",
    color: "primary",
    unit: "count",
    size: "small",
    dataSource: "stats.totalNodes",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total network nodes",
    view: "monitoring/network-map/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "NWM20002",
    module: "NWM",
    title: "Healthy",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "count",
    size: "small",
    dataSource: "stats.healthyNodes",
    hasTrend: false,
    hasTimeRange: false,
    description: "Healthy network nodes",
    view: "monitoring/network-map/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "NWM20003",
    module: "NWM",
    title: "Degraded",
    icon: "carbon:warning-filled",
    color: "warning",
    unit: "count",
    size: "small",
    dataSource: "stats.degradedNodes",
    hasTrend: false,
    hasTimeRange: false,
    description: "Degraded network nodes",
    view: "monitoring/network-map/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "NWM20004",
    module: "NWM",
    title: "Down",
    icon: "carbon:close-filled",
    color: "error",
    unit: "count",
    size: "small",
    dataSource: "stats.downNodes",
    hasTrend: false,
    hasTimeRange: false,
    description: "Down network nodes",
    view: "monitoring/network-map/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "NWM20005",
    module: "NWM",
    title: "Connections",
    icon: "carbon:connect",
    color: "info",
    unit: "count",
    size: "small",
    dataSource: "stats.totalConnections",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total network connections",
    view: "monitoring/network-map/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "NWM20006",
    module: "NWM",
    title: "Avg Latency",
    icon: "carbon:time",
    color: "info",
    unit: "ms",
    size: "small",
    dataSource: "stats.avgLatency",
    hasTrend: false,
    hasTimeRange: false,
    description: "Average network latency",
    view: "monitoring/network-map/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "NWM20007",
    module: "NWM",
    title: "Active Nodes",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "count",
    size: "small",
    dataSource: "nodes.filter(healthy).length",
    hasTrend: false,
    hasTimeRange: false,
    description: "Currently healthy network nodes",
    view: "monitoring/network-map/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "NWM20008",
    module: "NWM",
    title: "Maintenance",
    icon: "carbon:tool-box",
    color: "purple",
    unit: "count",
    size: "small",
    dataSource: "nodes.filter(maintenance).length",
    hasTrend: false,
    hasTimeRange: false,
    description: "Nodes in maintenance",
    view: "monitoring/network-map/index.vue",
    position: "stats-row-2",
  },
];
