/**
 * Stat Panel Registry — KUBERNETES (K8S)
 * 20 stat panel registry definitions
 */

import type { StatPanelDefinition } from "./types";

export const K8S_STAT_PANEL_REGISTRY: StatPanelDefinition[] = [
  // │ KUBERNETES (K8S) — 12 stat panels
  // └──────────────────────────────────────────────────────────────────────────────
  {
    statPanelId: "K8S20001",
    module: "K8S",
    title: "Clusters",
    icon: "carbon:kubernetes",
    color: "primary",
    unit: "count",
    size: "small",
    dataSource: "overview.clusters",
    hasTrend: false,
    hasTimeRange: false,
    description: "Registered Kubernetes clusters",
    view: "monitoring/kubernetes/overview.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "K8S20002",
    module: "K8S",
    title: "Nodes",
    icon: "carbon:bare-metal-server",
    color: "success",
    unit: "count",
    size: "small",
    dataSource: "overview.nodes",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total cluster nodes (ready/total)",
    view: "monitoring/kubernetes/overview.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "K8S20003",
    module: "K8S",
    title: "Running Pods",
    icon: "carbon:cube",
    color: "info",
    unit: "count",
    size: "small",
    dataSource: "overview.runningPods",
    hasTrend: true,
    hasTimeRange: false,
    description: "Pods currently in Running phase",
    view: "monitoring/kubernetes/overview.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "K8S20004",
    module: "K8S",
    title: "Deployments",
    icon: "carbon:deploy",
    color: "purple",
    unit: "count",
    size: "small",
    dataSource: "overview.deployments",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total Deployments across all namespaces",
    view: "monitoring/kubernetes/overview.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "K8S20005",
    module: "K8S",
    title: "Namespaces",
    icon: "carbon:folder",
    color: "info",
    unit: "count",
    size: "small",
    dataSource: "overview.namespaces",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total namespaces in cluster",
    view: "monitoring/kubernetes/overview.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "K8S20006",
    module: "K8S",
    title: "Services",
    icon: "carbon:network-4",
    color: "success",
    unit: "count",
    size: "small",
    dataSource: "overview.services",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total Services across all namespaces",
    view: "monitoring/kubernetes/overview.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "K8S20007",
    module: "K8S",
    title: "CPU Usage",
    icon: "carbon:chip",
    color: "primary",
    unit: "percent",
    size: "small",
    dataSource: "cpuUsagePercentages.real",
    hasTrend: true,
    hasTimeRange: true,
    description: "Cluster-wide CPU utilisation (real)",
    view: "monitoring/kubernetes/overview.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "K8S20008",
    module: "K8S",
    title: "Memory Usage",
    icon: "ph:memory-fill",
    color: "purple",
    unit: "percent",
    size: "small",
    dataSource: "ramUsagePercentages.real",
    hasTrend: true,
    hasTimeRange: true,
    description: "Cluster-wide memory utilisation (real)",
    view: "monitoring/kubernetes/overview.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "K8S20009",
    module: "K8S",
    title: "Autoscalers",
    icon: "carbon:scale",
    color: "success",
    unit: "count",
    size: "small",
    dataSource: "hpaTotalCount",
    hasTrend: false,
    hasTimeRange: false,
    description: "Active HorizontalPodAutoscalers",
    view: "monitoring/kubernetes/overview.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "K8S20010",
    module: "K8S",
    title: "PDB Disruptions",
    icon: "carbon:warning-alt",
    color: "warning",
    unit: "count",
    size: "small",
    dataSource: "pdbTotalDisruptionsAllowed",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total pod disruptions currently allowed by PDBs",
    view: "monitoring/kubernetes/overview.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "K8S20011",
    module: "K8S",
    title: "Pending Pods",
    icon: "carbon:time",
    color: "warning",
    unit: "count",
    size: "small",
    dataSource: "podsStatusReason.find(Pending).value",
    hasTrend: true,
    hasTimeRange: false,
    description: "Pods stuck in Pending phase",
    view: "monitoring/kubernetes/overview.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "K8S20012",
    module: "K8S",
    title: "Failed Pods",
    icon: "carbon:close-filled",
    color: "error",
    unit: "count",
    size: "small",
    dataSource: "podsStatusReason.find(Failed).value",
    hasTrend: true,
    hasTimeRange: false,
    description: "Pods in Failed phase",
    view: "monitoring/kubernetes/overview.vue",
    position: "stats-row-2",
  },

  // ┌──────────────────────────────────────────────────────────────────────────────
  // │ KUBERNETES - API SERVER (K8S20013-K8S20016) — 4 stat panels
  // └──────────────────────────────────────────────────────────────────────────────
  {
    statPanelId: "K8S20013",
    module: "K8S",
    title: "API Server Health",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "text",
    size: "small",
    dataSource: "healthStatus",
    hasTrend: false,
    hasTimeRange: false,
    description: "API Server health status (Healthy / Down)",
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-stat-health",
  },
  {
    statPanelId: "K8S20014",
    module: "K8S",
    title: "Requests / sec",
    icon: "carbon:api",
    color: "primary",
    unit: "reqps",
    size: "small",
    dataSource: "totalRequestsPerSec",
    hasTrend: true,
    hasTimeRange: true,
    description: "Total API Server request rate",
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-stat-reqps",
  },
  {
    statPanelId: "K8S20015",
    module: "K8S",
    title: "Avg Latency",
    icon: "carbon:timer",
    color: "warning",
    unit: "ms",
    size: "small",
    dataSource: "avgLatencyMs",
    hasTrend: true,
    hasTimeRange: true,
    description: "Average API Server request latency in ms",
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-stat-latency",
  },
  {
    statPanelId: "K8S20016",
    module: "K8S",
    title: "Instances",
    icon: "carbon:server",
    color: "info",
    unit: "count",
    size: "small",
    dataSource: "instanceCount",
    hasTrend: false,
    hasTimeRange: false,
    description: "Number of API Server instances",
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-stat-instances",
  },

  // ┌──────────────────────────────────────────────────────────────────────────────
  // │ KUBERNETES - COREDNS (K8S20017-K8S20020) — 4 stat panels
  // └──────────────────────────────────────────────────────────────────────────────
  {
    statPanelId: "K8S20017",
    module: "K8S",
    title: "CoreDNS Health",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "text",
    size: "small",
    dataSource: "healthStatus",
    hasTrend: false,
    hasTimeRange: false,
    description: "CoreDNS pod health status (Healthy / Down)",
    view: "monitoring/kubernetes/coredns.vue",
    position: "dns-stat-health",
  },
  {
    statPanelId: "K8S20018",
    module: "K8S",
    title: "DNS Requests / sec",
    icon: "carbon:dns-services",
    color: "primary",
    unit: "reqps",
    size: "small",
    dataSource: "totalRequestsPerSec",
    hasTrend: true,
    hasTimeRange: true,
    description: "Total DNS request rate handled by CoreDNS",
    view: "monitoring/kubernetes/coredns.vue",
    position: "dns-stat-reqps",
  },
  {
    statPanelId: "K8S20019",
    module: "K8S",
    title: "Cache Hit Rate",
    icon: "carbon:cached",
    color: "success",
    unit: "percent",
    size: "small",
    dataSource: "cacheHitRatePercent",
    hasTrend: true,
    hasTimeRange: true,
    description: "CoreDNS cache hit percentage",
    view: "monitoring/kubernetes/coredns.vue",
    position: "dns-stat-cache",
  },
  {
    statPanelId: "K8S20020",
    module: "K8S",
    title: "Avg Duration",
    icon: "carbon:timer",
    color: "warning",
    unit: "ms",
    size: "small",
    dataSource: "avgDurationMs",
    hasTrend: true,
    hasTimeRange: true,
    description: "Average DNS request duration in ms",
    view: "monitoring/kubernetes/coredns.vue",
    position: "dns-stat-duration",
  },
];
