/**
 * Stat Panel Registry — AGENT (AGT)
 * 12 stat panel registry definitions
 */

import type { StatPanelDefinition } from "./types";

export const AGT_STAT_PANEL_REGISTRY: StatPanelDefinition[] = [
  // │ AGENT (AGT) — 12 stat panels (8 index + 4 detail)
  // └──────────────────────────────────────────────────────────────────────────────
  {
    statPanelId: "AGT20001",
    module: "AGT",
    title: "Total Agents",
    icon: "carbon:ai-results",
    color: "primary",
    unit: "count",
    size: "small",
    dataSource: "agentStore.agentCount",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total monitoring agents",
    view: "monitoring/agent/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "AGT20002",
    module: "AGT",
    title: "Online",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "count",
    size: "small",
    dataSource: "agentStore.onlineAgents",
    hasTrend: false,
    hasTimeRange: false,
    description: "Online agents",
    view: "monitoring/agent/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "AGT20003",
    module: "AGT",
    title: "Warning",
    icon: "carbon:warning-filled",
    color: "warning",
    unit: "count",
    size: "small",
    dataSource: "agentStore.warningAgents",
    hasTrend: false,
    hasTimeRange: false,
    description: "Agents in warning state",
    view: "monitoring/agent/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "AGT20004",
    module: "AGT",
    title: "Offline",
    icon: "carbon:close-filled",
    color: "error",
    unit: "count",
    size: "small",
    dataSource: "agentStore.offlineAgents",
    hasTrend: false,
    hasTimeRange: false,
    description: "Offline agents",
    view: "monitoring/agent/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "AGT20005",
    module: "AGT",
    title: "Avg CPU Usage",
    icon: "carbon:chip",
    color: "info",
    unit: "%",
    size: "small",
    dataSource: "agentStore.avgCPUUsage",
    hasTrend: true,
    hasTimeRange: true,
    description: "Average CPU usage across agents",
    view: "monitoring/agent/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "AGT20006",
    module: "AGT",
    title: "Avg Memory Usage",
    icon: "ph:memory-fill",
    color: "info",
    unit: "%",
    size: "small",
    dataSource: "agentStore.avgMemoryUsage",
    hasTrend: true,
    hasTimeRange: true,
    description: "Average memory usage across agents",
    view: "monitoring/agent/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "AGT20007",
    module: "AGT",
    title: "Total CPU Cores",
    icon: "carbon:chip",
    color: "primary",
    unit: "cores",
    size: "small",
    dataSource: "agentStore.totalCPU",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total CPU cores across agents",
    view: "monitoring/agent/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "AGT20008",
    module: "AGT",
    title: "Total Memory",
    icon: "ph:memory-fill",
    color: "purple",
    unit: "bytes",
    size: "small",
    dataSource: "formatBytes(agentStore.totalMemory)",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total memory across agents",
    view: "monitoring/agent/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "AGT20009",
    module: "AGT",
    title: "Detail: Status",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "",
    size: "small",
    dataSource: "agent.status",
    hasTrend: false,
    hasTimeRange: false,
    description: "Agent detail status",
    view: "monitoring/agent/AgentDetailsPanel.vue",
    position: "detail-stats",
  },
  {
    statPanelId: "AGT20010",
    module: "AGT",
    title: "Detail: CPU Cores",
    icon: "carbon:chip",
    color: "primary",
    unit: "cores",
    size: "small",
    dataSource: "agent.metrics.cpu.cores",
    hasTrend: false,
    hasTimeRange: false,
    description: "Agent CPU cores",
    view: "monitoring/agent/AgentDetailsPanel.vue",
    position: "detail-stats",
  },
  {
    statPanelId: "AGT20011",
    module: "AGT",
    title: "Detail: Memory",
    icon: "ph:memory-fill",
    color: "info",
    unit: "bytes",
    size: "small",
    dataSource: "formatBytes(agent.metrics.memory.total)",
    hasTrend: false,
    hasTimeRange: false,
    description: "Agent total memory",
    view: "monitoring/agent/AgentDetailsPanel.vue",
    position: "detail-stats",
  },
  {
    statPanelId: "AGT20012",
    module: "AGT",
    title: "Detail: Version",
    icon: "carbon:version",
    color: "purple",
    unit: "",
    size: "small",
    dataSource: "agent.version",
    hasTrend: false,
    hasTimeRange: false,
    description: "Agent version",
    view: "monitoring/agent/AgentDetailsPanel.vue",
    position: "detail-stats",
  },
];
