/**
 * Stat Panel Registry — SERVICE MAP (SVM)
 * 16 stat panel registry definitions
 */

import type { StatPanelDefinition } from "./types";

export const SVM_STAT_PANEL_REGISTRY: StatPanelDefinition[] = [
  // │ SERVICE MAP (SVM) — 16 stat panels (8 index + 8 detail)
  // └──────────────────────────────────────────────────────────────────────────────
  {
    statPanelId: "SVM20001",
    module: "SVM",
    title: "Total Services",
    icon: "carbon:chart-line",
    color: "primary",
    unit: "count",
    size: "small",
    dataSource: "stats.totalServices",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total discovered services",
    view: "monitoring/service-map/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "SVM20002",
    module: "SVM",
    title: "Healthy",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "count",
    size: "small",
    dataSource: "stats.healthyServices",
    hasTrend: false,
    hasTimeRange: false,
    description: "Healthy services",
    view: "monitoring/service-map/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "SVM20003",
    module: "SVM",
    title: "Degraded",
    icon: "carbon:warning-filled",
    color: "warning",
    unit: "count",
    size: "small",
    dataSource: "stats.degradedServices",
    hasTrend: false,
    hasTimeRange: false,
    description: "Degraded services",
    view: "monitoring/service-map/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "SVM20004",
    module: "SVM",
    title: "Unhealthy",
    icon: "carbon:close-filled",
    color: "error",
    unit: "count",
    size: "small",
    dataSource: "stats.unhealthyServices",
    hasTrend: false,
    hasTimeRange: false,
    description: "Unhealthy services",
    view: "monitoring/service-map/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "SVM20005",
    module: "SVM",
    title: "Dependencies",
    icon: "carbon:checkmark-filled",
    color: "info",
    unit: "count",
    size: "small",
    dataSource: "stats.totalDependencies",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total service dependencies",
    view: "monitoring/service-map/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "SVM20006",
    module: "SVM",
    title: "Avg Error Rate",
    icon: "carbon:close-filled",
    color: "error",
    unit: "%",
    size: "small",
    dataSource: "stats.avgErrorRate",
    hasTrend: false,
    hasTimeRange: false,
    description: "Average error rate across services",
    view: "monitoring/service-map/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "SVM20007",
    module: "SVM",
    title: "Active Services",
    icon: "carbon:percentage",
    color: "success",
    unit: "count",
    size: "small",
    dataSource: "services.filter(healthy).length",
    hasTrend: false,
    hasTimeRange: false,
    description: "Currently healthy/active services",
    view: "monitoring/service-map/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "SVM20008",
    module: "SVM",
    title: "Avg Latency",
    icon: "carbon:time",
    color: "info",
    unit: "ms",
    size: "small",
    dataSource: "stats.avgLatency",
    hasTrend: false,
    hasTimeRange: false,
    description: "Average latency across services",
    view: "monitoring/service-map/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "SVM20009",
    module: "SVM",
    title: "Detail: Status",
    icon: "carbon:checkmark-filled",
    color: "success",
    unit: "",
    size: "small",
    dataSource: "service.status",
    hasTrend: false,
    hasTimeRange: false,
    description: "Service detail status",
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
  },
  {
    statPanelId: "SVM20010",
    module: "SVM",
    title: "Detail: Error Rate",
    icon: "carbon:error-filled",
    color: "error",
    unit: "%",
    size: "small",
    dataSource: "service.metrics.errorRate",
    hasTrend: false,
    hasTimeRange: false,
    description: "Service detail error rate",
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
  },
  {
    statPanelId: "SVM20011",
    module: "SVM",
    title: "Detail: Avg Latency",
    icon: "carbon:time",
    color: "primary",
    unit: "ms",
    size: "small",
    dataSource: "service.metrics.avgLatency",
    hasTrend: false,
    hasTimeRange: false,
    description: "Service detail average latency",
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
  },
  {
    statPanelId: "SVM20012",
    module: "SVM",
    title: "Detail: Availability",
    icon: "carbon:meter-alt",
    color: "success",
    unit: "%",
    size: "small",
    dataSource: "service.metrics.availability",
    hasTrend: false,
    hasTimeRange: false,
    description: "Service detail availability",
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
  },
  {
    statPanelId: "SVM20013",
    module: "SVM",
    title: "Detail: Request Rate",
    icon: "carbon:chart-line",
    color: "info",
    unit: "req/min",
    size: "small",
    dataSource: "service.metrics.requestRate",
    hasTrend: false,
    hasTimeRange: false,
    description: "Service detail request rate",
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
  },
  {
    statPanelId: "SVM20014",
    module: "SVM",
    title: "Detail: Success Rate",
    icon: "carbon:checkmark",
    color: "success",
    unit: "%",
    size: "small",
    dataSource: "service.metrics.successRate",
    hasTrend: false,
    hasTimeRange: false,
    description: "Service detail success rate",
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
  },
  {
    statPanelId: "SVM20015",
    module: "SVM",
    title: "Detail: P99 Latency",
    icon: "carbon:data-vis-4",
    color: "warning",
    unit: "ms",
    size: "small",
    dataSource: "service.metrics.p99Latency",
    hasTrend: false,
    hasTimeRange: false,
    description: "Service detail P99 latency",
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
  },
  {
    statPanelId: "SVM20016",
    module: "SVM",
    title: "Detail: Saturation",
    icon: "carbon:dashboard",
    color: "warning",
    unit: "%",
    size: "small",
    dataSource: "service.metrics.saturation",
    hasTrend: false,
    hasTimeRange: false,
    description: "Service detail saturation",
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
  },
];
