/**
 * Stat Panel Registry — PostgreSQL (DBM)
 * 8 stat panel registry definitions
 */

import type { StatPanelDefinition } from "./types";

export const DBM_POSTGRESQL_STAT_PANELS: StatPanelDefinition[] = [
  {
    statPanelId: "DBM20101",
    module: "DBM",
    title: "Active Connections",
    icon: "carbon:connect",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Currently active PostgreSQL connections",
    dataSource: "dbPostgresqlStore.activeConnections",
    view: "/monitoring/db/postgresql",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20102",
    module: "DBM",
    title: "Transactions/sec",
    icon: "carbon:chart-line-data",
    color: "success",
    unit: "txns/s",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Average transactions per second (commits + rollbacks)",
    dataSource: "dbPostgresqlStore.transactionsPerSec",
    view: "/monitoring/db/postgresql",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20103",
    module: "DBM",
    title: "Cache Hit Ratio",
    icon: "carbon:cached",
    color: "success",
    unit: "%",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Buffer cache hit ratio (warning <95%, critical <90%)",
    dataSource: "dbPostgresqlStore.cacheHitRatio",
    view: "/monitoring/db/postgresql",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20104",
    module: "DBM",
    title: "Replication Lag",
    icon: "carbon:time",
    color: "warning",
    unit: "s",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Replication lag in seconds (warning >5s, critical >30s)",
    dataSource: "dbPostgresqlStore.replicationLag",
    view: "/monitoring/db/postgresql",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20105",
    module: "DBM",
    title: "Dead Tuples",
    icon: "carbon:warning",
    color: "error",
    unit: "",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Total dead tuples across all tables",
    dataSource: "dbPostgresqlStore.deadTuples",
    view: "/monitoring/db/postgresql",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20106",
    module: "DBM",
    title: "XID Age %",
    icon: "carbon:progress-bar",
    color: "warning",
    unit: "%",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description:
      "Transaction ID age as percentage of wraparound limit (warning >50%, critical >70%)",
    dataSource: "dbPostgresqlStore.xidAgePercent",
    view: "/monitoring/db/postgresql",
    position: "overview-middle",
  },
  {
    statPanelId: "DBM20107",
    module: "DBM",
    title: "Database Size",
    icon: "carbon:database",
    color: "info",
    unit: "bytes",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Total database size in bytes",
    dataSource: "dbPostgresqlStore.databaseSize",
    view: "/monitoring/db/postgresql",
    position: "overview-bottom",
  },
  {
    statPanelId: "DBM20108",
    module: "DBM",
    title: "Active Locks",
    icon: "carbon:locked",
    color: "error",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Currently active locks across all databases",
    dataSource: "dbPostgresqlStore.activeLocks",
    view: "/monitoring/db/postgresql",
    position: "overview-bottom",
  },
];
