import type { StatPanelDefinition } from "./types";

// Allocated ID range: DBM20801-DBM20808
export const DBM_MONGODB_COMMUNITY_STAT_PANELS: StatPanelDefinition[] = [
  {
    statPanelId: "DBM20801",
    module: "DBM",
    title: "Total Instances",
    icon: "carbon:data-base",
    color: "primary",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total registered MongoDB Community instances",
    dataSource: "dbMongodbCommunityStore.summary.totalInstances",
    view: "/db-monitoring/mongodb-community",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20802",
    module: "DBM",
    title: "Active Connections",
    icon: "carbon:connection-signal",
    color: "info",
    unit: "connections",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Current active connections across all instances",
    dataSource: "db_mongodb_metrics",
    view: "/db-monitoring/mongodb-community",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20803",
    module: "DBM",
    title: "Operations/sec",
    icon: "carbon:operations",
    color: "success",
    unit: "ops/s",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Total operations per second",
    dataSource: "db_mongodb_metrics",
    view: "/db-monitoring/mongodb-community",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20804",
    module: "DBM",
    title: "Cache Hit Ratio",
    icon: "carbon:percentage",
    color: "success",
    unit: "%",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "WiredTiger cache hit ratio",
    dataSource: "db_mongodb_metrics",
    view: "/db-monitoring/mongodb-community",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20805",
    module: "DBM",
    title: "Replication Lag",
    icon: "carbon:time",
    color: "warning",
    unit: "seconds",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Max replication lag across replica sets",
    dataSource: "db_mongodb_metrics",
    view: "/db-monitoring/mongodb-community",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20806",
    module: "DBM",
    title: "Slow Queries",
    icon: "carbon:warning-alt",
    color: "error",
    unit: "",
    size: "default",
    hasTrend: false,
    hasTimeRange: true,
    description: "Slow queries in last hour",
    dataSource: "dbMongodbCommunityStore.slowQueries.length",
    view: "/db-monitoring/mongodb-community",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20807",
    module: "DBM",
    title: "Document Stats",
    icon: "carbon:document",
    color: "info",
    unit: "docs/s",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Documents inserted/updated/deleted per second",
    dataSource: "db_mongodb_metrics",
    view: "/db-monitoring/mongodb-community",
    position: "overview-top",
  },
  {
    statPanelId: "DBM20808",
    module: "DBM",
    title: "Assertion Rate",
    icon: "carbon:warning",
    color: "error",
    unit: "assertions/s",
    size: "default",
    hasTrend: true,
    hasTimeRange: true,
    description: "Assertion rate across all instances",
    dataSource: "db_mongodb_metrics",
    view: "/db-monitoring/mongodb-community",
    position: "overview-top",
  },
];
