import type { StatPanelDefinition } from "./types";

export const DBM_PERCONA_STAT_PANELS: StatPanelDefinition[] = [
  {
    statPanelId: "DBM22001",
    module: "DBM",
    title: "QRT P95 Latency",
    icon: "carbon:timer",
    color: "primary",
    unit: "ms",
    size: "default",
    dataSource: "queryResponseTime.p95",
    hasTrend: true,
    hasTimeRange: true,
    description: "Percona Query Response Time P95 latency",
    view: "monitoring/db-mysql/components/QRTSection.vue",
    position: "overview-percona",
  },
  {
    statPanelId: "DBM22002",
    title: "PXC Cluster Health",
    module: "DBM",
    icon: "carbon:cloud-service-management",
    color: "success",
    unit: "status",
    size: "default",
    dataSource: "pxc.clusterHealth",
    hasTrend: true,
    hasTimeRange: true,
    description: "Percona XtraDB Cluster health status (1=healthy)",
    view: "monitoring/db-mysql/components/PXCSection.vue",
    position: "overview-percona",
  },
  {
    statPanelId: "DBM22003",
    title: "Thread Pool Utilization",
    module: "DBM",
    icon: "carbon:chart-multitype",
    color: "info",
    unit: "ratio",
    size: "default",
    dataSource: "threadPool.utilization",
    hasTrend: true,
    hasTimeRange: true,
    description: "Percona thread pool utilization",
    view: "monitoring/db-mysql/components/PerconaThreadPoolSection.vue",
    position: "overview-percona",
  },
  {
    statPanelId: "DBM22004",
    title: "XtraBackup Changed Pages",
    module: "DBM",
    icon: "carbon:backup",
    color: "warning",
    unit: "count",
    size: "default",
    dataSource: "xtrabackup.changedPages",
    hasTrend: true,
    hasTimeRange: true,
    description: "Percona XtraBackup changed pages count",
    view: "monitoring/db-mysql/components/XtraBackupSection.vue",
    position: "overview-percona",
  },
  {
    statPanelId: "DBM22005",
    title: "Audit Events Written",
    module: "DBM",
    icon: "carbon:security",
    color: "primary",
    unit: "count",
    size: "default",
    dataSource: "audit.eventsWritten",
    hasTrend: true,
    hasTimeRange: true,
    description: "Percona audit plugin events written",
    view: "monitoring/db-mysql/components/AuditSection.vue",
    position: "overview-percona",
  },
  {
    statPanelId: "DBM22006",
    title: "PXC Flow Control Impact",
    module: "DBM",
    icon: "carbon:flow-stream",
    color: "error",
    unit: "ratio",
    size: "default",
    dataSource: "pxc.flowControlImpact",
    hasTrend: true,
    hasTimeRange: true,
    description: "Percona PXC flow control impact (lower is better)",
    view: "monitoring/db-mysql/components/PXCFlowControl.vue",
    position: "overview-percona",
  },
];
