/**
 * Stat Panel Registry — HOME (HOM)
 * 8 stat panel registry definitions
 */

import type { StatPanelDefinition } from "./types";

export const HOM_STAT_PANEL_REGISTRY: StatPanelDefinition[] = [
  // │ HOME (HOM) — 8 stat panels (2 rows × 4)
  // └──────────────────────────────────────────────────────────────────────────────
  // Row 1: Headline counts
  {
    statPanelId: "HOM20001",
    module: "HOM",
    title: "Total Metrics",
    icon: "carbon:chart-line",
    color: "primary",
    unit: "count",
    size: "default",
    dataSource: "metricsStore.metricNames.length",
    hasTrend: false,
    hasTimeRange: false,
    description: "Total number of unique metric names discovered",
    view: "home/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "HOM20002",
    module: "HOM",
    title: "Log Events",
    icon: "carbon:list-numbered",
    color: "success",
    unit: "count",
    size: "default",
    dataSource: "logsStore.totalLogs",
    hasTrend: true,
    hasTimeRange: true,
    description: "Total log events ingested in time range",
    view: "home/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "HOM20003",
    module: "HOM",
    title: "Traces",
    icon: "carbon:flow",
    color: "info",
    unit: "count",
    size: "default",
    dataSource: "tracesStore.traces.length",
    hasTrend: true,
    hasTimeRange: true,
    description: "Total traces collected in time range",
    view: "home/index.vue",
    position: "stats-row-1",
  },
  {
    statPanelId: "HOM20004",
    module: "HOM",
    title: "Active Alerts",
    icon: "carbon:notification",
    color: "error",
    unit: "count",
    size: "default",
    dataSource: "alertsStore.activeAlerts.length",
    hasTrend: false,
    hasTimeRange: false,
    description: "Currently firing alerts (fallback: alertsStore count)",
    view: "home/index.vue",
    position: "stats-row-1",
  },
  // Row 2: Detail metrics
  {
    statPanelId: "HOM20005",
    module: "HOM",
    title: "Services",
    icon: "carbon:application",
    color: "purple",
    unit: "count",
    size: "default",
    dataSource: "tracesStats.serviceCount",
    hasTrend: false,
    hasTimeRange: true,
    description: "Number of distinct services emitting traces",
    view: "home/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "HOM20006",
    module: "HOM",
    title: "Error Rate",
    icon: "carbon:warning-alt",
    color: "error",
    unit: "%",
    size: "default",
    dataSource: "tracesStats.errorCount / tracesStats.totalTraces",
    hasTrend: false,
    hasTimeRange: true,
    description: "Trace error rate percentage in time range",
    view: "home/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "HOM20007",
    module: "HOM",
    title: "Avg Latency",
    icon: "carbon:time",
    color: "warning",
    unit: "ms",
    size: "default",
    dataSource: "tracesStats.avgDurationMs",
    hasTrend: false,
    hasTimeRange: true,
    description: "Average span duration across all services",
    view: "home/index.vue",
    position: "stats-row-2",
  },
  {
    statPanelId: "HOM20008",
    module: "HOM",
    title: "Log Errors",
    icon: "carbon:error",
    color: "error",
    unit: "count",
    size: "default",
    dataSource: "logsStats.errorCount",
    hasTrend: false,
    hasTimeRange: true,
    description: "Total ERROR-severity log events in time range",
    view: "home/index.vue",
    position: "stats-row-2",
  },
];
