/**
 * TFO-Agent Alert Rules
 * TelemetryFlow Agent monitoring for host metrics, health, and status
 */

import type { AlertRuleTemplate, AlertRuleCategory } from "../types";
import {
  RuleCategory,
  AlertSourceType,
  DefaultDurations,
  DefaultIntervals,
  DefaultThresholds,
} from "../types";

export const TFOAgentCategory: AlertRuleCategory = {
  metadata: {
    id: RuleCategory.TFO_AGENT,
    name: "TFO-Agent",
    description: "TelemetryFlow Agent monitoring for host metrics and health",
    icon: "mdi:robot",
    exporter: "tfo-agent",
    documentationUrl: "https://docs.telemetryflow.id/agent",
    ruleCount: 25,
  },
  groups: [
    {
      id: "health",
      name: "Health",
      description: "Agent health and availability",
      rules: [],
    },
    {
      id: "cpu",
      name: "CPU",
      description: "CPU metrics from agent",
      rules: [],
    },
    {
      id: "memory",
      name: "Memory",
      description: "Memory metrics from agent",
      rules: [],
    },
    {
      id: "disk",
      name: "Disk",
      description: "Disk metrics from agent",
      rules: [],
    },
    {
      id: "network",
      name: "Network",
      description: "Network metrics from agent",
      rules: [],
    },
    {
      id: "system",
      name: "System",
      description: "System-level metrics",
      rules: [],
    },
  ],
};

export const TFOAgentRules: AlertRuleTemplate[] = [
  // Health
  {
    id: "tfo-agent-offline",
    name: "TFO-Agent Offline",
    description: "TFO-Agent has not sent heartbeat",
    category: RuleCategory.TFO_AGENT,
    subcategory: "health",
    severity: "critical",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_last_heartbeat_seconds",
        aggregation: "last",
        operator: "gt",
        threshold: DefaultThresholds.AGENT_HEARTBEAT_MISSING_CRITICAL_SEC,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "availability" },
    annotations: { summary: "TFO-Agent offline ({{ $labels.agent_name }})" },
    promql: "time() - tfo_agent_last_heartbeat_timestamp_seconds > 300",
    enabled: true,
    source: {
      name: "TelemetryFlow",
      url: "https://docs.telemetryflow.id/agent/alerts",
    },
  },
  {
    id: "tfo-agent-unhealthy",
    name: "TFO-Agent Unhealthy",
    description: "TFO-Agent is reporting unhealthy status",
    category: RuleCategory.TFO_AGENT,
    subcategory: "health",
    severity: "warning",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_status",
        aggregation: "last",
        operator: "neq",
        threshold: 1,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "health" },
    annotations: { summary: "TFO-Agent unhealthy ({{ $labels.agent_name }})" },
    promql: "tfo_agent_status != 1",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-high-response-time",
    name: "TFO-Agent High Response Time",
    description: "TFO-Agent response time is high",
    category: RuleCategory.TFO_AGENT,
    subcategory: "health",
    severity: "warning",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_response_time_ms",
        aggregation: "avg",
        operator: "gt",
        threshold: DefaultThresholds.AGENT_RESPONSE_TIME_WARNING_MS,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "latency" },
    annotations: { summary: "TFO-Agent high response time" },
    promql: "avg_over_time(tfo_agent_response_time_ms[5m]) > 500",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-version-mismatch",
    name: "TFO-Agent Version Mismatch",
    description: "TFO-Agent version differs from expected",
    category: RuleCategory.TFO_AGENT,
    subcategory: "health",
    severity: "info",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_version_info",
        aggregation: "count",
        operator: "gt",
        threshold: 1,
        duration: DefaultDurations.LONG,
      },
    ],
    evaluationInterval: DefaultIntervals.SLOW,
    forDuration: DefaultDurations.LONG,
    labels: { component: "tfo-agent", type: "version" },
    annotations: { summary: "Multiple TFO-Agent versions detected" },
    promql: "count(count by (version) (tfo_agent_version_info)) > 1",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-stale",
    name: "TFO-Agent Stale Metrics",
    description: "TFO-Agent metrics are stale",
    category: RuleCategory.TFO_AGENT,
    subcategory: "health",
    severity: "warning",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_last_heartbeat_seconds",
        aggregation: "last",
        operator: "gt",
        threshold: DefaultThresholds.AGENT_HEARTBEAT_MISSING_WARNING_SEC,
        duration: DefaultDurations.SHORT,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.SHORT,
    labels: { component: "tfo-agent", type: "staleness" },
    annotations: { summary: "TFO-Agent stale metrics" },
    promql: "time() - tfo_agent_last_heartbeat_timestamp_seconds > 60",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },

  // CPU
  {
    id: "tfo-agent-cpu-high",
    name: "Host CPU Usage High",
    description: "Host CPU usage is high (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "cpu",
    severity: "warning",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_cpu_usage_percent",
        aggregation: "avg",
        operator: "gt",
        threshold: DefaultThresholds.CPU_USAGE_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "cpu" },
    annotations: { summary: "High CPU usage on {{ $labels.hostname }}" },
    promql: "avg_over_time(tfo_agent_cpu_usage_percent[5m]) > 80",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-cpu-critical",
    name: "Host CPU Usage Critical",
    description: "Host CPU usage is critically high (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "cpu",
    severity: "critical",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_cpu_usage_percent",
        aggregation: "avg",
        operator: "gt",
        threshold: DefaultThresholds.CPU_USAGE_CRITICAL,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "cpu" },
    annotations: { summary: "Critical CPU usage on {{ $labels.hostname }}" },
    promql: "avg_over_time(tfo_agent_cpu_usage_percent[5m]) > 90",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-load-high",
    name: "Host Load Average High",
    description: "Host load average is high (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "cpu",
    severity: "warning",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_load_avg_5m",
        aggregation: "avg",
        operator: "gt",
        threshold: DefaultThresholds.CPU_LOAD_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "load" },
    annotations: { summary: "High load average on {{ $labels.hostname }}" },
    promql: "tfo_agent_load_avg_5m / tfo_agent_cpu_cores > 0.8",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },

  // Memory
  {
    id: "tfo-agent-memory-high",
    name: "Host Memory Usage High",
    description: "Host memory usage is high (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "memory",
    severity: "warning",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_memory_used_percent",
        aggregation: "avg",
        operator: "gt",
        threshold: DefaultThresholds.MEMORY_USAGE_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "memory" },
    annotations: { summary: "High memory usage on {{ $labels.hostname }}" },
    promql: "tfo_agent_memory_used_percent > 80",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-memory-critical",
    name: "Host Memory Usage Critical",
    description: "Host memory usage is critically high (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "memory",
    severity: "critical",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_memory_used_percent",
        aggregation: "avg",
        operator: "gt",
        threshold: DefaultThresholds.MEMORY_USAGE_CRITICAL,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "memory" },
    annotations: { summary: "Critical memory usage on {{ $labels.hostname }}" },
    promql: "tfo_agent_memory_used_percent > 90",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-swap-high",
    name: "Host Swap Usage High",
    description: "Host swap usage is high (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "memory",
    severity: "warning",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_swap_used_percent",
        aggregation: "avg",
        operator: "gt",
        threshold: DefaultThresholds.SWAP_USAGE_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "swap" },
    annotations: { summary: "High swap usage on {{ $labels.hostname }}" },
    promql: "tfo_agent_swap_used_percent > 50",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-oom-kill",
    name: "Host OOM Kill Detected",
    description: "OOM kill detected on host (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "memory",
    severity: "critical",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_oom_kills_total",
        aggregation: "rate",
        operator: "gt",
        threshold: 0,
        duration: DefaultDurations.SHORT,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.SHORT,
    labels: { component: "tfo-agent", type: "oom" },
    annotations: { summary: "OOM kill on {{ $labels.hostname }}" },
    promql: "increase(tfo_agent_oom_kills_total[5m]) > 0",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },

  // Disk
  {
    id: "tfo-agent-disk-high",
    name: "Host Disk Usage High",
    description: "Host disk usage is high (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "disk",
    severity: "warning",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_disk_used_percent",
        aggregation: "max",
        operator: "gt",
        threshold: DefaultThresholds.DISK_USAGE_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "disk" },
    annotations: { summary: "High disk usage on {{ $labels.hostname }}" },
    promql: "max by (hostname, path) (tfo_agent_disk_used_percent) > 80",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-disk-critical",
    name: "Host Disk Usage Critical",
    description: "Host disk usage is critically high (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "disk",
    severity: "critical",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_disk_used_percent",
        aggregation: "max",
        operator: "gt",
        threshold: DefaultThresholds.DISK_USAGE_CRITICAL,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "disk" },
    annotations: { summary: "Critical disk usage on {{ $labels.hostname }}" },
    promql: "max by (hostname, path) (tfo_agent_disk_used_percent) > 90",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-disk-io-high",
    name: "Host Disk I/O High",
    description: "Host disk I/O utilization is high (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "disk",
    severity: "warning",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_disk_io_util_percent",
        aggregation: "avg",
        operator: "gt",
        threshold: DefaultThresholds.DISK_IO_UTIL_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "disk-io" },
    annotations: { summary: "High disk I/O on {{ $labels.hostname }}" },
    promql: "tfo_agent_disk_io_util_percent > 80",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-disk-latency-high",
    name: "Host Disk Latency High",
    description: "Host disk latency is high (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "disk",
    severity: "warning",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_disk_latency_read_ms",
        aggregation: "avg",
        operator: "gt",
        threshold: 50,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "disk-latency" },
    annotations: { summary: "High disk latency on {{ $labels.hostname }}" },
    promql: "tfo_agent_disk_latency_read_ms > 50",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },

  // Network
  {
    id: "tfo-agent-network-errors",
    name: "Host Network Errors",
    description: "Host network interface has errors (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "network",
    severity: "warning",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_network_errors_total",
        aggregation: "rate",
        operator: "gt",
        threshold: DefaultThresholds.NETWORK_ERROR_RATE_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "network" },
    annotations: { summary: "Network errors on {{ $labels.hostname }}" },
    promql: "rate(tfo_agent_network_errors_total[5m]) > 1",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-network-drops",
    name: "Host Network Packet Drops",
    description: "Host network interface has packet drops (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "network",
    severity: "warning",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_network_drops_total",
        aggregation: "rate",
        operator: "gt",
        threshold: DefaultThresholds.NETWORK_PACKET_DROP_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "network" },
    annotations: { summary: "Network drops on {{ $labels.hostname }}" },
    promql: "rate(tfo_agent_network_drops_total[5m]) > 1",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-tcp-retransmits",
    name: "Host TCP Retransmits High",
    description: "Host TCP retransmit rate is high (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "network",
    severity: "warning",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_tcp_retransmits_total",
        aggregation: "rate",
        operator: "gt",
        threshold: 10,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "tcp" },
    annotations: { summary: "High TCP retransmits on {{ $labels.hostname }}" },
    promql: "rate(tfo_agent_tcp_retransmits_total[5m]) > 10",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-tcp-timewait-high",
    name: "Host TCP TIME_WAIT High",
    description: "Host TCP TIME_WAIT connections are high (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "network",
    severity: "info",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_tcp_connections",
        aggregation: "last",
        operator: "gt",
        threshold: 10000,
        duration: DefaultDurations.MEDIUM,
        labels: { state: "time_wait" },
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "tcp" },
    annotations: { summary: "High TIME_WAIT on {{ $labels.hostname }}" },
    promql: 'tfo_agent_tcp_connections{state="time_wait"} > 10000',
    enabled: true,
    source: { name: "TelemetryFlow" },
  },

  // System
  {
    id: "tfo-agent-uptime-reboot",
    name: "Host Rebooted",
    description: "Host has rebooted recently (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "system",
    severity: "info",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_uptime_seconds",
        aggregation: "last",
        operator: "lt",
        threshold: 600,
        duration: DefaultDurations.SHORT,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.SHORT,
    labels: { component: "tfo-agent", type: "uptime" },
    annotations: { summary: "Host rebooted: {{ $labels.hostname }}" },
    promql: "tfo_agent_uptime_seconds < 600",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-process-count-high",
    name: "Host Process Count High",
    description: "Host process count is high (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "system",
    severity: "warning",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_process_count",
        aggregation: "last",
        operator: "gt",
        threshold: 500,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "processes" },
    annotations: { summary: "High process count on {{ $labels.hostname }}" },
    promql: "tfo_agent_process_count > 500",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-agent-page-faults-high",
    name: "Host Page Faults High",
    description: "Host major page fault rate is high (via TFO-Agent)",
    category: RuleCategory.TFO_AGENT,
    subcategory: "system",
    severity: "warning",
    sourceType: AlertSourceType.TFO_AGENT,
    conditions: [
      {
        metric: "tfo_agent_page_faults_major_total",
        aggregation: "rate",
        operator: "gt",
        threshold: 100,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-agent", type: "pagefaults" },
    annotations: { summary: "High page faults on {{ $labels.hostname }}" },
    promql: "rate(tfo_agent_page_faults_major_total[5m]) > 100",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
];

// Update category with rules
TFOAgentCategory.groups.forEach((group) => {
  group.rules = TFOAgentRules.filter((rule) => rule.subcategory === group.id);
});
