/**
 * TFO-Collector Alert Rules
 * TelemetryFlow Collector (OTEL Collector) monitoring
 * Based on OpenTelemetry Collector internal metrics
 */

import type { AlertRuleTemplate, AlertRuleCategory } from "../types";
import {
  RuleCategory,
  AlertSourceType,
  DefaultDurations,
  DefaultIntervals,
  DefaultThresholds,
} from "../types";

export const TFOCollectorCategory: AlertRuleCategory = {
  metadata: {
    id: RuleCategory.TFO_COLLECTOR,
    name: "TFO-Collector",
    description:
      "TelemetryFlow Collector (OTEL) monitoring for traces, metrics, and logs pipelines",
    icon: "mdi:pipe",
    exporter: "otelcol-contrib",
    documentationUrl: "https://docs.telemetryflow.id/collector",
    ruleCount: 35,
  },
  groups: [
    {
      id: "health",
      name: "Health",
      description: "Collector health and availability",
      rules: [],
    },
    {
      id: "receiver",
      name: "Receivers",
      description: "Receiver pipeline metrics",
      rules: [],
    },
    {
      id: "processor",
      name: "Processors",
      description: "Processor pipeline metrics",
      rules: [],
    },
    {
      id: "exporter",
      name: "Exporters",
      description: "Exporter pipeline metrics",
      rules: [],
    },
    {
      id: "traces",
      name: "Traces",
      description: "Trace-specific pipeline metrics",
      rules: [],
    },
    {
      id: "metrics",
      name: "Metrics",
      description: "Metrics-specific pipeline metrics",
      rules: [],
    },
    {
      id: "logs",
      name: "Logs",
      description: "Logs-specific pipeline metrics",
      rules: [],
    },
    {
      id: "queue",
      name: "Queues",
      description: "Queue and buffer metrics",
      rules: [],
    },
  ],
};

export const TFOCollectorRules: AlertRuleTemplate[] = [
  // Health
  {
    id: "tfo-collector-down",
    name: "TFO-Collector Down",
    description: "TFO-Collector is down",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "health",
    severity: "critical",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_process_uptime",
        aggregation: "last",
        operator: "eq",
        threshold: 0,
        duration: DefaultDurations.SHORT,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.SHORT,
    labels: { component: "tfo-collector", type: "availability" },
    annotations: { summary: "TFO-Collector down" },
    promql: 'up{job="otelcol"} == 0',
    enabled: true,
    source: {
      name: "TelemetryFlow",
      url: "https://docs.telemetryflow.id/collector/alerts",
    },
  },
  {
    id: "tfo-collector-high-cpu",
    name: "TFO-Collector High CPU",
    description: "TFO-Collector CPU usage is high",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "health",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_process_cpu_seconds_total",
        aggregation: "rate",
        operator: "gt",
        threshold: 0.8,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", type: "cpu" },
    annotations: { summary: "TFO-Collector high CPU" },
    promql: "rate(otelcol_process_cpu_seconds_total[5m]) > 0.8",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-high-memory",
    name: "TFO-Collector High Memory",
    description: "TFO-Collector memory usage is high",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "health",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_process_memory_rss",
        aggregation: "last",
        operator: "gt",
        threshold: 1073741824,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", type: "memory" },
    annotations: { summary: "TFO-Collector high memory" },
    promql: "otelcol_process_memory_rss > 1073741824",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-restart",
    name: "TFO-Collector Restarted",
    description: "TFO-Collector has restarted",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "health",
    severity: "info",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_process_uptime",
        aggregation: "last",
        operator: "lt",
        threshold: 300,
        duration: DefaultDurations.SHORT,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.SHORT,
    labels: { component: "tfo-collector", type: "restart" },
    annotations: { summary: "TFO-Collector restarted" },
    promql: "otelcol_process_uptime < 300",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-rpc-errors",
    name: "TFO-Collector RPC Errors",
    description: "Collector experiencing RPC errors",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "health",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_rpc_server_request_count",
        aggregation: "rate",
        operator: "gt",
        threshold: 10,
        duration: DefaultDurations.MEDIUM,
        labels: { rpc_grpc_status_code: "ERROR" },
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", type: "rpc" },
    annotations: { summary: "High RPC error rate" },
    promql:
      'sum(rate(otelcol_rpc_server_request_count{rpc_grpc_status_code!="OK"}[5m])) > 10',
    enabled: true,
    source: { name: "TelemetryFlow" },
  },

  // Receiver
  {
    id: "tfo-collector-receiver-refused",
    name: "TFO-Collector Receiver Refusing Data",
    description: "Receiver is refusing incoming telemetry data",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "receiver",
    severity: "critical",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_receiver_refused_spans",
        aggregation: "rate",
        operator: "gt",
        threshold: 0,
        duration: DefaultDurations.SHORT,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.SHORT,
    labels: { component: "tfo-collector", type: "receiver" },
    annotations: { summary: "Receiver refusing data" },
    promql: "rate(otelcol_receiver_refused_spans[5m]) > 0",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-receiver-no-data",
    name: "TFO-Collector Receiver No Data",
    description: "Receiver is not receiving any data",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "receiver",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_receiver_accepted_spans",
        aggregation: "rate",
        operator: "eq",
        threshold: 0,
        duration: DefaultDurations.LONG,
      },
    ],
    evaluationInterval: DefaultIntervals.SLOW,
    forDuration: DefaultDurations.LONG,
    labels: { component: "tfo-collector", type: "receiver" },
    annotations: { summary: "Receiver not receiving data" },
    promql: "rate(otelcol_receiver_accepted_spans[15m]) == 0",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-receiver-errors",
    name: "TFO-Collector Receiver Errors",
    description: "Receiver is encountering errors",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "receiver",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_receiver_errors_total",
        aggregation: "rate",
        operator: "gt",
        threshold: 1,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", type: "receiver" },
    annotations: { summary: "Receiver errors" },
    promql: "rate(otelcol_receiver_errors_total[5m]) > 1",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-scrape-errors",
    name: "TFO-Collector Scrape Errors",
    description: "Prometheus receiver scrape errors",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "receiver",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_receiver_prometheus_scrape_errors_total",
        aggregation: "rate",
        operator: "gt",
        threshold: 1,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", type: "scrape" },
    annotations: { summary: "Prometheus scrape errors" },
    promql: "rate(otelcol_receiver_prometheus_scrape_errors_total[5m]) > 1",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },

  // Processor
  {
    id: "tfo-collector-processor-dropped",
    name: "TFO-Collector Processor Dropping Data",
    description: "Processor is dropping telemetry data",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "processor",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_processor_dropped_spans",
        aggregation: "rate",
        operator: "gt",
        threshold: DefaultThresholds.COLLECTOR_DROPPED_SPANS_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", type: "processor" },
    annotations: { summary: "Processor dropping data" },
    promql: "rate(otelcol_processor_dropped_spans[5m]) > 10",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-processor-dropped-critical",
    name: "TFO-Collector Processor Dropping Data Critical",
    description: "Processor is dropping significant telemetry data",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "processor",
    severity: "critical",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_processor_dropped_spans",
        aggregation: "rate",
        operator: "gt",
        threshold: DefaultThresholds.COLLECTOR_DROPPED_SPANS_CRITICAL,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", type: "processor" },
    annotations: { summary: "Processor dropping data critical" },
    promql: "rate(otelcol_processor_dropped_spans[5m]) > 100",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-batch-timeout",
    name: "TFO-Collector Batch Timeout",
    description: "Batch processor is timing out",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "processor",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_processor_batch_timeout_trigger_send",
        aggregation: "rate",
        operator: "gt",
        threshold: 10,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", type: "batch" },
    annotations: { summary: "Batch processor timeout" },
    promql: "rate(otelcol_processor_batch_timeout_trigger_send[5m]) > 10",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },

  // Exporter
  {
    id: "tfo-collector-exporter-failed",
    name: "TFO-Collector Exporter Failed",
    description: "Exporter is failing to send data",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "exporter",
    severity: "critical",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_exporter_send_failed_spans",
        aggregation: "rate",
        operator: "gt",
        threshold: 0,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", type: "exporter" },
    annotations: { summary: "Exporter failing" },
    promql: "rate(otelcol_exporter_send_failed_spans[5m]) > 0",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-exporter-queue-full",
    name: "TFO-Collector Exporter Queue Full",
    description: "Exporter queue is nearly full",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "exporter",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_exporter_queue_size",
        aggregation: "last",
        operator: "gt",
        threshold: DefaultThresholds.COLLECTOR_QUEUE_SIZE_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", type: "exporter" },
    annotations: { summary: "Exporter queue full" },
    promql:
      "otelcol_exporter_queue_size / otelcol_exporter_queue_capacity * 100 > 80",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-exporter-retry",
    name: "TFO-Collector Exporter Retrying",
    description: "Exporter is retrying to send data",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "exporter",
    severity: "info",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_exporter_retry_send_spans",
        aggregation: "rate",
        operator: "gt",
        threshold: 1,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", type: "exporter" },
    annotations: { summary: "Exporter retrying" },
    promql: "rate(otelcol_exporter_retry_send_spans[5m]) > 1",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-exporter-no-output",
    name: "TFO-Collector Exporter No Output",
    description: "Exporter is not sending any data",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "exporter",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_exporter_sent_spans",
        aggregation: "rate",
        operator: "eq",
        threshold: 0,
        duration: DefaultDurations.LONG,
      },
    ],
    evaluationInterval: DefaultIntervals.SLOW,
    forDuration: DefaultDurations.LONG,
    labels: { component: "tfo-collector", type: "exporter" },
    annotations: { summary: "Exporter not sending data" },
    promql: "rate(otelcol_exporter_sent_spans[15m]) == 0",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },

  // Traces
  {
    id: "tfo-collector-traces-dropped",
    name: "TFO-Collector Traces Dropped",
    description: "Traces are being dropped",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "traces",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_processor_dropped_spans",
        aggregation: "rate",
        operator: "gt",
        threshold: DefaultThresholds.COLLECTOR_DROPPED_SPANS_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", signal: "traces" },
    annotations: { summary: "Traces being dropped" },
    promql: "sum(rate(otelcol_processor_dropped_spans[5m])) > 10",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-traces-high-latency",
    name: "TFO-Collector Traces High Latency",
    description: "Trace processing latency is high",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "traces",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_span_processing_duration_seconds",
        aggregation: "p99",
        operator: "gt",
        threshold: 1,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", signal: "traces" },
    annotations: { summary: "Trace processing high latency" },
    promql:
      "histogram_quantile(0.99, rate(otelcol_span_processing_duration_seconds_bucket[5m])) > 1",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-traces-export-failure",
    name: "TFO-Collector Traces Export Failure",
    description: "Trace export is failing",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "traces",
    severity: "critical",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_exporter_send_failed_spans",
        aggregation: "rate",
        operator: "gt",
        threshold: DefaultThresholds.COLLECTOR_EXPORT_FAILURE_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", signal: "traces" },
    annotations: { summary: "Trace export failing" },
    promql: "sum(rate(otelcol_exporter_send_failed_spans[5m])) > 5",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },

  // Metrics
  {
    id: "tfo-collector-metrics-dropped",
    name: "TFO-Collector Metrics Dropped",
    description: "Metrics are being dropped",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "metrics",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_processor_dropped_metric_points",
        aggregation: "rate",
        operator: "gt",
        threshold: DefaultThresholds.COLLECTOR_DROPPED_METRICS_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", signal: "metrics" },
    annotations: { summary: "Metrics being dropped" },
    promql: "sum(rate(otelcol_processor_dropped_metric_points[5m])) > 10",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-metrics-refused",
    name: "TFO-Collector Metrics Refused",
    description: "Metrics receiver is refusing data",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "metrics",
    severity: "critical",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_receiver_refused_metric_points",
        aggregation: "rate",
        operator: "gt",
        threshold: 0,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", signal: "metrics" },
    annotations: { summary: "Metrics receiver refusing data" },
    promql: "sum(rate(otelcol_receiver_refused_metric_points[5m])) > 0",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-metrics-export-failure",
    name: "TFO-Collector Metrics Export Failure",
    description: "Metrics export is failing",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "metrics",
    severity: "critical",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_exporter_send_failed_metric_points",
        aggregation: "rate",
        operator: "gt",
        threshold: DefaultThresholds.COLLECTOR_EXPORT_FAILURE_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", signal: "metrics" },
    annotations: { summary: "Metrics export failing" },
    promql: "sum(rate(otelcol_exporter_send_failed_metric_points[5m])) > 5",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },

  // Logs
  {
    id: "tfo-collector-logs-dropped",
    name: "TFO-Collector Logs Dropped",
    description: "Logs are being dropped",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "logs",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_processor_dropped_log_records",
        aggregation: "rate",
        operator: "gt",
        threshold: DefaultThresholds.COLLECTOR_DROPPED_LOGS_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", signal: "logs" },
    annotations: { summary: "Logs being dropped" },
    promql: "sum(rate(otelcol_processor_dropped_log_records[5m])) > 10",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-logs-refused",
    name: "TFO-Collector Logs Refused",
    description: "Logs receiver is refusing data",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "logs",
    severity: "critical",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_receiver_refused_log_records",
        aggregation: "rate",
        operator: "gt",
        threshold: 0,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", signal: "logs" },
    annotations: { summary: "Logs receiver refusing data" },
    promql: "sum(rate(otelcol_receiver_refused_log_records[5m])) > 0",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-logs-export-failure",
    name: "TFO-Collector Logs Export Failure",
    description: "Logs export is failing",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "logs",
    severity: "critical",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_exporter_send_failed_log_records",
        aggregation: "rate",
        operator: "gt",
        threshold: DefaultThresholds.COLLECTOR_EXPORT_FAILURE_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", signal: "logs" },
    annotations: { summary: "Logs export failing" },
    promql: "sum(rate(otelcol_exporter_send_failed_log_records[5m])) > 5",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },

  // Queue
  {
    id: "tfo-collector-queue-high",
    name: "TFO-Collector Queue High",
    description: "Collector queue is filling up",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "queue",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_exporter_queue_size",
        aggregation: "avg",
        operator: "gt",
        threshold: DefaultThresholds.COLLECTOR_QUEUE_SIZE_WARNING,
        duration: DefaultDurations.MEDIUM,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", type: "queue" },
    annotations: { summary: "Queue filling up" },
    promql:
      "otelcol_exporter_queue_size / otelcol_exporter_queue_capacity * 100 > 80",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-queue-critical",
    name: "TFO-Collector Queue Critical",
    description: "Collector queue is almost full",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "queue",
    severity: "critical",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_exporter_queue_size",
        aggregation: "avg",
        operator: "gt",
        threshold: DefaultThresholds.COLLECTOR_QUEUE_SIZE_CRITICAL,
        duration: DefaultDurations.SHORT,
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.SHORT,
    labels: { component: "tfo-collector", type: "queue" },
    annotations: { summary: "Queue critical" },
    promql:
      "otelcol_exporter_queue_size / otelcol_exporter_queue_capacity * 100 > 95",
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
  {
    id: "tfo-collector-memory-limiter-active",
    name: "TFO-Collector Memory Limiter Active",
    description: "Memory limiter is actively throttling",
    category: RuleCategory.TFO_COLLECTOR,
    subcategory: "queue",
    severity: "warning",
    sourceType: AlertSourceType.TFO_COLLECTOR,
    conditions: [
      {
        metric: "otelcol_processor_memory_limiter_decision",
        aggregation: "rate",
        operator: "gt",
        threshold: 1,
        duration: DefaultDurations.MEDIUM,
        labels: { decision: "drop" },
      },
    ],
    evaluationInterval: DefaultIntervals.NORMAL,
    forDuration: DefaultDurations.MEDIUM,
    labels: { component: "tfo-collector", type: "memory-limiter" },
    annotations: { summary: "Memory limiter dropping data" },
    promql:
      'rate(otelcol_processor_memory_limiter_decision{decision="drop"}[5m]) > 1',
    enabled: true,
    source: { name: "TelemetryFlow" },
  },
];

// Update category with rules
TFOCollectorCategory.groups.forEach((group) => {
  group.rules = TFOCollectorRules.filter(
    (rule) => rule.subcategory === group.id,
  );
});
