import type { GraphDefinition } from './types';

export const DBM_COCKROACHDB_GRAPHS: GraphDefinition[] = [
  {
    graphId: 'DBM10601',
    module: 'DBM',
    title: 'SQL Query Rate',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'queries/s',
    description: 'SQL query execution rate over time',
    dataSource: 'db_cockroachdb_metrics',
    view: 'db-monitoring/cockroachdb/CockroachDBOverviewView.vue',
    position: 'crdb-query-rate',
    defaultQueries: [
      { dialect: 'tfql', expression: 'rate(crdb.sql.query_count[1m])', legend: 'Queries/s' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10602',
    module: 'DBM',
    title: 'Transaction Rate',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'txn/s',
    description: 'Transaction begin and commit rate over time',
    dataSource: 'db_cockroachdb_metrics',
    view: 'db-monitoring/cockroachdb/CockroachDBOverviewView.vue',
    position: 'crdb-txn-rate',
    defaultQueries: [
      { dialect: 'tfql', expression: 'rate(crdb.sql_txn_begin_count[1m])', legend: 'Begins' },
      { dialect: 'tfql', expression: 'rate(crdb.sql_txn_commit_count[1m])', legend: 'Commits' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10603',
    module: 'DBM',
    title: 'Latency Percentiles',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'ms',
    description: 'SQL query latency at p50, p90, and p99',
    dataSource: 'db_cockroachdb_metrics',
    view: 'db-monitoring/cockroachdb/CockroachDBOverviewView.vue',
    position: 'crdb-latency',
    defaultQueries: [
      { dialect: 'tfql', expression: 'crdb.sql.query.latency_p50', legend: 'p50' },
      { dialect: 'tfql', expression: 'crdb.sql.query.latency_p90', legend: 'p90' },
      { dialect: 'tfql', expression: 'crdb.sql.query.latency_p99', legend: 'p99' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10604',
    module: 'DBM',
    title: 'Storage Capacity',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'bytes',
    description: 'Cluster storage capacity, available, and used',
    dataSource: 'db_cockroachdb_metrics',
    view: 'db-monitoring/cockroachdb/CockroachDBStorageView.vue',
    position: 'crdb-storage',
    defaultQueries: [
      { dialect: 'tfql', expression: 'crdb.capacity', legend: 'Total Capacity' },
      { dialect: 'tfql', expression: 'crdb.capacity_available', legend: 'Available' },
      { dialect: 'tfql', expression: 'crdb.capacity_used', legend: 'Used' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10605',
    module: 'DBM',
    title: 'Range Count by Node',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'ranges',
    description: 'Number of ranges per node over time',
    dataSource: 'db_cockroachdb_metrics',
    view: 'db-monitoring/cockroachdb/CockroachDBOverviewView.vue',
    position: 'crdb-ranges',
    defaultQueries: [
      { dialect: 'tfql', expression: 'crdb.ranges', legend: 'Ranges' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10606',
    module: 'DBM',
    title: 'Leaseholder Distribution',
    component: 'RegistryGraphPanel',
    chartType: 'bar',
    signalType: 'metrics',
    unit: 'leases',
    description: 'Leaseholder count per node',
    dataSource: 'db_cockroachdb_metrics',
    view: 'db-monitoring/cockroachdb/CockroachDBClusterView.vue',
    position: 'crdb-leaseholders',
    defaultQueries: [
      { dialect: 'tfql', expression: 'crdb.leases_epoch', legend: 'Leases' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10607',
    module: 'DBM',
    title: 'Raft Leader Distribution',
    component: 'RegistryGraphPanel',
    chartType: 'bar',
    signalType: 'metrics',
    unit: 'leaders',
    description: 'Raft leader count per node',
    dataSource: 'db_cockroachdb_metrics',
    view: 'db-monitoring/cockroachdb/CockroachDBClusterView.vue',
    position: 'crdb-raft-leaders',
    defaultQueries: [
      { dialect: 'tfql', expression: 'crdb.raft_leader', legend: 'Raft Leaders' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10608',
    module: 'DBM',
    title: 'Rebalancing Rate',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'ops/s',
    description: 'Rebalancing operations rate over time',
    dataSource: 'db_cockroachdb_metrics',
    view: 'db-monitoring/cockroachdb/CockroachDBClusterView.vue',
    position: 'crdb-rebalance',
    defaultQueries: [
      { dialect: 'tfql', expression: 'rate(crdb.rebalancing.queriespersecond[1m])', legend: 'Rebalance Ops/s' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10609',
    module: 'DBM',
    title: 'Heartbeat Latency',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'ms',
    description: 'Node liveness heartbeat latency',
    dataSource: 'db_cockroachdb_metrics',
    view: 'db-monitoring/cockroachdb/CockroachDBClusterView.vue',
    position: 'crdb-heartbeat',
    defaultQueries: [
      { dialect: 'tfql', expression: 'crdb.liveness.heartbeatlatency', legend: 'Heartbeat Latency' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10610',
    module: 'DBM',
    title: 'Changefeed Throughput',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'rows/s',
    description: 'Changefeed emitted messages rate over time',
    dataSource: 'db_cockroachdb_metrics',
    view: 'db-monitoring/cockroachdb/CockroachDBChangefeedsView.vue',
    position: 'crdb-changefeed-throughput',
    defaultQueries: [
      { dialect: 'tfql', expression: 'rate(crdb.changefeed.emitted_messages[1m])', legend: 'Emitted Rows/s' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10611',
    module: 'DBM',
    title: 'Changefeed Latency',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'ms',
    description: 'Changefeed lag over time',
    dataSource: 'db_cockroachdb_metrics',
    view: 'db-monitoring/cockroachdb/CockroachDBChangefeedsView.vue',
    position: 'crdb-changefeed-latency',
    defaultQueries: [
      { dialect: 'tfql', expression: 'crdb.changefeed.lag', legend: 'Changefeed Lag' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10612',
    module: 'DBM',
    title: 'GC Pause',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'ns',
    description: 'Garbage collection pause duration over time',
    dataSource: 'db_cockroachdb_metrics',
    view: 'db-monitoring/cockroachdb/CockroachDBOverviewView.vue',
    position: 'crdb-gc-pause',
    defaultQueries: [
      { dialect: 'tfql', expression: 'crdb.gc.pause_ns', legend: 'GC Pause' },
    ],
    toggleable: false,
  },
];
