/**
 * Graph Registry — SERVICE MAP (SVM)
 * 21 graph definitions
 *
 * Auto-extracted from graph-registry.ts
 */

import type { GraphDefinition } from "./types";

export const SVM_GRAPHS: GraphDefinition[] = [
  // │ SERVICE MAP (SVM) - 20 graphs
  // └──────────────────────────────────────────────────────────────────────────────
  {
    graphId: "SVM10001",
    module: "SVM",
    title: "Total Services",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "count",
    description: "Total discovered services",
    dataSource: "stats.totalServices",
    defaultQueries: [
      { dialect: "tfql", expression: "FETCH services AGGREGATE count(*)", legendFormat: "Total Services", seriesKey: "__name__" },
    ],
    view: "monitoring/service-map/index.vue",
    position: "stats-row-1",
    toggleable: false,
  },
  {
    graphId: "SVM10002",
    module: "SVM",
    title: "Healthy",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "count",
    description: "Healthy services",
    dataSource: "stats.healthyServices",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "FETCH services WHERE status = 'healthy' AGGREGATE count(*)",
        legendFormat: "Healthy",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/index.vue",
    position: "stats-row-1",
    toggleable: false,
  },
  {
    graphId: "SVM10003",
    module: "SVM",
    title: "Degraded",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "count",
    description: "Degraded services",
    dataSource: "stats.degradedServices",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "FETCH services WHERE status = 'degraded' AGGREGATE count(*)",
        legendFormat: "Degraded",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/index.vue",
    position: "stats-row-1",
    toggleable: false,
  },
  {
    graphId: "SVM10004",
    module: "SVM",
    title: "Unhealthy",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "count",
    description: "Unhealthy services",
    dataSource: "stats.unhealthyServices",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "FETCH services WHERE status = 'unhealthy' AGGREGATE count(*)",
        legendFormat: "Unhealthy",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/index.vue",
    position: "stats-row-1",
    toggleable: false,
  },
  {
    graphId: "SVM10005",
    module: "SVM",
    title: "Dependencies",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "count",
    description: "Total service dependencies",
    dataSource: "stats.totalDependencies",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "FETCH service_dependencies AGGREGATE count(*)",
        legendFormat: "Dependencies",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/index.vue",
    position: "stats-row-2",
    toggleable: false,
  },
  {
    graphId: "SVM10006",
    module: "SVM",
    title: "Avg Error Rate",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "%",
    description: "Average error rate across services",
    dataSource: "stats.avgErrorRate",
    defaultQueries: [
      {
        dialect: "promql",
        expression: 'service_map_error_rate{service_id="{{service_id}}"}',
        legendFormat: "Avg Error Rate",
        seriesKey: "__name__",
      },
      {
        dialect: "tfql",
        expression:
          "FETCH service_map_metrics WHERE service_id = '{{service_id}}' AGGREGATE avg(error_rate) INTERVAL {{interval}}",
        legendFormat: "Avg Error Rate",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/index.vue",
    position: "stats-row-2",
    toggleable: false,
  },
  {
    graphId: "SVM10007",
    module: "SVM",
    title: "Active Services",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "count",
    description: "Currently healthy/active services",
    dataSource: "services.filter(healthy).length",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "FETCH services WHERE status IN ('healthy', 'active') AGGREGATE count(*)",
        legendFormat: "Active Services",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/index.vue",
    position: "stats-row-2",
    toggleable: false,
  },
  {
    graphId: "SVM10008",
    module: "SVM",
    title: "Avg Latency",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "ms",
    description: "Average latency across services",
    dataSource: "stats.avgLatency",
    defaultQueries: [
      {
        dialect: "promql",
        expression: 'service_map_avg_latency{service_id="{{service_id}}"}',
        legendFormat: "Avg Latency",
        seriesKey: "__name__",
      },
      {
        dialect: "tfql",
        expression:
          "FETCH service_map_metrics WHERE service_id = '{{service_id}}' AGGREGATE avg(avg_latency) INTERVAL {{interval}}",
        legendFormat: "Avg Latency",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/index.vue",
    position: "stats-row-2",
    toggleable: false,
  },
  {
    graphId: "SVM10009",
    module: "SVM",
    title: "Service Topology",
    component: "ServiceNodeGraph",
    chartType: "topology",
    signalType: "infrastructure",
    unit: "",
    description:
      "Interactive service dependency topology (canvas, layered/force/grid layouts)",
    dataSource: "graphData.nodes / graphData.edges",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "FETCH services AGGREGATE count(*) GROUP BY status",
        legend: "Service Topology",
        legendFormat: "{{status}}",
        seriesKey: "status",
      },
    ],
    view: "monitoring/service-map/ServiceNodeGraph.vue",
    position: "main-graph",
    toggleable: false,
  },
  {
    graphId: "SVM10010",
    module: "SVM",
    title: "Status",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "",
    description: "Service detail status",
    dataSource: "service.status",
    defaultQueries: [
      {
        dialect: "promql",
        expression: 'service_map_health_score{service_id="{{service_id}}"}',
        legendFormat: "Status",
        seriesKey: "__name__",
      },
      {
        dialect: "tfql",
        expression:
          "FETCH service_map_metrics WHERE service_id = '{{service_id}}' AGGREGATE avg(health_score) INTERVAL {{interval}}",
        legendFormat: "Status",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
    toggleable: false,
  },
  {
    graphId: "SVM10011",
    module: "SVM",
    title: "Error Rate",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "%",
    description: "Service detail error rate",
    dataSource: "service.metrics.errorRate",
    defaultQueries: [
      {
        dialect: "promql",
        expression: 'service_map_error_rate{service_id="{{service_id}}"}',
        legendFormat: "Error Rate",
        seriesKey: "__name__",
      },
      {
        dialect: "tfql",
        expression:
          "FETCH service_map_metrics WHERE service_id = '{{service_id}}' AGGREGATE avg(error_rate) INTERVAL {{interval}}",
        legendFormat: "Error Rate",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
    toggleable: false,
  },
  {
    graphId: "SVM10012",
    module: "SVM",
    title: "Avg Latency",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "ms",
    description: "Service detail average latency",
    dataSource: "service.metrics.avgLatency",
    defaultQueries: [
      {
        dialect: "promql",
        expression: 'service_map_avg_latency{service_id="{{service_id}}"}',
        legendFormat: "Avg Latency",
        seriesKey: "__name__",
      },
      {
        dialect: "tfql",
        expression:
          "FETCH service_map_metrics WHERE service_id = '{{service_id}}' AGGREGATE avg(avg_latency) INTERVAL {{interval}}",
        legendFormat: "Avg Latency",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
    toggleable: false,
  },
  {
    graphId: "SVM10013",
    module: "SVM",
    title: "Availability",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "%",
    description: "Service detail availability",
    dataSource: "service.metrics.availability",
    defaultQueries: [
      {
        dialect: "promql",
        expression: 'service_map_uptime{service_id="{{service_id}}"}',
        legendFormat: "Availability",
        seriesKey: "__name__",
      },
      {
        dialect: "tfql",
        expression:
          "FETCH service_map_metrics WHERE service_id = '{{service_id}}' AGGREGATE avg(uptime) INTERVAL {{interval}}",
        legendFormat: "Availability",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
    toggleable: false,
  },
  {
    graphId: "SVM10014",
    module: "SVM",
    title: "Request Rate",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "req/min",
    description: "Service detail request rate",
    dataSource: "service.metrics.requestRate",
    defaultQueries: [
      {
        dialect: "promql",
        expression: 'service_map_request_rate{service_id="{{service_id}}"}',
        legendFormat: "Request Rate",
        seriesKey: "__name__",
      },
      {
        dialect: "tfql",
        expression:
          "FETCH service_map_metrics WHERE service_id = '{{service_id}}' AGGREGATE avg(request_rate) INTERVAL {{interval}}",
        legendFormat: "Request Rate",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
    toggleable: false,
  },
  {
    graphId: "SVM10015",
    module: "SVM",
    title: "Success Rate",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "%",
    description: "Service detail success rate",
    dataSource: "service.metrics.successRate",
    defaultQueries: [
      {
        dialect: "promql",
        expression: 'service_map_health_score{service_id="{{service_id}}"}',
        legendFormat: "Success Rate",
        seriesKey: "__name__",
      },
      {
        dialect: "tfql",
        expression:
          "FETCH service_map_metrics WHERE service_id = '{{service_id}}' AGGREGATE avg(health_score) INTERVAL {{interval}}",
        legendFormat: "Success Rate",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
    toggleable: false,
  },
  {
    graphId: "SVM10016",
    module: "SVM",
    title: "P99 Latency",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "ms",
    description: "Service detail P99 latency",
    dataSource: "service.metrics.p99Latency",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          'histogram_quantile(0.99, sum(rate(trace_duration_ms_bucket{service_name="{{service_name}}"}[$__rate_interval])) by (le))',
        legendFormat: "{{le}}",
        seriesKey: "le",
      },
      {
        dialect: "tfql",
        expression:
          "FETCH traces WHERE service_name = '{{service_name}}' AGGREGATE p99(duration_ns) / 1000000 INTERVAL {{interval}}",
        legendFormat: "p99",
        seriesKey: "percentile",
      },
    ],
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
    toggleable: false,
  },
  {
    graphId: "SVM10017",
    module: "SVM",
    title: "Saturation",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "%",
    description: "Service detail saturation",
    dataSource: "service.metrics.saturation",
    defaultQueries: [
      {
        dialect: "promql",
        expression: 'network_node_cpu_usage{node_id="{{node_id}}"}',
        legendFormat: "Saturation",
        seriesKey: "__name__",
      },
      {
        dialect: "tfql",
        expression:
          "FETCH network_map_traffic WHERE node_id = '{{node_id}}' AGGREGATE avg(cpu_usage) INTERVAL {{interval}}",
        legendFormat: "Saturation",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-stats",
    toggleable: false,
  },
  {
    graphId: "SVM10018",
    module: "SVM",
    title: "Avg Latency Trend",
    component: "MiniChartCard",
    chartType: "timeseries",
    signalType: "infrastructure",
    unit: "ms",
    description: "Service average latency trend mini chart",
    dataSource:
      'generateChartSeries("Avg Latency", service.metrics.avgLatency)',
    defaultQueries: [
      {
        dialect: "promql",
        expression: 'service_map_avg_latency{service_id="{{service_id}}"}',
        legendFormat: "Avg Latency Trend",
        seriesKey: "__name__",
      },
      {
        dialect: "tfql",
        expression:
          "FETCH service_map_metrics WHERE service_id = '{{service_id}}' AGGREGATE avg(avg_latency) INTERVAL {{interval}}",
        legendFormat: "Avg Latency Trend",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-trends",
    toggleable: true,
  },
  {
    graphId: "SVM10019",
    module: "SVM",
    title: "Request Rate Trend",
    component: "MiniChartCard",
    chartType: "timeseries",
    signalType: "infrastructure",
    unit: "req/min",
    description: "Service request rate trend mini chart",
    dataSource: 'generateChartSeries("Req/min", service.metrics.requestRate)',
    defaultQueries: [
      {
        dialect: "promql",
        expression: 'service_map_request_rate{service_id="{{service_id}}"}',
        legendFormat: "Request Rate Trend",
        seriesKey: "__name__",
      },
      {
        dialect: "tfql",
        expression:
          "FETCH service_map_metrics WHERE service_id = '{{service_id}}' AGGREGATE avg(request_rate) INTERVAL {{interval}}",
        legendFormat: "Request Rate Trend",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-trends",
    toggleable: true,
  },
  {
    graphId: "SVM10020",
    module: "SVM",
    title: "Resource Utilization",
    component: "Custom",
    chartType: "progress",
    signalType: "infrastructure",
    unit: "%",
    description: "CPU/Memory/Disk/Network progress bars",
    dataSource: "resourceUtil",
    defaultQueries: [
      {
        dialect: "promql",
        expression: 'network_node_cpu_usage{node_id="{{node_id}}"}',
        legendFormat: "Resource Utilization",
        seriesKey: "__name__",
      },
      {
        dialect: "tfql",
        expression:
          "FETCH network_map_traffic WHERE node_id = '{{node_id}}' AGGREGATE avg(cpu_usage) INTERVAL {{interval}}",
        legendFormat: "Resource Utilization",
        seriesKey: "__name__",
      },
      {
        dialect: "promql",
        expression: 'network_node_memory_usage{node_id="{{node_id}}"}',
        legendFormat: "value",
        seriesKey: "__name__",
      },
      {
        dialect: "tfql",
        expression:
          "FETCH network_map_traffic WHERE node_id = '{{node_id}}' AGGREGATE avg(memory_usage) INTERVAL {{interval}}",
        legendFormat: "value",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/ServiceDetailPanel.vue",
    position: "detail-resources",
    toggleable: false,
  },

  {
    graphId: "SVM10021",
    module: "SVM",
    title: "Infra Probe Latency",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "infrastructure",
    unit: "ms",
    description:
      "Probe round-trip latency per infrastructure service over time (from ClickHouse service_map_infra_health MVs)",
    dataSource: "service_map_infra_health_1h",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "FETCH service_map_infra_health WHERE service_key = '{{service_key}}' AGGREGATE avg(avg_latency_ms) INTERVAL {{interval}}",
        legend: "Probe Latency (ms)",
        legendFormat: "Infra Probe Latency",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/service-map/index.vue",
    position: "infra-health-chart",
    toggleable: true,
  },

];
