import type { GraphDefinition } from './types';

// Allocated ID range: DBM11101-DBM11112
export const DBM_TIMESCALEDB_GRAPHS: GraphDefinition[] = [
  {
    graphId: "DBM11101",
    module: "DBM",
    title: "Active Connections Over Time",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "connections",
    description: "Active database connections over time",
    dataSource: "db_timescaledb_metrics",
    view: "db-monitoring/timescaledb/TimescaledbInstanceDetailView.vue",
    position: "tsdb-connections",
    defaultQueries: [
      { dialect: "tfql", expression: "db.timescaledb.connections.active", legend: "Active Connections" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM11102",
    module: "DBM",
    title: "Hypertable Storage Growth",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "bytes",
    description: "Total hypertable storage usage over time",
    dataSource: "db_timescaledb_metrics",
    view: "db-monitoring/timescaledb/TimescaledbInstanceDetailView.vue",
    position: "tsdb-storage",
    defaultQueries: [
      { dialect: "tfql", expression: "db.timescaledb.hypertable.total_size_bytes", legend: "Total Size" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM11103",
    module: "DBM",
    title: "Query Throughput",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "queries/s",
    description: "Query throughput (reads and writes) over time",
    dataSource: "db_timescaledb_metrics",
    view: "db-monitoring/timescaledb/TimescaledbInstanceDetailView.vue",
    position: "tsdb-throughput",
    defaultQueries: [
      { dialect: "tfql", expression: "rate(db.timescaledb.queries.select[1m])", legend: "SELECTs" },
      { dialect: "tfql", expression: "rate(db.timescaledb.queries.insert[1m])", legend: "INSERTs" },
      { dialect: "tfql", expression: "rate(db.timescaledb.queries.update[1m])", legend: "UPDATEs" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM11104",
    module: "DBM",
    title: "Compression Ratio Over Time",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "ratio",
    description: "Compression ratio trend across hypertables",
    dataSource: "db_timescaledb_metrics",
    view: "db-monitoring/timescaledb/TimescaledbInstanceDetailView.vue",
    position: "tsdb-compression-ratio",
    defaultQueries: [
      { dialect: "tfql", expression: "db.timescaledb.compression.ratio", legend: "Compression Ratio" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM11105",
    module: "DBM",
    title: "Background Job Duration",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "ms",
    description: "Background job execution duration over time",
    dataSource: "db_timescaledb_metrics",
    view: "db-monitoring/timescaledb/TimescaledbInstanceDetailView.vue",
    position: "tsdb-job-duration",
    defaultQueries: [
      { dialect: "tfql", expression: "db.timescaledb.job.duration_ms", legend: "Duration" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM11106",
    module: "DBM",
    title: "Chunk Distribution",
    component: "RegistryGraphPanel",
    chartType: "bar",
    signalType: "metrics",
    unit: "chunks",
    description: "Compressed vs uncompressed chunks per hypertable",
    dataSource: "db_timescaledb_metrics",
    view: "db-monitoring/timescaledb/TimescaledbInstanceDetailView.vue",
    position: "tsdb-chunk-distribution",
    defaultQueries: [
      { dialect: "tfql", expression: "db.timescaledb.hypertable.uncompressed_chunk_count", legend: "Uncompressed" },
      { dialect: "tfql", expression: "db.timescaledb.hypertable.compressed_chunk_count", legend: "Compressed" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM11107",
    module: "DBM",
    title: "Transaction Rate",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "txns/s",
    description: "Transaction commit and rollback rate",
    dataSource: "db_timescaledb_metrics",
    view: "db-monitoring/timescaledb/TimescaledbInstanceDetailView.vue",
    position: "tsdb-txn-rate",
    defaultQueries: [
      { dialect: "tfql", expression: "rate(db.timescaledb.transactions.commits[1m])", legend: "Commits" },
      { dialect: "tfql", expression: "rate(db.timescaledb.transactions.rollbacks[1m])", legend: "Rollbacks" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM11108",
    module: "DBM",
    title: "Cache Hit Ratio",
    component: "RegistryGraphPanel",
    chartType: "gauge",
    signalType: "metrics",
    unit: "%",
    description: "Buffer cache hit ratio",
    dataSource: "db_timescaledb_metrics",
    view: "db-monitoring/timescaledb/TimescaledbInstanceDetailView.vue",
    position: "tsdb-cache-hit",
    defaultQueries: [
      { dialect: "tfql", expression: "db.timescaledb.cache.hit_ratio", legend: "Hit Ratio" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM11109",
    module: "DBM",
    title: "Replication Lag (Distributed)",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "bytes",
    description: "Replication lag across data nodes",
    dataSource: "db_timescaledb_metrics",
    view: "db-monitoring/timescaledb/TimescaledbInstanceDetailView.vue",
    position: "tsdb-repl-lag",
    defaultQueries: [
      { dialect: "tfql", expression: "db.timescaledb.data_node.replication_lag_bytes", legend: "Lag" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM11110",
    module: "DBM",
    title: "Disk I/O",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "bytes/s",
    description: "Disk read and write throughput",
    dataSource: "db_timescaledb_metrics",
    view: "db-monitoring/timescaledb/TimescaledbInstanceDetailView.vue",
    position: "tsdb-disk-io",
    defaultQueries: [
      { dialect: "tfql", expression: "rate(db.timescaledb.disk.read_bytes[1m])", legend: "Read" },
      { dialect: "tfql", expression: "rate(db.timescaledb.disk.write_bytes[1m])", legend: "Write" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM11111",
    module: "DBM",
    title: "Continuous Aggregate Refresh Rate",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "refreshes/h",
    description: "Continuous aggregate materialization refresh rate",
    dataSource: "db_timescaledb_metrics",
    view: "db-monitoring/timescaledb/TimescaledbInstanceDetailView.vue",
    position: "tsdb-cagg-refresh",
    defaultQueries: [
      { dialect: "tfql", expression: "db.timescaledb.cagg.refresh_count", legend: "Refreshes" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM11112",
    module: "DBM",
    title: "Query Duration Percentiles",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "ms",
    description: "p50, p95, p99 query latency",
    dataSource: "db_timescaledb_metrics",
    view: "db-monitoring/timescaledb/TimescaledbInstanceDetailView.vue",
    position: "tsdb-query-duration",
    defaultQueries: [
      { dialect: "tfql", expression: "db.timescaledb.queries.duration_ms_p50", legend: "p50" },
      { dialect: "tfql", expression: "db.timescaledb.queries.duration_ms_p95", legend: "p95" },
      { dialect: "tfql", expression: "db.timescaledb.queries.duration_ms_p99", legend: "p99" },
    ],
    toggleable: false,
  },
];
