import type { GraphDefinition } from "./types";

export const QRY_GRAPHS: GraphDefinition[] = [
  {
    graphId: "QRY10001",
    module: "QRY",
    title: "Query Latency Distribution",
    component: "RegistryGraphPanel",
    chartType: "bar",
    signalType: "metrics",
    unit: "ms",
    description: "Query execution time distribution across all engines",
    dataSource: "db_mysql_queries",
    view: "db-monitoring/query-analytics/QANView.vue",
    position: "qan-latency-dist",
    defaultQueries: [
      { dialect: "tfql", expression: "FETCH queries AGGREGATE avg(avg_time_us) BY schema_name", legend: "Avg Latency by Schema" },
    ],
    toggleable: false,
  },
  {
    graphId: "QRY10002",
    module: "QRY",
    title: "Queries Per Second",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "qps",
    description: "Total query throughput over time",
    dataSource: "db_mysql_queries",
    view: "db-monitoring/query-analytics/QANView.vue",
    position: "qan-qps",
    defaultQueries: [
      { dialect: "tfql", expression: "FETCH queries AGGREGATE sum(calls) BY engine", legend: "QPS by Engine" },
    ],
    toggleable: false,
  },
  {
    graphId: "QRY10003",
    module: "QRY",
    title: "Top Queries by Load",
    component: "RegistryGraphPanel",
    chartType: "bar",
    signalType: "metrics",
    unit: "ms",
    description: "Top 20 queries by total execution time",
    dataSource: "db_mysql_queries",
    view: "db-monitoring/query-analytics/QANView.vue",
    position: "qan-top-load",
    defaultQueries: [
      { dialect: "tfql", expression: "FETCH queries ORDER BY total_time_us DESC LIMIT 20", legend: "Top Queries" },
    ],
    toggleable: false,
  },
  {
    graphId: "QRY10004",
    module: "QRY",
    title: "Slow Query Trend",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "queries",
    description: "Count of slow queries (>100ms) over time",
    dataSource: "db_mysql_queries",
    view: "db-monitoring/query-analytics/QANView.vue",
    position: "qan-slow-trend",
    defaultQueries: [
      { dialect: "tfql", expression: "FETCH queries WHERE avg_time_us > 100000 AGGREGATE count() INTERVAL 5m", legend: "Slow Queries" },
    ],
    toggleable: true,
  },
  {
    graphId: "QRY10005",
    module: "QRY",
    title: "Query Load by Engine",
    component: "RegistryGraphPanel",
    chartType: "bar",
    signalType: "metrics",
    unit: "%",
    description: "Percentage of total query load per engine",
    dataSource: "db_mysql_queries",
    view: "db-monitoring/query-analytics/QANView.vue",
    position: "qan-engine-load",
    defaultQueries: [
      { dialect: "tfql", expression: "FETCH queries AGGREGATE sum(total_time_us) BY engine", legend: "Load by Engine" },
    ],
    toggleable: false,
  },
];
