import type { GraphDefinition } from "./types";

export const DBM_CLICKHOUSE_GRAPHS: GraphDefinition[] = [
  {
    graphId: "DBM10201",
    module: "DBM",
    title: "Queries Over Time",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "queries",
    description: "Active queries over time",
    dataSource: "db_clickhouse_metrics",
    view: "db-monitoring/clickhouse/ClickHouseOverviewView.vue",
    position: "ch-queries",
    defaultQueries: [
      { dialect: "tfql", expression: "db.clickhouse.system.Query", legend: "Active Queries" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10202",
    module: "DBM",
    title: "Memory Usage Over Time",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "bytes",
    description: "Memory tracking over time",
    dataSource: "db_clickhouse_metrics",
    view: "db-monitoring/clickhouse/ClickHouseOverviewView.vue",
    position: "ch-memory",
    defaultQueries: [
      { dialect: "tfql", expression: "db.clickhouse.system.MemoryTracking", legend: "Memory" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10203",
    module: "DBM",
    title: "Insert/Select Throughput",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "rows/s",
    description: "Row throughput for inserts and selects",
    dataSource: "db_clickhouse_metrics",
    view: "db-monitoring/clickhouse/ClickHouseOverviewView.vue",
    position: "ch-throughput",
    defaultQueries: [
      { dialect: "tfql", expression: "rate(db.clickhouse.events.InsertedRows[1m])", legend: "Inserts" },
      { dialect: "tfql", expression: "rate(db.clickhouse.events.SelectedRows[1m])", legend: "Selects" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10204",
    module: "DBM",
    title: "Merge Activity",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "merges",
    description: "Concurrent background merges over time",
    dataSource: "db_clickhouse_metrics",
    view: "db-monitoring/clickhouse/ClickHouseTablesView.vue",
    position: "ch-merges",
    defaultQueries: [
      { dialect: "tfql", expression: "db.clickhouse.system.Merge", legend: "Merges" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10205",
    module: "DBM",
    title: "Replication Lag",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "seconds",
    description: "Absolute delay per replica",
    dataSource: "db_clickhouse_metrics",
    view: "db-monitoring/clickhouse/ClickHouseReplicationView.vue",
    position: "ch-repl-lag",
    defaultQueries: [
      { dialect: "tfql", expression: "db.clickhouse.replica.absolute_delay", legend: "Lag" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10206",
    module: "DBM",
    title: "Disk I/O",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "bytes/s",
    description: "Disk read and write throughput",
    dataSource: "db_clickhouse_metrics",
    view: "db-monitoring/clickhouse/ClickHouseStorageView.vue",
    position: "ch-disk-io",
    defaultQueries: [
      { dialect: "tfql", expression: "rate(db.clickhouse.events.NetworkReceiveBytes[1m])", legend: "Read" },
      { dialect: "tfql", expression: "rate(db.clickhouse.events.NetworkSendBytes[1m])", legend: "Write" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10207",
    module: "DBM",
    title: "Network Traffic",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "bytes/s",
    description: "Network bytes sent and received",
    dataSource: "db_clickhouse_metrics",
    view: "db-monitoring/clickhouse/ClickHouseOverviewView.vue",
    position: "ch-network",
    defaultQueries: [
      { dialect: "tfql", expression: "rate(db.clickhouse.events.NetworkReceiveBytes[1m])", legend: "Inbound" },
      { dialect: "tfql", expression: "rate(db.clickhouse.events.NetworkSendBytes[1m])", legend: "Outbound" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10208",
    module: "DBM",
    title: "Query Duration Distribution",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "ms",
    description: "p50, p95, p99 query latency",
    dataSource: "db_clickhouse_metrics",
    view: "db-monitoring/clickhouse/ClickHouseQueryAnalyticsView.vue",
    position: "ch-query-duration",
    defaultQueries: [
      { dialect: "tfql", expression: "db.clickhouse.query_log.duration_ms_p50", legend: "p50" },
      { dialect: "tfql", expression: "db.clickhouse.query_log.duration_ms_p95", legend: "p95" },
      { dialect: "tfql", expression: "db.clickhouse.query_log.duration_ms_p99", legend: "p99" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10209",
    module: "DBM",
    title: "Parts Count Over Time",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "parts",
    description: "Active parts per table over time",
    dataSource: "db_clickhouse_metrics",
    view: "db-monitoring/clickhouse/ClickHouseTablesView.vue",
    position: "ch-parts",
    defaultQueries: [
      { dialect: "tfql", expression: "db.clickhouse.mergetree.parts_count", legend: "Parts" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10210",
    module: "DBM",
    title: "ZooKeeper Operations",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "ops/s",
    description: "ZK transactions, watches, requests",
    dataSource: "db_clickhouse_metrics",
    view: "db-monitoring/clickhouse/ClickHouseReplicationView.vue",
    position: "ch-zk-ops",
    defaultQueries: [
      { dialect: "tfql", expression: "rate(db.clickhouse.events.ZooKeeperTransactions[1m])", legend: "Transactions" },
      { dialect: "tfql", expression: "rate(db.clickhouse.events.ZooKeeperWatch[1m])", legend: "Watches" },
      { dialect: "tfql", expression: "rate(db.clickhouse.events.ZooKeeperRequest[1m])", legend: "Requests" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10211",
    module: "DBM",
    title: "Query Kind Distribution",
    component: "RegistryGraphPanel",
    chartType: "dynamic",
    signalType: "metrics",
    unit: "",
    description: "Distribution of query types",
    dataSource: "db_clickhouse_metrics",
    view: "db-monitoring/clickhouse/ClickHouseQueryAnalyticsView.vue",
    position: "ch-query-kinds",
    defaultQueries: [
      { dialect: "tfql", expression: "db.clickhouse.query_log.count", legend: "Queries" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10212",
    module: "DBM",
    title: "Compression Ratio by Table",
    component: "RegistryGraphPanel",
    chartType: "bar",
    signalType: "metrics",
    unit: "ratio",
    description: "Compression ratio per table",
    dataSource: "db_clickhouse_metrics",
    view: "db-monitoring/clickhouse/ClickHouseStorageView.vue",
    position: "ch-compression",
    defaultQueries: [
      { dialect: "tfql", expression: "db.clickhouse.columns.compressed_bytes", legend: "Compressed" },
      { dialect: "tfql", expression: "db.clickhouse.columns.uncompressed_bytes", legend: "Uncompressed" },
    ],
    toggleable: false,
  },
];
