import type { GraphDefinition } from "./types";

export const DBM_MSSQL_GRAPHS: GraphDefinition[] = [
  {
    graphId: "DBM10901",
    module: "DBM",
    title: "Batch Requests/sec",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "/s",
    description: "SQL Server batch requests per second",
    dataSource: "db_mssql_metrics",
    view: "db-monitoring/mssql",
    position: "mssql-batch-req",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mssql.batch_requests_per_sec", legend: "Batch Req/s" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10902",
    module: "DBM",
    title: "Page Life Expectancy",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "s",
    description: "Buffer pool page life expectancy",
    dataSource: "db_mssql_metrics",
    view: "db-monitoring/mssql",
    position: "mssql-ple",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mssql.page_life_expectancy", legend: "PLE (s)" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10903",
    module: "DBM",
    title: "Buffer Cache Hit Ratio",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "%",
    description: "Buffer cache hit ratio percentage",
    dataSource: "db_mssql_metrics",
    view: "db-monitoring/mssql",
    position: "mssql-buffer-hit",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mssql.buffer_cache_hit_ratio", legend: "Hit %" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10904",
    module: "DBM",
    title: "User Connections",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "",
    description: "Active user connections over time",
    dataSource: "db_mssql_metrics",
    view: "db-monitoring/mssql",
    position: "mssql-connections",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mssql.user_connections", legend: "Connections" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10905",
    module: "DBM",
    title: "Wait Stats by Category",
    component: "RegistryGraphPanel",
    chartType: "donut",
    signalType: "metrics",
    unit: "ms",
    description: "Wait time distribution by category (CPU, IO, Lock, etc.)",
    dataSource: "db_mssql_waits",
    view: "db-monitoring/mssql",
    position: "mssql-waits-donut",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mssql.waits.category.*.total_ms", legend: "{{ category }}" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10906",
    module: "DBM",
    title: "Top Wait Types",
    component: "RegistryGraphPanel",
    chartType: "bar",
    signalType: "metrics",
    unit: "ms",
    description: "Top wait types by total wait time",
    dataSource: "db_mssql_waits",
    view: "db-monitoring/mssql",
    position: "mssql-top-waits",
    defaultQueries: [
      { dialect: "tfql", expression: "top(10, db.mssql.waits.*.wait_time_ms)", legend: "{{ wait_type }}" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10907",
    module: "DBM",
    title: "Wait Stats Trend",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "ms",
    description: "Wait time trend by category over time",
    dataSource: "db_mssql_waits",
    view: "db-monitoring/mssql",
    position: "mssql-waits-trend",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mssql.waits.category.IO.total_ms", legend: "IO" },
      { dialect: "tfql", expression: "db.mssql.waits.category.CPU.total_ms", legend: "CPU" },
      { dialect: "tfql", expression: "db.mssql.waits.category.Lock.total_ms", legend: "Lock" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10908",
    module: "DBM",
    title: "File I/O Stall Times",
    component: "RegistryGraphPanel",
    chartType: "bar",
    signalType: "metrics",
    unit: "ms",
    description: "Average read/write stall times per database file",
    dataSource: "db_mssql_metrics",
    view: "db-monitoring/mssql",
    position: "mssql-file-io",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mssql.file_io.read_stall_avg_ms", legend: "Read Stall" },
      { dialect: "tfql", expression: "db.mssql.file_io.write_stall_avg_ms", legend: "Write Stall" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10909",
    module: "DBM",
    title: "TempDB Space Usage",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "MB",
    description: "TempDB space breakdown: user objects, internal objects, version store",
    dataSource: "db_mssql_metrics",
    view: "db-monitoring/mssql",
    position: "mssql-tempdb",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mssql.tempdb.user_objects_mb", legend: "User Objects" },
      { dialect: "tfql", expression: "db.mssql.tempdb.internal_objects_mb", legend: "Internal" },
      { dialect: "tfql", expression: "db.mssql.tempdb.version_store_mb", legend: "Version Store" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10910",
    module: "DBM",
    title: "AG Log Send Queue",
    component: "RegistryGraphPanel",
    chartType: "gauge",
    signalType: "metrics",
    unit: "KB",
    description: "AlwaysOn availability group log send queue size",
    dataSource: "db_mssql_metrics",
    view: "db-monitoring/mssql",
    position: "mssql-ag-log-queue",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mssql.ag.log_send_queue_size", legend: "Log Send Queue" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10911",
    module: "DBM",
    title: "AG Redo Queue",
    component: "RegistryGraphPanel",
    chartType: "gauge",
    signalType: "metrics",
    unit: "KB",
    description: "AlwaysOn availability group redo queue size",
    dataSource: "db_mssql_metrics",
    view: "db-monitoring/mssql",
    position: "mssql-ag-redo-queue",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mssql.ag.redo_queue_size", legend: "Redo Queue" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10912",
    module: "DBM",
    title: "Query Performance Trend",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "us",
    description: "Top query CPU time trend",
    dataSource: "db_mssql_queries",
    view: "db-monitoring/mssql",
    position: "mssql-query-trend",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mssql.queries.top.cpu_time", legend: "CPU Time" },
    ],
    toggleable: false,
  },
];
