/**
 * Graph Registry — AWS DynamoDB (DBM)
 * 12 graph definitions (DBM10301–DBM10312)
 */

import type { GraphDefinition } from './types';

export const DBM_AWS_DYNAMODB_GRAPHS: GraphDefinition[] = [
  {
    graphId: 'DBM10301',
    module: 'DBM',
    title: 'Consumed Read Capacity',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'RCU',
    description: 'DynamoDB consumed read capacity units over time',
    dataSource: 'dbDynamoDBStore.consumedReadCapacity',
    view: 'monitoring/db-dynamodb/overview.vue',
    position: 'dynamodb-consumed-read-capacity',
    defaultQueries: [
      { dialect: 'tfql', expression: 'db.dynamodb.consumed_read_capacity_units', legend: 'Consumed RCU' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10302',
    module: 'DBM',
    title: 'Consumed Write Capacity',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'WCU',
    description: 'DynamoDB consumed write capacity units over time',
    dataSource: 'dbDynamoDBStore.consumedWriteCapacity',
    view: 'monitoring/db-dynamodb/overview.vue',
    position: 'dynamodb-consumed-write-capacity',
    defaultQueries: [
      { dialect: 'tfql', expression: 'db.dynamodb.consumed_write_capacity_units', legend: 'Consumed WCU' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10303',
    module: 'DBM',
    title: 'Read Throttle Events',
    component: 'RegistryGraphPanel',
    chartType: 'bar',
    signalType: 'metrics',
    unit: 'events',
    description: 'DynamoDB read throttle events by table (provisioned capacity exceeded)',
    dataSource: 'dbDynamoDBStore.readThrottleEvents',
    view: 'monitoring/db-dynamodb/overview.vue',
    position: 'dynamodb-read-throttle-events',
    defaultQueries: [
      { dialect: 'tfql', expression: 'rate(db.dynamodb.read_throttle_events[5m])', legend: 'Read Throttles' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10304',
    module: 'DBM',
    title: 'Write Throttle Events',
    component: 'RegistryGraphPanel',
    chartType: 'bar',
    signalType: 'metrics',
    unit: 'events',
    description: 'DynamoDB write throttle events by table (provisioned capacity exceeded)',
    dataSource: 'dbDynamoDBStore.writeThrottleEvents',
    view: 'monitoring/db-dynamodb/overview.vue',
    position: 'dynamodb-write-throttle-events',
    defaultQueries: [
      { dialect: 'tfql', expression: 'rate(db.dynamodb.write_throttle_events[5m])', legend: 'Write Throttles' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10305',
    module: 'DBM',
    title: 'System Errors',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'errors',
    description: 'DynamoDB system errors (500-level) over time',
    dataSource: 'dbDynamoDBStore.systemErrors',
    view: 'monitoring/db-dynamodb/overview.vue',
    position: 'dynamodb-system-errors',
    defaultQueries: [
      { dialect: 'tfql', expression: 'db.dynamodb.system_errors', legendFormat: '{{operation}}', seriesKey: 'operation' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10306',
    module: 'DBM',
    title: 'Successful Request Latency',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'ms',
    description: 'DynamoDB successful request latency (p50, p90, p99) over time',
    dataSource: 'dbDynamoDBStore.successfulRequestLatency',
    view: 'monitoring/db-dynamodb/overview.vue',
    position: 'dynamodb-request-latency',
    defaultQueries: [
      { dialect: 'tfql', expression: 'db.dynamodb.successful_request_latency.p50', legend: 'p50' },
      { dialect: 'tfql', expression: 'db.dynamodb.successful_request_latency.p90', legend: 'p90' },
      { dialect: 'tfql', expression: 'db.dynamodb.successful_request_latency.p99', legend: 'p99' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10307',
    module: 'DBM',
    title: 'User Errors',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'errors',
    description: 'DynamoDB user errors (400-level) over time',
    dataSource: 'dbDynamoDBStore.userErrors',
    view: 'monitoring/db-dynamodb/overview.vue',
    position: 'dynamodb-user-errors',
    defaultQueries: [
      { dialect: 'tfql', expression: 'db.dynamodb.user_errors', legendFormat: '{{operation}}', seriesKey: 'operation' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10308',
    module: 'DBM',
    title: 'GSI Consumed Capacity',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'units',
    description: 'DynamoDB Global Secondary Index consumed read and write capacity',
    dataSource: 'dbDynamoDBStore.gsiConsumedCapacity',
    view: 'monitoring/db-dynamodb/overview.vue',
    position: 'dynamodb-gsi-consumed-capacity',
    defaultQueries: [
      { dialect: 'tfql', expression: 'db.dynamodb.online_store.gsi_consumed_read_capacity', legend: 'GSI Read' },
      { dialect: 'tfql', expression: 'db.dynamodb.online_store.gsi_consumed_write_capacity', legend: 'GSI Write' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10309',
    module: 'DBM',
    title: 'Replication Latency',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'ms',
    description: 'DynamoDB global table replication latency across regions',
    dataSource: 'dbDynamoDBStore.replicationLatency',
    view: 'monitoring/db-dynamodb/replication.vue',
    position: 'dynamodb-replication-latency',
    defaultQueries: [
      { dialect: 'tfql', expression: 'db.dynamodb.replication_latency', legendFormat: '{{region}}', seriesKey: 'region' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10310',
    module: 'DBM',
    title: 'Stream Iterator Age',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'ms',
    description: 'DynamoDB Streams iterator age (how far behind the stream consumer is)',
    dataSource: 'dbDynamoDBStore.streamIteratorAge',
    view: 'monitoring/db-dynamodb/overview.vue',
    position: 'dynamodb-stream-iterator-age',
    defaultQueries: [
      { dialect: 'tfql', expression: 'db.dynamodb.get_records.iterator_age', legend: 'Iterator Age' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10311',
    module: 'DBM',
    title: 'DAX Cache Hit Ratio',
    component: 'RegistryGraphPanel',
    chartType: 'gauge',
    signalType: 'metrics',
    unit: 'percent',
    description: 'DynamoDB Accelerator (DAX) cache hit ratio',
    dataSource: 'dbDynamoDBStore.daxCacheHitRatio',
    view: 'monitoring/db-dynamodb/dax.vue',
    position: 'dynamodb-dax-cache-hit',
    defaultQueries: [
      { dialect: 'tfql', expression: 'db.dynamodb.dax.cache_hit_ratio', legend: 'Hit Ratio' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10312',
    module: 'DBM',
    title: 'Auto-Scaling Events',
    component: 'RegistryGraphPanel',
    chartType: 'bar',
    signalType: 'metrics',
    unit: 'events',
    description: 'DynamoDB auto-scaling capacity adjustments over time',
    dataSource: 'dbDynamoDBStore.autoScalingEvents',
    view: 'monitoring/db-dynamodb/overview.vue',
    position: 'dynamodb-autoscaling-events',
    defaultQueries: [
      { dialect: 'tfql', expression: 'rate(db.dynamodb.provisioned_read_capacity_units[5m])', legend: 'Read Scale' },
      { dialect: 'tfql', expression: 'rate(db.dynamodb.provisioned_write_capacity_units[5m])', legend: 'Write Scale' },
    ],
    toggleable: false,
  },
];
