/**
 * Graph Registry — KUBERNETES (K8S)
 * 79 graph definitions
 *
 * Auto-extracted from graph-registry.ts
 */

import type { GraphDefinition } from "./types";

export const K8S_GRAPHS: GraphDefinition[] = [
  // │ KUBERNETES (K8S) - 17 graphs
  // └──────────────────────────────────────────────────────────────────────────────
  {
    graphId: "K8S10001",
    module: "K8S",
    title: "Kubernetes Resource Count",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "count",
    description: "Resource count over time (pods, deployments, etc.)",
    dataSource: "resourceCountTimeSeries",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "sum(k8s.pod.count{}) by (namespace)",
        legendFormat: "{{resource_type}}",
        seriesKey: "resource_type",
      },
    ],
    view: "monitoring/kubernetes/OverviewSection.vue",
    position: "overview-section",
    toggleable: true,
  },
  {
    graphId: "K8S10002",
    module: "K8S",
    title: "Cluster CPU Utilization",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "%",
    description: "Cluster-wide CPU utilization",
    dataSource: "clusterCpuUtilization",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.node.cpu.usage{} by (resource_name)",
        legendFormat: "CPU Usage %",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/ResourcesSection.vue",
    position: "resources-row1-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10003",
    module: "K8S",
    title: "Cluster Memory Utilization",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "%",
    description: "Cluster-wide memory utilization",
    dataSource: "clusterMemoryUtilization",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.node.memory.usage{} by (resource_name)",
        legendFormat: "Memory Usage %",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/ResourcesSection.vue",
    position: "resources-row1-col2",
    toggleable: true,
  },
  {
    graphId: "K8S10004",
    module: "K8S",
    title: "CPU Utilization by Namespace",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "%",
    description: "CPU usage breakdown by namespace",
    dataSource: "cpuByNamespace",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.pod.container.cpu_usage{} by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/kubernetes/ResourcesSection.vue",
    position: "resources-row2-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10005",
    module: "K8S",
    title: "Memory Utilization by Namespace",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "%",
    description: "Memory usage breakdown by namespace",
    dataSource: "memoryByNamespace",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.pod.container.memory_usage{} by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/kubernetes/ResourcesSection.vue",
    position: "resources-row2-col2",
    toggleable: true,
  },
  {
    graphId: "K8S10006",
    module: "K8S",
    title: "CPU Utilization by Instance",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "%",
    description: "CPU usage per node instance",
    dataSource: "cpuByInstance",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.node.cpu.usage{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/ResourcesSection.vue",
    position: "resources-row3-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10007",
    module: "K8S",
    title: "Memory Utilization by Instance",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "%",
    description: "Memory usage per node instance",
    dataSource: "memoryByInstance",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.node.memory.usage{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/ResourcesSection.vue",
    position: "resources-row3-col2",
    toggleable: true,
  },
  {
    graphId: "K8S10008",
    module: "K8S",
    title: "CPU Throttled seconds by Namespace",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "seconds",
    description: "CPU throttling per namespace",
    dataSource: "cpuThrottledByNamespace",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "sum(k8s.pod.container.cpu_throttled{}) by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/kubernetes/ResourcesSection.vue",
    position: "resources-row4-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10009",
    module: "K8S",
    title: "CPU Core Throttled by Instance",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "cores",
    description: "CPU throttling per instance",
    dataSource: "cpuThrottledByInstance",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "sum(k8s.pod.container.cpu_throttled{}) by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/ResourcesSection.vue",
    position: "resources-row4-col2",
    toggleable: true,
  },
  {
    graphId: "K8S10010",
    module: "K8S",
    title: "Pods QoS Classes",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "count",
    description: "Pod distribution by QoS class",
    dataSource: "podsQoSData",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "sum(k8s.pod.qos_class{}) by (qos_class)",
        legendFormat: "{{qos_class}}",
        seriesKey: "qos_class",
      },
    ],
    view: "monitoring/kubernetes/KubernetesSection.vue",
    position: "k8s-row1-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10011",
    module: "K8S",
    title: "Pods Status Reason",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "count",
    description: "Pod status reason breakdown",
    dataSource: "podsStatusReason",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "sum(k8s.pod.status_reason{}) by (reason)",
        legendFormat: "{{reason}}",
        seriesKey: "reason",
      },
    ],
    view: "monitoring/kubernetes/KubernetesSection.vue",
    position: "k8s-row1-col2",
    toggleable: true,
  },
  {
    graphId: "K8S10012",
    module: "K8S",
    title: "OOM Events by Namespace",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "events",
    description: "OOM kill events per namespace",
    dataSource: "oomEventsByNamespace",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "sum(k8s.pod.container.oom_killed{}) by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/kubernetes/KubernetesSection.vue",
    position: "k8s-row2-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10013",
    module: "K8S",
    title: "Container Restarts by Namespace",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "restarts",
    description: "Container restart count per namespace",
    dataSource: "containerRestarts",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "sum(k8s.pod.restart_count{}) by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/kubernetes/KubernetesSection.vue",
    position: "k8s-row2-col2",
    toggleable: true,
  },
  {
    graphId: "K8S10014",
    module: "K8S",
    title: "Global Network Utilization by Device",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "MB/s",
    description: "Network traffic per device",
    dataSource: "networkByDevice",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.node.network.rx_bytes{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/NetworkSection.vue",
    position: "network-row1-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10015",
    module: "K8S",
    title: "Network Saturation - Packets Dropped",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "packets",
    description: "Dropped packets indicating network saturation",
    dataSource: "networkPacketsDropped",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.node.network.io{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/NetworkSection.vue",
    position: "network-row1-col2",
    toggleable: true,
  },
  {
    graphId: "K8S10016",
    module: "K8S",
    title: "Network Received by Namespace",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "MB/s",
    description: "Inbound network traffic per namespace",
    dataSource: "networkByNamespace",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.namespace.network.rx_bytes{} by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/kubernetes/NetworkSection.vue",
    position: "network-row2-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10017",
    module: "K8S",
    title: "Total Network Received by Instance",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "MB/s",
    description: "Inbound network traffic per instance",
    dataSource: "networkByInstance",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.node.network.rx_bytes{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/NetworkSection.vue",
    position: "network-row2-col2",
    toggleable: true,
  },

  // ── Namespace page ─────────────────────────────────────────────────────────────
  {
    graphId: "K8S10018",
    module: "K8S",
    title: "Namespace Count over Time",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Active, terminating, and total namespace counts over time",
    dataSource: "namespaceTimeSeries",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "sum(k8s.namespace.phase{}) by (phase)",
        legendFormat: "{{phase}}",
        seriesKey: "phase",
      },
    ],
    view: "monitoring/kubernetes/namespace-components/OverviewSection.vue",
    position: "ns-overview-chart",
    toggleable: true,
  },
  {
    graphId: "K8S10019",
    module: "K8S",
    title: "CPU Usage by Namespace",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "cores",
    description: "CPU utilization broken down by namespace",
    dataSource: "cpuByNamespace",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.pod.container.cpu_usage{} by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/kubernetes/namespace-components/ResourcesSection.vue",
    position: "ns-resources-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10020",
    module: "K8S",
    title: "Memory Usage by Namespace",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "GiB",
    description: "Memory usage broken down by namespace",
    dataSource: "memoryByNamespace",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.pod.container.memory_usage{} by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/kubernetes/namespace-components/ResourcesSection.vue",
    position: "ns-resources-col2",
    toggleable: true,
  },
  {
    graphId: "K8S10021",
    module: "K8S",
    title: "Pods by Namespace",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Pod count per namespace over time",
    dataSource: "podsByNamespace",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "sum(k8s.pod.count{}) by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/kubernetes/namespace-components/ResourcesSection.vue",
    position: "ns-resources-row2",
    toggleable: true,
  },
  {
    graphId: "K8S10022",
    module: "K8S",
    title: "Deployments by Namespace",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Deployment count per namespace",
    dataSource: "deploymentsByNamespace",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "sum(k8s.deployment.replicas{}) by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/kubernetes/namespace-components/WorkloadsSection.vue",
    position: "ns-workloads-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10023",
    module: "K8S",
    title: "Services by Namespace",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Service count per namespace",
    dataSource: "servicesByNamespace",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "sum(k8s.service.count{}) by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/kubernetes/namespace-components/WorkloadsSection.vue",
    position: "ns-workloads-col2",
    toggleable: true,
  },
  {
    graphId: "K8S10024",
    module: "K8S",
    title: "Ingresses by Namespace",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Ingress count per namespace",
    dataSource: "ingressByNamespace",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "sum(k8s.ingress.count{}) by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/kubernetes/namespace-components/WorkloadsSection.vue",
    position: "ns-workloads-col3",
    toggleable: true,
  },

  // ── Nodes page ─────────────────────────────────────────────────────────────────
  {
    graphId: "K8S10025",
    module: "K8S",
    title: "Node Status over Time",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Ready, not-ready, and total node counts over time",
    dataSource: "nodeTimeSeries",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.node.status{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/nodes-components/OverviewSection.vue",
    position: "nodes-overview-chart",
    toggleable: true,
  },
  {
    graphId: "K8S10026",
    module: "K8S",
    title: "CPU Usage by Node",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "%",
    description: "CPU utilization percentage per node",
    dataSource: "cpuByNode",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.node.cpu.usage{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/nodes-components/ResourcesSection.vue",
    position: "nodes-resources-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10027",
    module: "K8S",
    title: "Memory Usage by Node",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "%",
    description: "Memory utilization percentage per node",
    dataSource: "memoryByNode",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.node.memory.usage{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/nodes-components/ResourcesSection.vue",
    position: "nodes-resources-col2",
    toggleable: true,
  },
  {
    graphId: "K8S10028",
    module: "K8S",
    title: "Disk Usage by Node",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "%",
    description: "Disk utilization percentage per node",
    dataSource: "diskByNode",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.node.filesystem.usage{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/nodes-components/ResourcesSection.vue",
    position: "nodes-resources-col3",
    toggleable: true,
  },
  {
    graphId: "K8S10029",
    module: "K8S",
    title: "Network I/O by Node",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "KiB/s",
    description: "Network throughput per node (receive + transmit)",
    dataSource: "networkByNode",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.node.network.io{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/nodes-components/ResourcesSection.vue",
    position: "nodes-resources-col4",
    toggleable: true,
  },
  {
    graphId: "K8S10030",
    module: "K8S",
    title: "Disk Pressure",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Nodes reporting DiskPressure condition over time",
    dataSource: "diskPressure",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.node.condition.disk_pressure{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/nodes-components/ConditionsSection.vue",
    position: "nodes-conditions-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10031",
    module: "K8S",
    title: "Memory Pressure",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Nodes reporting MemoryPressure condition over time",
    dataSource: "memoryPressure",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.node.condition.memory_pressure{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/nodes-components/ConditionsSection.vue",
    position: "nodes-conditions-col2",
    toggleable: true,
  },
  {
    graphId: "K8S10032",
    module: "K8S",
    title: "PID Pressure",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Nodes reporting PIDPressure condition over time",
    dataSource: "pidPressure",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.node.condition.pid_pressure{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/nodes-components/ConditionsSection.vue",
    position: "nodes-conditions-col3",
    toggleable: true,
  },
  {
    graphId: "K8S10033",
    module: "K8S",
    title: "Network Unavailable",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Nodes reporting NetworkUnavailable condition over time",
    dataSource: "networkUnavailable",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.node.condition.network_unavailable{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/nodes-components/ConditionsSection.vue",
    position: "nodes-conditions-col4",
    toggleable: true,
  },

  // ── Pods page ──────────────────────────────────────────────────────────────────
  {
    graphId: "K8S10034",
    module: "K8S",
    title: "Pod Status over Time",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Running, pending, succeeded, and failed pod counts over time",
    dataSource: "podTimeSeries",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "count(k8s.pod.phase{}) by (phase)",
        legendFormat: "{{phase}}",
        seriesKey: "phase",
      },
    ],
    view: "monitoring/kubernetes/pods-components/OverviewSection.vue",
    position: "pods-overview-chart",
    toggleable: true,
  },
  {
    graphId: "K8S10035",
    module: "K8S",
    title: "Container Restarts by Pod",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Container restart count per pod",
    dataSource: "restartsByPod",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "sum(k8s.pod.restart_count{}) by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/pods-components/HealthSection.vue",
    position: "pods-health-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10036",
    module: "K8S",
    title: "OOM Killed Containers",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Containers killed by OOM over time",
    dataSource: "oomKilledPods",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "sum(k8s.pod.container.oom_killed{}) by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/pods-components/HealthSection.vue",
    position: "pods-health-col2",
    toggleable: true,
  },
  {
    graphId: "K8S10037",
    module: "K8S",
    title: "Pods by QoS Class",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description:
      "Pod count grouped by QoS class (Guaranteed/Burstable/BestEffort)",
    dataSource: "podsByQoS",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "sum(k8s.pod.qos_class{}) by (qos_class)",
        legendFormat: "{{qos_class}}",
        seriesKey: "qos_class",
      },
    ],
    view: "monitoring/kubernetes/pods-components/HealthSection.vue",
    position: "pods-health-col3",
    toggleable: true,
  },
  {
    graphId: "K8S10038",
    module: "K8S",
    title: "Container Status",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description:
      "Container state breakdown (running, waiting, terminated) over time",
    dataSource: "containerStatus",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "sum(k8s.pod.container.status{}) by (status)",
        legendFormat: "{{state}}",
        seriesKey: "state",
      },
    ],
    view: "monitoring/kubernetes/pods-components/HealthSection.vue",
    position: "pods-health-col4",
    toggleable: true,
  },
  {
    graphId: "K8S10039",
    module: "K8S",
    title: "Pod CPU Usage",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "cores",
    description: "CPU cores consumed per pod",
    dataSource: "cpuUsageByPod",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.pod.container.cpu_usage{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/pods-components/ResourcesSection.vue",
    position: "pods-resources-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10040",
    module: "K8S",
    title: "Pod Memory Usage",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "MiB",
    description: "Memory consumed per pod",
    dataSource: "memoryUsageByPod",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.pod.container.memory_usage{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/pods-components/ResourcesSection.vue",
    position: "pods-resources-col2",
    toggleable: true,
  },
  {
    graphId: "K8S10041",
    module: "K8S",
    title: "Pod CPU Throttled",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "sec",
    description: "CPU throttled seconds per pod",
    dataSource: "cpuThrottled",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "sum(k8s.pod.container.cpu_throttled{}) by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/pods-components/ResourcesSection.vue",
    position: "pods-resources-col3",
    toggleable: true,
  },
  {
    graphId: "K8S10042",
    module: "K8S",
    title: "Pod Memory Working Set",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "MiB",
    description: "Active memory (working set) per pod",
    dataSource: "memoryWorkingSet",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.pod.container.memory_working_set{} by (resource_name)",
        legendFormat: "{{resource_name}}",
        seriesKey: "resource_name",
      },
    ],
    view: "monitoring/kubernetes/pods-components/ResourcesSection.vue",
    position: "pods-resources-col4",
    toggleable: true,
  },

  // ── Persistent Volumes page ────────────────────────────────────────────────────
  {
    graphId: "K8S10043",
    module: "K8S",
    title: "PV Status over Time",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Bound, available, released, and failed PV counts over time",
    dataSource: "pvTimeSeries",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "sum(k8s.pv.phase{}) by (phase)",
        legendFormat: "{{phase}}",
        seriesKey: "phase",
      },
    ],
    view: "monitoring/kubernetes/pv-components/OverviewSection.vue",
    position: "pv-overview-chart",
    toggleable: true,
  },
  {
    graphId: "K8S10044",
    module: "K8S",
    title: "PV Count by Storage Class",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Persistent volume count per storage class",
    dataSource: "storageByClass",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "sum(k8s.pv.info{}) by (storage_class)",
        legendFormat: "{{storageclass}}",
        seriesKey: "storageclass",
      },
    ],
    view: "monitoring/kubernetes/pv-components/StorageSection.vue",
    position: "pv-storage-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10045",
    module: "K8S",
    title: "Capacity by Storage Class",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "GiB",
    description: "Total storage capacity per storage class",
    dataSource: "capacityByClass",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.pv.capacity_bytes{} by (resource_name)",
        legendFormat: "{{storageclass}}",
        seriesKey: "storageclass",
      },
    ],
    view: "monitoring/kubernetes/pv-components/StorageSection.vue",
    position: "pv-storage-col2",
    toggleable: true,
  },
  {
    graphId: "K8S10046",
    module: "K8S",
    title: "Storage Usage by Namespace",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "GiB",
    description: "PVC storage usage per namespace",
    dataSource: "usageByNamespace",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.pv.used_bytes{} by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/kubernetes/pv-components/StorageSection.vue",
    position: "pv-storage-col3",
    toggleable: true,
  },
  {
    graphId: "K8S10047",
    module: "K8S",
    title: "Inodes Used by Namespace",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Volume inodes usage across namespaces",
    dataSource: "inodesMetrics",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "k8s.pv.inodes_used{} by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/kubernetes/pv-components/StorageSection.vue",
    position: "pv-storage-col4",
    toggleable: true,
  },

  // ── Deployments page ───────────────────────────────────────────────────────────
  {
    graphId: "K8S10048",
    module: "K8S",
    title: "Deployment Status over Time",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description:
      "Available, progressing, degraded, and paused deployment counts",
    dataSource: "deploymentTimeSeries",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "sum(k8s.deployment.condition{}) by (condition)",
        legendFormat: "{{condition}} - {{status}}",
        seriesKey: "condition,status",
      },
    ],
    view: "monitoring/kubernetes/deployment-components/OverviewSection.vue",
    position: "deploy-overview-chart",
    toggleable: true,
  },
  {
    graphId: "K8S10049",
    module: "K8S",
    title: "Desired vs Available Replicas",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description:
      "Desired replica count compared to currently available replicas",
    dataSource: "desiredReplicas",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.deployment.replicas{}",
        legendFormat: "Desired vs Available Replicas",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/kubernetes/deployment-components/ReplicasSection.vue",
    position: "deploy-replicas-col1",
    toggleable: true,
  },
  {
    graphId: "K8S10050",
    module: "K8S",
    title: "Available Replicas",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Replicas that have passed the readiness probe",
    dataSource: "availableReplicas",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.deployment.replicas.available{}",
        legendFormat: "Available Replicas",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/kubernetes/deployment-components/ReplicasSection.vue",
    position: "deploy-replicas-col2",
    toggleable: true,
  },
  {
    graphId: "K8S10051",
    module: "K8S",
    title: "Unavailable Replicas",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Replicas that have not passed the readiness probe",
    dataSource: "unavailableReplicas",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.deployment.replicas.unavailable{}",
        legendFormat: "Unavailable Replicas",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/kubernetes/deployment-components/ReplicasSection.vue",
    position: "deploy-replicas-col3",
    toggleable: true,
  },
  {
    graphId: "K8S10052",
    module: "K8S",
    title: "Updated Replicas",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Replicas successfully updated to the latest pod template",
    dataSource: "updatedReplicas",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.deployment.replicas.updated{}",
        legendFormat: "Updated Replicas",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/kubernetes/deployment-components/ReplicasSection.vue",
    position: "deploy-replicas-col4",
    toggleable: true,
  },

  // ── HPA (K8S10053-K8S10056) ─────────────────────────────────────────────────
  {
    graphId: "K8S10053",
    module: "K8S",
    title: "HPA Current vs Desired Replicas",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description:
      "Current and desired replica counts per HorizontalPodAutoscaler",
    dataSource: "hpaTimeSeries",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.hpa.replicas.current",
        legendFormat: "HPA Current vs Desired Replicas",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/kubernetes/overview-components/KubernetesSection.vue",
    position: "k8s-hpa-replicas",
    toggleable: true,
  },
  {
    graphId: "K8S10054",
    module: "K8S",
    title: "HPA Min / Max Bounds",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Minimum and maximum replica bounds configured on each HPA",
    dataSource: "hpaTimeSeries",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.hpa.replicas.min",
        legendFormat: "HPA Min / Max Bounds",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/kubernetes/overview-components/KubernetesSection.vue",
    position: "k8s-hpa-bounds",
    toggleable: true,
  },
  {
    graphId: "K8S10055",
    module: "K8S",
    title: "HPA Scaling Conditions",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description:
      "AbleToScale / ScalingActive / ScalingLimited condition status per HPA",
    dataSource: "hpaTimeSeries",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.hpa.condition",
        legendFormat: "HPA Scaling Conditions",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/kubernetes/overview-components/KubernetesSection.vue",
    position: "k8s-hpa-conditions",
    toggleable: true,
  },
  // ── PDB (K8S10056-K8S10060) ─────────────────────────────────────────────────
  {
    graphId: "K8S10056",
    module: "K8S",
    title: "PDB Disruptions Allowed",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description:
      "Number of simultaneous pod disruptions currently allowed by each PDB",
    dataSource: "pdbTimeSeries",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.pdb.disruptions_allowed",
        legendFormat: "PDB Disruptions Allowed",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/kubernetes/overview-components/KubernetesSection.vue",
    position: "k8s-pdb-disruptions",
    toggleable: true,
  },
  {
    graphId: "K8S10057",
    module: "K8S",
    title: "PDB Healthy Pods",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "",
    description: "Current healthy pods vs desired healthy threshold per PDB",
    dataSource: "pdbTimeSeries",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.pdb.pods.current_healthy",
        legendFormat: "PDB Healthy Pods",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/kubernetes/overview-components/KubernetesSection.vue",
    position: "k8s-pdb-healthy",
    toggleable: true,
  },
  {
    graphId: "K8S10058",
    module: "K8S",
    title: "Memory Working Set by Pod",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "MiB",
    description:
      "Active memory working set (MiB) for top 10 pods — from Kubelet /stats/summary",
    dataSource: "memoryWorkingSetByPod",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.pod.container.memory_working_set",
        legendFormat: "Memory Working Set by Pod",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/kubernetes/pods-components/ResourcesSection.vue",
    position: "pod-memory-working-set",
    toggleable: true,
  },

  // ┌──────────────────────────────────────────────────────────────────────────────
  // │ K8S - API SERVER (K8S10059-K8S10070) - 12 graphs
  // └──────────────────────────────────────────────────────────────────────────────
  {
    graphId: "K8S10059",
    module: "K8S",
    title: "API Server - Health Status",
    component: "StatPanel",
    chartType: "stat",
    signalType: "kubernetes",
    unit: "count",
    description: "API Server health status (up=1, down=0)",
    dataSource: "apiserver_health",
    defaultQueries: [{ dialect: "promql", expression: 'up{job="apiserver"}', legendFormat: "API Server Health", seriesKey: "__name__" }],
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-health",
    toggleable: false,
  },
  {
    graphId: "K8S10060",
    module: "K8S",
    title: "API Requests / sec (by HTTP code)",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "reqps",
    description: "Rate of API server HTTP requests grouped by response code",
    dataSource: "apiserver_requests_by_code",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          "sum by (code) (rate(apiserver_request_total[$__rate_interval]))",
        legendFormat: "{{code}}",
        seriesKey: "code",
      },
    ],
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-requests-code",
    toggleable: true,
  },
  {
    graphId: "K8S10061",
    module: "K8S",
    title: "API Requests / sec (by verb)",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "reqps",
    description:
      "Rate of API server HTTP requests grouped by verb (GET, POST, etc.)",
    dataSource: "apiserver_requests_by_verb",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          "sum by (verb) (rate(apiserver_request_total[$__rate_interval]))",
        legendFormat: "{{verb}}",
        seriesKey: "verb",
      },
    ],
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-requests-verb",
    toggleable: true,
  },
  {
    graphId: "K8S10062",
    module: "K8S",
    title: "API Request Latency (by verb)",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "s",
    description: "Average API server request latency by verb",
    dataSource: "apiserver_latency_by_verb",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          'sum(rate(apiserver_request_duration_seconds_sum{job="apiserver"}[$__rate_interval])) by (verb) / sum(rate(apiserver_request_duration_seconds_count{job="apiserver"}[$__rate_interval])) by (verb)',
        legendFormat: "{{verb}}",
        seriesKey: "verb",
      },
    ],
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-latency-verb",
    toggleable: true,
  },
  {
    graphId: "K8S10063",
    module: "K8S",
    title: "API Request Latency (by instance)",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "s",
    description: "Average API server request latency by instance",
    dataSource: "apiserver_latency_by_instance",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          'sum(rate(apiserver_request_duration_seconds_sum{job="apiserver"}[$__rate_interval])) by (instance) / sum(rate(apiserver_request_duration_seconds_count{job="apiserver"}[$__rate_interval])) by (instance)',
        legendFormat: "{{instance}}",
        seriesKey: "instance",
      },
    ],
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-latency-instance",
    toggleable: true,
  },
  {
    graphId: "K8S10064",
    module: "K8S",
    title: "API Errors (5xx) by Instance",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "percent",
    description: "Rate of 5xx errors by API server instance",
    dataSource: "apiserver_errors_by_instance",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          'sum by(instance) (rate(apiserver_request_total{code=~"5..",job="apiserver"}[$__rate_interval])) / sum by(instance) (rate(apiserver_request_total{job="apiserver"}[$__rate_interval]))',
        legendFormat: "{{instance}}",
        seriesKey: "instance",
      },
    ],
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-errors-instance",
    toggleable: true,
  },
  {
    graphId: "K8S10065",
    module: "K8S",
    title: "API Errors (5xx) by Verb",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "percent",
    description: "Rate of 5xx errors grouped by verb",
    dataSource: "apiserver_errors_by_verb",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          'sum by(verb) (rate(apiserver_request_total{code=~"5..",job="apiserver"}[$__rate_interval])) / sum by(verb) (rate(apiserver_request_total{job="apiserver"}[$__rate_interval]))',
        legendFormat: "{{verb}}",
        seriesKey: "verb",
      },
    ],
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-errors-verb",
    toggleable: true,
  },
  {
    graphId: "K8S10066",
    module: "K8S",
    title: "Work Queue Depth (by instance)",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "count",
    description: "API server work queue depth per instance",
    dataSource: "apiserver_workqueue",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          'sum(rate(workqueue_depth{job="apiserver"}[$__rate_interval])) by (instance)',
        legendFormat: "{{instance}}",
        seriesKey: "instance",
      },
    ],
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-workqueue",
    toggleable: true,
  },
  {
    graphId: "K8S10067",
    module: "K8S",
    title: "API Server CPU Usage",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "cores",
    description: "API server process CPU usage",
    dataSource: "apiserver_cpu",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          'rate(process_cpu_seconds_total{job="apiserver"}[$__rate_interval])',
        legendFormat: "API Server CPU Usage",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-cpu",
    toggleable: true,
  },
  {
    graphId: "K8S10068",
    module: "K8S",
    title: "API Server Memory Usage",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "MB",
    description: "API server process resident memory",
    dataSource: "apiserver_memory",
    defaultQueries: [
      {
        dialect: "promql",
        expression: 'process_resident_memory_bytes{job="apiserver"}',
        legendFormat: "API Server Memory Usage",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-memory",
    toggleable: true,
  },
  {
    graphId: "K8S10069",
    module: "K8S",
    title: "Deprecated Resource Requests",
    component: "BarChart",
    chartType: "bar",
    signalType: "kubernetes",
    unit: "count",
    description: "Deprecated Kubernetes API resources being requested",
    dataSource: "apiserver_deprecated_resources",
    defaultQueries: [
      { dialect: "promql", expression: "apiserver_requested_deprecated_apis", legendFormat: "Deprecated Resource Requests", seriesKey: "__name__" },
    ],
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-deprecated",
    toggleable: true,
  },
  {
    graphId: "K8S10070",
    module: "K8S",
    title: "API Requests Stacked (by instance)",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "reqps",
    description: "Stacked HTTP request rate by instance",
    dataSource: "apiserver_requests_stacked",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          "sum(rate(apiserver_request_total[$__rate_interval])) by (instance)",
        legendFormat: "{{instance}}",
        seriesKey: "instance",
      },
    ],
    view: "monitoring/kubernetes/api-server.vue",
    position: "api-requests-stacked",
    toggleable: true,
  },

  // ┌──────────────────────────────────────────────────────────────────────────────
  // │ K8S - COREDNS (K8S10071-K8S10079) - 9 graphs
  // └──────────────────────────────────────────────────────────────────────────────
  {
    graphId: "K8S10071",
    module: "K8S",
    title: "CoreDNS - Health Status",
    component: "StatPanel",
    chartType: "stat",
    signalType: "kubernetes",
    unit: "count",
    description: "CoreDNS pod health status",
    dataSource: "coredns_health",
    defaultQueries: [{ dialect: "promql", expression: 'up{job="coredns"}', legendFormat: "CoreDNS Health", seriesKey: "__name__" }],
    view: "monitoring/kubernetes/coredns.vue",
    position: "dns-health",
    toggleable: false,
  },
  {
    graphId: "K8S10072",
    module: "K8S",
    title: "DNS Requests / sec",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "reqps",
    description: "Rate of DNS requests handled by CoreDNS",
    dataSource: "coredns_requests",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          "sum(rate(coredns_dns_requests_total[$__rate_interval])) by (server, proto)",
        legendFormat: "{{server}} - {{proto}}",
        seriesKey: "server,proto",
      },
    ],
    view: "monitoring/kubernetes/coredns.vue",
    position: "dns-requests",
    toggleable: true,
  },
  {
    graphId: "K8S10073",
    module: "K8S",
    title: "DNS Responses by rcode",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "reqps",
    description:
      "CoreDNS response rate by rcode (NOERROR, NXDOMAIN, SERVFAIL, etc.)",
    dataSource: "coredns_responses_rcode",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          "sum(rate(coredns_dns_responses_total[$__rate_interval])) by (rcode)",
        legendFormat: "{{rcode}}",
        seriesKey: "rcode",
      },
    ],
    view: "monitoring/kubernetes/coredns.vue",
    position: "dns-responses-rcode",
    toggleable: true,
  },
  {
    graphId: "K8S10074",
    module: "K8S",
    title: "DNS Request Duration (p99)",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "s",
    description: "99th percentile DNS request duration",
    dataSource: "coredns_duration_p99",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket[$__rate_interval])) by (le, server))",
        legendFormat: "{{le}} - {{server}}",
        seriesKey: "le,server",
      },
    ],
    view: "monitoring/kubernetes/coredns.vue",
    position: "dns-duration-p99",
    toggleable: true,
  },
  {
    graphId: "K8S10075",
    module: "K8S",
    title: "DNS Cache Hits / Misses",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "reqps",
    description: "CoreDNS cache hit and miss rate",
    dataSource: "coredns_cache",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          "sum(rate(coredns_cache_hits_total[$__rate_interval])) by (server, type)",
        legendFormat: "{{server}} - {{type}}",
        seriesKey: "server,type",
      },
    ],
    view: "monitoring/kubernetes/coredns.vue",
    position: "dns-cache",
    toggleable: true,
  },
  {
    graphId: "K8S10076",
    module: "K8S",
    title: "DNS Error Rate",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "reqps",
    description: "Rate of DNS errors (SERVFAIL)",
    dataSource: "coredns_errors",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          'sum(rate(coredns_dns_responses_total{rcode="SERVFAIL"}[$__rate_interval])) by (server)',
        legendFormat: "{{server}}",
        seriesKey: "server",
      },
    ],
    view: "monitoring/kubernetes/coredns.vue",
    position: "dns-errors",
    toggleable: true,
  },
  {
    graphId: "K8S10077",
    module: "K8S",
    title: "Upstream Requests / sec",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "reqps",
    description: "CoreDNS upstream (forward) request rate",
    dataSource: "coredns_upstream_requests",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          "sum(rate(coredns_forward_requests_total[$__rate_interval])) by (to)",
        legendFormat: "{{to}}",
        seriesKey: "to",
      },
    ],
    view: "monitoring/kubernetes/coredns.vue",
    position: "dns-upstream",
    toggleable: true,
  },
  {
    graphId: "K8S10078",
    module: "K8S",
    title: "CoreDNS CPU Usage",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "cores",
    description: "CoreDNS process CPU usage",
    dataSource: "coredns_cpu",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          'rate(process_cpu_seconds_total{job="coredns"}[$__rate_interval])',
        legendFormat: "CoreDNS CPU Usage",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/kubernetes/coredns.vue",
    position: "dns-cpu",
    toggleable: true,
  },
  {
    graphId: "K8S10079",
    module: "K8S",
    title: "CoreDNS Memory Usage",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "MB",
    description: "CoreDNS process resident memory",
    dataSource: "coredns_memory",
    defaultQueries: [
      {
        dialect: "promql",
        expression: 'process_resident_memory_bytes{job="coredns"}',
        legendFormat: "CoreDNS Memory Usage",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/kubernetes/coredns.vue",
    position: "dns-memory",
    toggleable: true,
  },

];
