/**
 * Graph Registry — PostgreSQL (DBM)
 * 12 graph definitions
 */

import type { GraphDefinition } from "./types";

export const DBM_POSTGRESQL_GRAPHS: GraphDefinition[] = [
  {
    graphId: "DBM10101",
    module: "DBM",
    title: "Connections Over Time",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "connections",
    description: "PostgreSQL connection states over time: active, idle, idle in transaction, waiting",
    dataSource: "db_postgresql_metrics",
    view: "monitoring/db-postgresql/overview.vue",
    position: "postgresql-connections",
    defaultQueries: [
      { dialect: "tfql", expression: "db.postgresql.connections.active", legend: "Active" },
      { dialect: "tfql", expression: "db.postgresql.connections.idle", legend: "Idle" },
      { dialect: "tfql", expression: "db.postgresql.connections.idle_in_transaction", legend: "Idle in Transaction" },
      { dialect: "tfql", expression: "db.postgresql.connections.waiting", legend: "Waiting" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10102",
    module: "DBM",
    title: "Transaction Rate",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "txns/s",
    description: "PostgreSQL commit and rollback rates over time",
    dataSource: "db_postgresql_metrics",
    view: "monitoring/db-postgresql/overview.vue",
    position: "postgresql-transaction-rate",
    defaultQueries: [
      { dialect: "tfql", expression: "rate(db.postgresql.xact_commit[1m])", legend: "Commits/s" },
      { dialect: "tfql", expression: "rate(db.postgresql.xact_rollback[1m])", legend: "Rollbacks/s" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10103",
    module: "DBM",
    title: "Tuple Operations",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "ops/s",
    description: "PostgreSQL tuple insert, update, and delete rates",
    dataSource: "db_postgresql_metrics",
    view: "monitoring/db-postgresql/overview.vue",
    position: "postgresql-tuple-ops",
    defaultQueries: [
      { dialect: "tfql", expression: "rate(db.postgresql.tup_inserted[1m])", legend: "Inserted" },
      { dialect: "tfql", expression: "rate(db.postgresql.tup_updated[1m])", legend: "Updated" },
      { dialect: "tfql", expression: "rate(db.postgresql.tup_deleted[1m])", legend: "Deleted" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10104",
    module: "DBM",
    title: "Cache Hit Ratio",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "percent",
    description: "PostgreSQL buffer cache hit ratio over time",
    dataSource: "db_postgresql_metrics",
    view: "monitoring/db-postgresql/overview.vue",
    position: "postgresql-cache-hit",
    defaultQueries: [
      { dialect: "tfql", expression: "db.postgresql.cache_hit_ratio", legend: "Hit Ratio" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10105",
    module: "DBM",
    title: "Checkpoint Activity",
    component: "RegistryGraphPanel",
    chartType: "bar",
    signalType: "metrics",
    unit: "count",
    description: "PostgreSQL checkpoint frequency: timed vs requested",
    dataSource: "db_postgresql_metrics",
    view: "monitoring/db-postgresql/overview.vue",
    position: "postgresql-checkpoints",
    defaultQueries: [
      { dialect: "tfql", expression: "rate(db.postgresql.checkpoints_timed[5m])", legend: "Timed" },
      { dialect: "tfql", expression: "rate(db.postgresql.checkpoints_req[5m])", legend: "Requested" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10106",
    module: "DBM",
    title: "WAL Generation Rate",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "bytes/s",
    description: "PostgreSQL WAL (Write-Ahead Log) generation rate",
    dataSource: "db_postgresql_metrics",
    view: "monitoring/db-postgresql/overview.vue",
    position: "postgresql-wal-rate",
    defaultQueries: [
      { dialect: "tfql", expression: "rate(db.postgresql.wal_bytes[1m])", legend: "WAL Bytes/s" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10107",
    module: "DBM",
    title: "Dead Tuples by Table",
    component: "RegistryGraphPanel",
    chartType: "bar",
    signalType: "metrics",
    unit: "tuples",
    description: "PostgreSQL dead tuple counts per table",
    dataSource: "db_postgresql_metrics",
    view: "monitoring/db-postgresql/schema-browser.vue",
    position: "postgresql-dead-tuples",
    defaultQueries: [
      { dialect: "tfql", expression: "db.postgresql.stat_user_tables.n_dead_tup", legendFormat: "{{tablename}}", seriesKey: "tablename" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10108",
    module: "DBM",
    title: "Lock Contention",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "locks",
    description: "PostgreSQL lock contention: waiting locks and max wait duration",
    dataSource: "db_postgresql_metrics",
    view: "monitoring/db-postgresql/overview.vue",
    position: "postgresql-lock-contention",
    defaultQueries: [
      { dialect: "tfql", expression: "db.postgresql.locks.waiting", legend: "Waiting Locks" },
      { dialect: "tfql", expression: "db.postgresql.locks.max_wait_seconds", legend: "Max Wait (s)" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10109",
    module: "DBM",
    title: "Database Size",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "bytes",
    description: "PostgreSQL database size growth over time",
    dataSource: "db_postgresql_metrics",
    view: "monitoring/db-postgresql/overview.vue",
    position: "postgresql-db-size",
    defaultQueries: [
      { dialect: "tfql", expression: "db.postgresql.database_size_bytes", legendFormat: "{{datname}}", seriesKey: "datname" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10110",
    module: "DBM",
    title: "Replication Lag",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "seconds",
    description: "PostgreSQL replication lag in bytes and seconds",
    dataSource: "db_postgresql_metrics",
    view: "monitoring/db-postgresql/replication.vue",
    position: "postgresql-repl-lag",
    defaultQueries: [
      { dialect: "tfql", expression: "db.postgresql.replication.lag_bytes", legend: "Lag (bytes)" },
      { dialect: "tfql", expression: "db.postgresql.replication.lag_seconds", legend: "Lag (seconds)" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10111",
    module: "DBM",
    title: "Query Time Heatmap",
    component: "RegistryGraphPanel",
    chartType: "heatmap",
    signalType: "metrics",
    unit: "ms",
    description: "PostgreSQL query execution time distribution heatmap",
    dataSource: "db_postgresql_metrics",
    view: "monitoring/db-postgresql/query-analytics.vue",
    position: "postgresql-query-heatmap",
    defaultQueries: [
      { dialect: "tfql", expression: "db.postgresql.query.duration_bucket", legendFormat: "{{le}}", seriesKey: "le" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10112",
    module: "DBM",
    title: "Temp Files",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "count",
    description: "PostgreSQL temporary file creation count and total bytes",
    dataSource: "db_postgresql_metrics",
    view: "monitoring/db-postgresql/overview.vue",
    position: "postgresql-temp-files",
    defaultQueries: [
      { dialect: "tfql", expression: "rate(db.postgresql.temp_files[1m])", legend: "Temp Files/s" },
      { dialect: "tfql", expression: "rate(db.postgresql.temp_bytes[1m])", legend: "Temp Bytes/s" },
    ],
    toggleable: false,
  },
];
