import type { GraphDefinition } from './types';

// Allocated ID range: DBM11001-DBM11012
export const DBM_SQLITE3_GRAPHS: GraphDefinition[] = [
  {
    graphId: 'DBM11001',
    module: 'DBM',
    title: 'File Size Over Time',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'bytes',
    description: 'Database file size trend',
    dataSource: 'db_sqlite3_metrics',
    view: 'db-monitoring/sqlite3/Sqlite3InstanceDetailView.vue',
    position: 'sqlite3-file-size',
    defaultQueries: [
      { dialect: 'tfql', expression: 'sqlite.file_size_bytes', legend: 'File Size' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM11002',
    module: 'DBM',
    title: 'Cache Hit Ratio',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: '%',
    description: 'Page cache hit ratio over time',
    dataSource: 'db_sqlite3_metrics',
    view: 'db-monitoring/sqlite3/Sqlite3InstanceDetailView.vue',
    position: 'sqlite3-cache-hit',
    defaultQueries: [
      { dialect: 'tfql', expression: 'sqlite.cache.hit_ratio', legend: 'Hit Ratio' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM11003',
    module: 'DBM',
    title: 'Page Count',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'pages',
    description: 'Total database pages over time',
    dataSource: 'db_sqlite3_metrics',
    view: 'db-monitoring/sqlite3/Sqlite3InstanceDetailView.vue',
    position: 'sqlite3-page-count',
    defaultQueries: [
      { dialect: 'tfql', expression: 'sqlite.page_count', legend: 'Pages' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM11004',
    module: 'DBM',
    title: 'WAL Frames',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'frames',
    description: 'Write-ahead log frame count',
    dataSource: 'db_sqlite3_metrics',
    view: 'db-monitoring/sqlite3/Sqlite3InstanceDetailView.vue',
    position: 'sqlite3-wal-frames',
    defaultQueries: [
      { dialect: 'tfql', expression: 'sqlite.wal.frame_count', legend: 'WAL Frames' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM11005',
    module: 'DBM',
    title: 'Busy Handler Invocations',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'count',
    description: 'Busy handler invocation count over time',
    dataSource: 'db_sqlite3_metrics',
    view: 'db-monitoring/sqlite3/Sqlite3InstanceDetailView.vue',
    position: 'sqlite3-busy-handler',
    defaultQueries: [
      { dialect: 'tfql', expression: 'sqlite.busy.handler_count', legend: 'Invocations' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM11006',
    module: 'DBM',
    title: 'Active Processes',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'processes',
    description: 'Number of active database connections/processes',
    dataSource: 'db_sqlite3_metrics',
    view: 'db-monitoring/sqlite3/Sqlite3InstanceDetailView.vue',
    position: 'sqlite3-processes',
    defaultQueries: [
      { dialect: 'tfql', expression: 'sqlite.process.count', legend: 'Processes' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM11007',
    module: 'DBM',
    title: 'Page Utilization',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: '%',
    description: 'Page utilization percentage over time',
    dataSource: 'db_sqlite3_metrics',
    view: 'db-monitoring/sqlite3/Sqlite3InstanceDetailView.vue',
    position: 'sqlite3-utilization',
    defaultQueries: [
      { dialect: 'tfql', expression: 'sqlite.page.utilization_pct', legend: 'Utilization' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM11008',
    module: 'DBM',
    title: 'Lock Wait Time',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'ms',
    description: 'Lock contention wait time',
    dataSource: 'db_sqlite3_metrics',
    view: 'db-monitoring/sqlite3/Sqlite3InstanceDetailView.vue',
    position: 'sqlite3-lock-wait',
    defaultQueries: [
      { dialect: 'tfql', expression: 'sqlite.lock.wait_time_ms', legend: 'Wait Time' },
    ],
    toggleable: false,
  },
];
