import type { GraphDefinition } from "./types";

export const DBM_MYSQL_GRAPHS: GraphDefinition[] = [
  {
    graphId: "DBM10001",
    module: "DBM",
    title: "Queries Per Second",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "qps",
    description: "QPS breakdown (select/insert/update/delete)",
    dataSource: "db_mysql_metrics",
    view: "monitoring/db-mysql/overview.vue",
    position: "mysql-qps",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mysql.qps", legend: "QPS" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10002",
    module: "DBM",
    title: "Active Connections",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "connections",
    description: "Active vs max connections",
    dataSource: "db_mysql_metrics",
    view: "monitoring/db-mysql/overview.vue",
    position: "mysql-connections",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "db.mysql.connections.active",
        legend: "Active",
      },
      {
        dialect: "tfql",
        expression: "db.mysql.connections.max",
        legend: "Max",
      },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10003",
    module: "DBM",
    title: "InnoDB Buffer Pool",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "percent",
    description: "Buffer pool utilization and hit ratio",
    dataSource: "db_mysql_metrics",
    view: "monitoring/db-mysql/overview.vue",
    position: "mysql-buffer-pool",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "db.mysql.buffer_pool_hit_ratio",
        legend: "Hit Ratio",
      },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10004",
    module: "DBM",
    title: "InnoDB Row Operations",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "ops/s",
    description: "Row reads, inserts, updates, deletes",
    dataSource: "db_mysql_metrics",
    view: "monitoring/db-mysql/overview.vue",
    position: "mysql-row-ops",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "db.mysql.innodb.row_reads",
        legend: "Reads",
      },
      {
        dialect: "tfql",
        expression: "db.mysql.innodb.row_inserts",
        legend: "Inserts",
      },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10005",
    module: "DBM",
    title: "InnoDB Lock Waits",
    component: "RegistryGraphPanel",
    chartType: "bar",
    signalType: "metrics",
    unit: "waits/s",
    description: "Lock wait frequency",
    dataSource: "db_mysql_metrics",
    view: "monitoring/db-mysql/overview.vue",
    position: "mysql-lock-waits",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "db.mysql.innodb.lock_waits",
        legend: "Lock Waits",
      },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10006",
    module: "DBM",
    title: "Replication Lag",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "seconds",
    description: "Replication lag in seconds",
    dataSource: "db_mysql_metrics",
    view: "monitoring/db-mysql/replication.vue",
    position: "mysql-repl-lag",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "db.mysql.replication_lag_seconds",
        legend: "Lag",
      },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10007",
    module: "DBM",
    title: "Connection Utilization",
    component: "RegistryGraphPanel",
    chartType: "gauge",
    signalType: "metrics",
    unit: "percent",
    description: "Connection utilization percentage",
    dataSource: "db_mysql_metrics",
    view: "monitoring/db-mysql/overview.vue",
    position: "mysql-conn-util",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "db.mysql.connection_utilization",
        legend: "Utilization",
      },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10008",
    module: "DBM",
    title: "Slow Queries Rate",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "queries/h",
    description: "Slow queries per hour",
    dataSource: "db_mysql_metrics",
    view: "monitoring/db-mysql/overview.vue",
    position: "mysql-slow-queries",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "db.mysql.slow_queries_per_hour",
        legend: "Slow Queries",
      },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10009",
    module: "DBM",
    title: "Network Traffic",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "bytes/s",
    description: "Bytes received and sent",
    dataSource: "db_mysql_metrics",
    view: "monitoring/db-mysql/overview.vue",
    position: "mysql-traffic",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "db.mysql.bytes_received",
        legend: "Received",
      },
      { dialect: "tfql", expression: "db.mysql.bytes_sent", legend: "Sent" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10010",
    module: "DBM",
    title: "Thread Cache Hit Rate",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "percent",
    description: "Thread cache hit rate",
    dataSource: "db_mysql_metrics",
    view: "monitoring/db-mysql/overview.vue",
    position: "mysql-thread-cache",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "db.mysql.thread_cache_hit_rate",
        legend: "Hit Rate",
      },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10011",
    module: "DBM",
    title: "Query Performance Trend",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "us",
    description: "Average query latency over time",
    dataSource: "db_mysql_metrics",
    view: "monitoring/db-mysql/query-analytics.vue",
    position: "mysql-query-trend",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "db.mysql.query.avg_time_us",
        legend: "Avg Latency",
      },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10012",
    module: "DBM",
    title: "Table Sizes",
    component: "RegistryGraphPanel",
    chartType: "bar",
    signalType: "metrics",
    unit: "bytes",
    description: "Table sizes by database",
    dataSource: "db_mysql_metrics",
    view: "monitoring/db-mysql/schema-browser.vue",
    position: "mysql-table-sizes",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "db.mysql.schema.table_size_bytes",
        legend: "Size",
      },
    ],
    toggleable: false,
  },
];
