import type { GraphDefinition } from './types';

// Allocated ID range: DBM10801-DBM10812
export const DBM_MONGODB_COMMUNITY_GRAPHS: GraphDefinition[] = [
  {
    graphId: "DBM10801",
    module: "DBM",
    title: "MongoDB Connections",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "connections",
    description: "Current and available connections",
    dataSource: "db_mongodb_metrics",
    view: "db-monitoring/mongodb-community/overview",
    position: "mongodb-connections",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mongodb.connections.current", legend: "Current" },
      { dialect: "tfql", expression: "db.mongodb.connections.available", legend: "Available" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10802",
    module: "DBM",
    title: "MongoDB Opcounters",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "ops/s",
    description: "Operations per second (insert/query/update/delete/getmore/command)",
    dataSource: "db_mongodb_metrics",
    view: "db-monitoring/mongodb-community/overview",
    position: "mongodb-opcounters",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mongodb.opcounters.insert", legend: "Insert" },
      { dialect: "tfql", expression: "db.mongodb.opcounters.query", legend: "Query" },
      { dialect: "tfql", expression: "db.mongodb.opcounters.update", legend: "Update" },
      { dialect: "tfql", expression: "db.mongodb.opcounters.delete", legend: "Delete" },
      { dialect: "tfql", expression: "db.mongodb.opcounters.command", legend: "Command" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10803",
    module: "DBM",
    title: "MongoDB Memory Usage",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "bytes",
    description: "Resident and virtual memory usage",
    dataSource: "db_mongodb_metrics",
    view: "db-monitoring/mongodb-community/overview",
    position: "mongodb-memory",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mongodb.memory.resident", legend: "Resident" },
      { dialect: "tfql", expression: "db.mongodb.memory.virtual", legend: "Virtual" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10804",
    module: "DBM",
    title: "Replication Lag",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "seconds",
    description: "Replication lag across replica set members",
    dataSource: "db_mongodb_metrics",
    view: "db-monitoring/mongodb-community/replica-set",
    position: "mongodb-repl-lag",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mongodb.replication.lag", legend: "Lag" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10805",
    module: "DBM",
    title: "Oplog Window",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "seconds",
    description: "Oplog time window and applied operations",
    dataSource: "db_mongodb_metrics",
    view: "db-monitoring/mongodb-community/replica-set",
    position: "mongodb-oplog",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mongodb.oplog.window_secs", legend: "Window (s)" },
      { dialect: "tfql", expression: "db.mongodb.oplog.applied_ops", legend: "Applied Ops" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10806",
    module: "DBM",
    title: "Sharding Chunks",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "chunks",
    description: "Chunk distribution and migration status",
    dataSource: "db_mongodb_metrics",
    view: "db-monitoring/mongodb-community/sharding",
    position: "mongodb-sharding",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mongodb.sharding.chunks_total", legend: "Total Chunks" },
      { dialect: "tfql", expression: "db.mongodb.sharding.chunks_migrating", legend: "Migrating" },
      { dialect: "tfql", expression: "db.mongodb.sharding.jumbo_chunks", legend: "Jumbo" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10807",
    module: "DBM",
    title: "Slow Query Duration",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "ms",
    description: "Slow query durations over time",
    dataSource: "db_mongodb_metrics",
    view: "db-monitoring/mongodb-community/query-analytics",
    position: "mongodb-slow-queries",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mongodb.queries.slow_duration_p99", legend: "P99" },
      { dialect: "tfql", expression: "db.mongodb.queries.slow_duration_p95", legend: "P95" },
      { dialect: "tfql", expression: "db.mongodb.queries.slow_duration_avg", legend: "Avg" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10808",
    module: "DBM",
    title: "Collection Sizes",
    component: "RegistryGraphPanel",
    chartType: "bar",
    signalType: "metrics",
    unit: "bytes",
    description: "Data and index sizes per collection",
    dataSource: "db_mongodb_metrics",
    view: "db-monitoring/mongodb-community/collections",
    position: "mongodb-collection-sizes",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mongodb.collection.data_size", legend: "Data" },
      { dialect: "tfql", expression: "db.mongodb.collection.index_size", legend: "Index" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10809",
    module: "DBM",
    title: "WiredTiger Cache",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "bytes",
    description: "WiredTiger cache bytes and evictions",
    dataSource: "db_mongodb_metrics",
    view: "db-monitoring/mongodb-community/overview",
    position: "mongodb-wt-cache",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mongodb.wiredtiger.cache_bytes", legend: "Cache Bytes" },
      { dialect: "tfql", expression: "db.mongodb.wiredtiger.cache_evictions", legend: "Evictions" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10810",
    module: "DBM",
    title: "WiredTiger Tickets",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "tickets",
    description: "Available read/write WiredTiger tickets",
    dataSource: "db_mongodb_metrics",
    view: "db-monitoring/mongodb-community/overview",
    position: "mongodb-wt-tickets",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mongodb.wiredtiger.read_tickets", legend: "Read" },
      { dialect: "tfql", expression: "db.mongodb.wiredtiger.write_tickets", legend: "Write" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10811",
    module: "DBM",
    title: "WiredTiger Checkpoints",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "ms",
    description: "WiredTiger checkpoint time",
    dataSource: "db_mongodb_metrics",
    view: "db-monitoring/mongodb-community/overview",
    position: "mongodb-wt-checkpoints",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mongodb.wiredtiger.checkpoint_time_ms", legend: "Checkpoint Time" },
    ],
    toggleable: false,
  },
  {
    graphId: "DBM10812",
    module: "DBM",
    title: "MongoDB Cursor Metrics",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "cursors",
    description: "Open, timed out, and total cursors",
    dataSource: "db_mongodb_metrics",
    view: "db-monitoring/mongodb-community/overview",
    position: "mongodb-cursors",
    defaultQueries: [
      { dialect: "tfql", expression: "db.mongodb.cursor.open", legend: "Open" },
      { dialect: "tfql", expression: "db.mongodb.cursor.timed_out", legend: "Timed Out" },
    ],
    toggleable: false,
  },
];
