import type { GraphDefinition } from "./types";

export const DBM_PERCONA_GRAPHS: GraphDefinition[] = [
  {
    graphId: "DBM11021",
    module: "DBM",
    title: "Query Response Time Distribution",
    component: "RegistryGraphPanel",
    chartType: "bar",
    signalType: "metrics",
    unit: "ms",
    description: "Percona QRT histogram showing query time distribution across buckets",
    dataSource: "percona.queryResponseTime",
    defaultQueries: [{ dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.query_response_time.bucket_count"' }],
    view: "monitoring/db-mysql/components/QRTSection.vue",
    position: "percona-qrt",
    toggleable: true,
  },
  {
    graphId: "DBM11022",
    title: "Query Response Time Percentiles",
    module: "DBM",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "ms",
    description: "Percona QRT P50/P95/P99 percentile trends",
    dataSource: "percona.queryResponseTimePercentiles",
    defaultQueries: [
      { dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.query_response_time.p50"', legend: "P50" },
      { dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.query_response_time.p95"', legend: "P95" },
      { dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.query_response_time.p99"', legend: "P99" },
    ],
    view: "monitoring/db-mysql/components/QRTSection.vue",
    position: "percona-qrt",
    toggleable: true,
  },
  {
    graphId: "DBM11023",
    title: "PXC Cluster Health",
    module: "DBM",
    component: "RegistryGraphPanel",
    chartType: "gauge",
    signalType: "metrics",
    unit: "status",
    description: "Percona XtraDB Cluster health status over time",
    dataSource: "percona.pxc.clusterHealth",
    defaultQueries: [{ dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.pxc.cluster_health"' }],
    view: "monitoring/db-mysql/components/PXCSection.vue",
    position: "percona-pxc",
    toggleable: true,
  },
  {
    graphId: "DBM11024",
    title: "PXC Flow Control",
    module: "DBM",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "ratio",
    description: "PXC flow control impact and certification efficiency trends",
    dataSource: "percona.pxc.flowControl",
    defaultQueries: [
      { dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.pxc.flow_control_impact"', legend: "Flow Control" },
      { dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.pxc.certification_efficiency"', legend: "Cert Efficiency" },
    ],
    view: "monitoring/db-mysql/components/PXCFlowControl.vue",
    position: "percona-pxc",
    toggleable: true,
  },
  {
    graphId: "DBM11025",
    title: "Percona Thread Pool",
    module: "DBM",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "threads",
    description: "Percona thread pool active/idle/high-prio thread counts",
    dataSource: "percona.threadPool",
    defaultQueries: [
      { dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.threadpool.active_threads"', legend: "Active" },
      { dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.threadpool.idle_threads"', legend: "Idle" },
      { dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.threadpool.high_prio_threads"', legend: "High Priority" },
    ],
    view: "monitoring/db-mysql/components/PerconaThreadPoolSection.vue",
    position: "percona-threadpool",
    toggleable: true,
  },
  {
    graphId: "DBM11026",
    title: "PXC Throughput",
    module: "DBM",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "bytes",
    description: "PXC write and replication throughput",
    dataSource: "percona.pxc.throughput",
    defaultQueries: [
      { dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.pxc.write_throughput"', legend: "Write" },
      { dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.pxc.replication_throughput"', legend: "Replication" },
    ],
    view: "monitoring/db-mysql/components/PXCSection.vue",
    position: "percona-pxc",
    toggleable: true,
  },
  {
    graphId: "DBM11027",
    title: "XtraBackup Changed Pages",
    module: "DBM",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "pages",
    description: "XtraBackup changed pages count trend",
    dataSource: "percona.xtrabackup",
    defaultQueries: [{ dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.xtrabackup.changed_pages"' }],
    view: "monitoring/db-mysql/components/XtraBackupSection.vue",
    position: "percona-xtrabackup",
    toggleable: true,
  },
  {
    graphId: "DBM11028",
    title: "Audit Event Rates",
    module: "DBM",
    component: "RegistryGraphPanel",
    chartType: "timeseries",
    signalType: "metrics",
    unit: "events",
    description: "Percona audit plugin event rates",
    dataSource: "percona.audit",
    defaultQueries: [
      { dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.audit.events"', legend: "Total" },
      { dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.audit.events_written"', legend: "Written" },
      { dialect: "tfql", expression: 'FETCH db_mysql_metrics WHERE metric_name = "db.mysql.audit.events_lost"', legend: "Lost" },
    ],
    view: "monitoring/db-mysql/components/AuditSection.vue",
    position: "percona-audit",
    toggleable: true,
  },
];
