import type { GraphDefinition } from './types';

// Allocated ID range: DBM10501-DBM10515
export const DBM_AWS_RDS_AURORA_GRAPHS: GraphDefinition[] = [
  {
    graphId: 'DBM10501',
    module: 'DBM',
    title: 'CPU Utilization',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: '%',
    description: 'CPU utilization per Aurora instance',
    dataSource: 'db_aurora_metrics',
    view: 'db-monitoring/aws-rds-aurora/InstanceDetailView.vue',
    position: 'aurora-cpu',
    defaultQueries: [
      { dialect: 'tfql', expression: 'aurora.CPUUtilization', legend: 'CPU', legendFormat: '{{instanceIdentifier}}', seriesKey: 'instanceIdentifier' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10502',
    module: 'DBM',
    title: 'Active Connections',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'connections',
    description: 'Active database connections per instance',
    dataSource: 'db_aurora_metrics',
    view: 'db-monitoring/aws-rds-aurora/InstanceDetailView.vue',
    position: 'aurora-connections',
    defaultQueries: [
      { dialect: 'tfql', expression: 'aurora.ActiveConnections', legend: 'Connections', legendFormat: '{{instanceIdentifier}}', seriesKey: 'instanceIdentifier' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10503',
    module: 'DBM',
    title: 'Volume IOPS',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'iops',
    description: 'Volume read and write IOPS',
    dataSource: 'db_aurora_metrics',
    view: 'db-monitoring/aws-rds-aurora/InstanceDetailView.vue',
    position: 'aurora-iops',
    defaultQueries: [
      { dialect: 'tfql', expression: 'aurora.VolumeReadIOPS', legend: 'Read IOPS' },
      { dialect: 'tfql', expression: 'aurora.VolumeWriteIOPS', legend: 'Write IOPS' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10504',
    module: 'DBM',
    title: 'Replica Lag',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'ms',
    description: 'Replication lag across reader instances',
    dataSource: 'db_aurora_metrics',
    view: 'db-monitoring/aws-rds-aurora/InstanceDetailView.vue',
    position: 'aurora-replica-lag',
    defaultQueries: [
      { dialect: 'tfql', expression: 'aurora.ReplicaLag', legend: 'Lag', legendFormat: '{{instanceIdentifier}}', seriesKey: 'instanceIdentifier' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10505',
    module: 'DBM',
    title: 'Buffer Cache Hit Ratio',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: '%',
    description: 'Buffer cache hit ratio over time',
    dataSource: 'db_aurora_metrics',
    view: 'db-monitoring/aws-rds-aurora/InstanceDetailView.vue',
    position: 'aurora-cache-hit',
    defaultQueries: [
      { dialect: 'tfql', expression: 'aurora.BufferCacheHitRatio', legend: 'Hit Ratio' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10506',
    module: 'DBM',
    title: 'Commit Latency',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'ms',
    description: 'Commit latency for write operations',
    dataSource: 'db_aurora_metrics',
    view: 'db-monitoring/aws-rds-aurora/InstanceDetailView.vue',
    position: 'aurora-commit-latency',
    defaultQueries: [
      { dialect: 'tfql', expression: 'aurora.CommitLatency', legend: 'Commit Latency' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10507',
    module: 'DBM',
    title: 'DML Latency',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'ms',
    description: 'Data manipulation language latency',
    dataSource: 'db_aurora_metrics',
    view: 'db-monitoring/aws-rds-aurora/InstanceDetailView.vue',
    position: 'aurora-dml-latency',
    defaultQueries: [
      { dialect: 'tfql', expression: 'aurora.DMLLatency', legend: 'DML Latency' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10508',
    module: 'DBM',
    title: 'Network Throughput',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'MB/s',
    description: 'Network throughput in and out',
    dataSource: 'db_aurora_metrics',
    view: 'db-monitoring/aws-rds-aurora/InstanceDetailView.vue',
    position: 'aurora-network',
    defaultQueries: [
      { dialect: 'tfql', expression: 'aurora.NetworkThroughput', legend: 'Throughput' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10509',
    module: 'DBM',
    title: 'ACU Utilization (Serverless)',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'ACU',
    description: 'Aurora Capacity Unit utilization for serverless instances',
    dataSource: 'db_aurora_metrics',
    view: 'db-monitoring/aws-rds-aurora/InstanceDetailView.vue',
    position: 'aurora-acu',
    defaultQueries: [
      { dialect: 'tfql', expression: 'aurora.ACUUtilization', legend: 'ACU', legendFormat: '{{instanceIdentifier}}', seriesKey: 'instanceIdentifier' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10510',
    module: 'DBM',
    title: 'Active Transactions',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'transactions',
    description: 'Active transaction count over time',
    dataSource: 'db_aurora_metrics',
    view: 'db-monitoring/aws-rds-aurora/InstanceDetailView.vue',
    position: 'aurora-transactions',
    defaultQueries: [
      { dialect: 'tfql', expression: 'aurora.ActiveTransactions', legend: 'Transactions' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10511',
    module: 'DBM',
    title: 'Freeable Memory',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'MB',
    description: 'Freeable memory per instance',
    dataSource: 'db_aurora_metrics',
    view: 'db-monitoring/aws-rds-aurora/InstanceDetailView.vue',
    position: 'aurora-memory',
    defaultQueries: [
      { dialect: 'tfql', expression: 'aurora.FreeableMemory', legend: 'Free Memory', legendFormat: '{{instanceIdentifier}}', seriesKey: 'instanceIdentifier' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10512',
    module: 'DBM',
    title: 'Wait Events Breakdown',
    component: 'RegistryGraphPanel',
    chartType: 'bar',
    signalType: 'metrics',
    unit: 'AAS',
    description: 'Wait event categories by load (average active sessions)',
    dataSource: 'db_aurora_performance_insights',
    view: 'db-monitoring/aws-rds-aurora/InstanceDetailView.vue',
    position: 'aurora-wait-events',
    defaultQueries: [
      { dialect: 'tfql', expression: 'aurora.wait_events.load', legend: 'Load', legendFormat: '{{waitEvent}}', seriesKey: 'waitEvent' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10513',
    module: 'DBM',
    title: 'Volume Storage Usage',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'GB',
    description: 'Volume storage used over time',
    dataSource: 'db_aurora_metrics',
    view: 'db-monitoring/aws-rds-aurora/InstanceDetailView.vue',
    position: 'aurora-storage',
    defaultQueries: [
      { dialect: 'tfql', expression: 'aurora.VolumeUsedGB', legend: 'Used (GB)' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10514',
    module: 'DBM',
    title: 'Deadlocks',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'count',
    description: 'Deadlock count over time',
    dataSource: 'db_aurora_metrics',
    view: 'db-monitoring/aws-rds-aurora/InstanceDetailView.vue',
    position: 'aurora-deadlocks',
    defaultQueries: [
      { dialect: 'tfql', expression: 'aurora.Deadlocks', legend: 'Deadlocks' },
    ],
    toggleable: false,
  },
  {
    graphId: 'DBM10515',
    module: 'DBM',
    title: 'Global Replication Lag',
    component: 'RegistryGraphPanel',
    chartType: 'timeseries',
    signalType: 'metrics',
    unit: 'ms',
    description: 'Cross-region replication lag for global database secondaries',
    dataSource: 'db_aurora_global_database',
    view: 'db-monitoring/aws-rds-aurora/InstanceDetailView.vue',
    position: 'aurora-global-lag',
    defaultQueries: [
      { dialect: 'tfql', expression: 'aurora.global.replication_lag_ms', legend: 'Lag', legendFormat: '{{region}}', seriesKey: 'region' },
    ],
    toggleable: false,
  },
];
