/**
 * Graph Registry — NETWORK MAP (NWM)
 * 9 graph definitions
 *
 * Auto-extracted from graph-registry.ts
 */

import type { GraphDefinition } from "./types";

export const NWM_GRAPHS: GraphDefinition[] = [
  // │ NETWORK MAP (NWM) - 9 graphs
  // └──────────────────────────────────────────────────────────────────────────────
  {
    graphId: "NWM10001",
    module: "NWM",
    title: "Total Nodes",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "count",
    description: "Total network nodes",
    dataSource: "stats.totalNodes",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "FETCH network_nodes AGGREGATE count(*)",
        legendFormat: "Total Nodes",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/network-map/index.vue",
    position: "stats-row-1",
    toggleable: false,
  },
  {
    graphId: "NWM10002",
    module: "NWM",
    title: "Healthy",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "count",
    description: "Healthy network nodes",
    dataSource: "stats.healthyNodes",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "FETCH network_nodes WHERE status = 'healthy' AGGREGATE count(*)",
        legendFormat: "Healthy",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/network-map/index.vue",
    position: "stats-row-1",
    toggleable: false,
  },
  {
    graphId: "NWM10003",
    module: "NWM",
    title: "Degraded",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "count",
    description: "Degraded network nodes",
    dataSource: "stats.degradedNodes",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "FETCH network_nodes WHERE status = 'degraded' AGGREGATE count(*)",
        legendFormat: "Degraded",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/network-map/index.vue",
    position: "stats-row-1",
    toggleable: false,
  },
  {
    graphId: "NWM10004",
    module: "NWM",
    title: "Down",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "count",
    description: "Down network nodes",
    dataSource: "stats.downNodes",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "FETCH network_nodes WHERE status = 'down' AGGREGATE count(*)",
        legendFormat: "Down",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/network-map/index.vue",
    position: "stats-row-1",
    toggleable: false,
  },
  {
    graphId: "NWM10005",
    module: "NWM",
    title: "Connections",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "count",
    description: "Total network connections",
    dataSource: "stats.totalConnections",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "FETCH network_connections AGGREGATE count(*)",
        legendFormat: "Connections",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/network-map/index.vue",
    position: "stats-row-2",
    toggleable: false,
  },
  {
    graphId: "NWM10006",
    module: "NWM",
    title: "Avg Latency",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "ms",
    description: "Average network latency",
    dataSource: "stats.avgLatency",
    defaultQueries: [
      {
        dialect: "promql",
        expression:
          'network_connection_latency{connection_id="{{connection_id}}"}',
        legendFormat: "Avg Latency",
        seriesKey: "__name__",
      },
      {
        dialect: "tfql",
        expression:
          "FETCH network_map_connection_metrics WHERE connection_id = '{{connection_id}}' AGGREGATE avg(latency) INTERVAL {{interval}}",
        legendFormat: "Avg Latency",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/network-map/index.vue",
    position: "stats-row-2",
    toggleable: false,
  },
  {
    graphId: "NWM10007",
    module: "NWM",
    title: "Active Nodes",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "count",
    description: "Currently healthy network nodes",
    dataSource: "nodes.filter(healthy).length",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "FETCH network_nodes WHERE status = 'healthy' AGGREGATE count(*)",
        legendFormat: "Active Nodes",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/network-map/index.vue",
    position: "stats-row-2",
    toggleable: false,
  },
  {
    graphId: "NWM10008",
    module: "NWM",
    title: "Maintenance",
    component: "StatPanel",
    chartType: "stat",
    signalType: "infrastructure",
    unit: "count",
    description: "Nodes in maintenance",
    dataSource: "nodes.filter(maintenance).length",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "FETCH network_nodes WHERE status = 'maintenance' AGGREGATE count(*)",
        legendFormat: "Maintenance",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/network-map/index.vue",
    position: "stats-row-2",
    toggleable: false,
  },
  {
    graphId: "NWM10009",
    module: "NWM",
    title: "Network Topology",
    component: "NetworkNodeGraph",
    chartType: "topology",
    signalType: "infrastructure",
    unit: "",
    description:
      "Interactive network topology (canvas, hierarchical/force/grid layouts)",
    dataSource: "graphData.nodes / graphData.edges",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "FETCH network_nodes AGGREGATE count(*) GROUP BY status",
        legend: "Network Topology",
        legendFormat: "{{status}}",
        seriesKey: "status",
      },
    ],
    view: "monitoring/network-map/NetworkNodeGraph.vue",
    position: "main-graph",
    toggleable: false,
  },

  // ── K8S Network Flow Graphs (NWM10010-NWM10017) ─────────────────────────────
  {
    graphId: "NWM10010",
    module: "NWM",
    title: "K8S Pod-to-Pod Traffic",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "MB/s",
    description: "Pod-to-pod network traffic volume over time",
    dataSource: "k8sNetworkFlows",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.namespace.network.receive_bytes{} by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/network-map/k8s-flows.vue",
    position: "k8s-flows-row1-col1",
    toggleable: true,
  },
  {
    graphId: "NWM10011",
    module: "NWM",
    title: "K8S Network Flow Count",
    component: "TimeSeriesChart",
    chartType: "bar",
    signalType: "kubernetes",
    unit: "flows",
    description: "Number of network flows per namespace",
    dataSource: "k8sFlowCount",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.namespace.network.transmit_bytes{} by (namespace)",
        legendFormat: "{{namespace}}",
        seriesKey: "namespace",
      },
    ],
    view: "monitoring/network-map/k8s-flows.vue",
    position: "k8s-flows-row1-col2",
    toggleable: true,
  },
  {
    graphId: "NWM10012",
    module: "NWM",
    title: "K8S Network Drops",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "drops",
    description:
      "Dropped/denied network flows (from Network Policies or packet loss)",
    dataSource: "k8sNetworkDrops",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.node.network.receive_drop_total{} by (node)",
        legendFormat: "{{node}}",
        seriesKey: "node",
      },
    ],
    view: "monitoring/network-map/k8s-flows.vue",
    position: "k8s-flows-row2-col1",
    toggleable: true,
  },
  {
    graphId: "NWM10013",
    module: "NWM",
    title: "K8S Network Policies",
    component: "StatPanel",
    chartType: "stat",
    signalType: "kubernetes",
    unit: "count",
    description: "Total NetworkPolicy count across namespaces",
    dataSource: "k8sNetworkPolicyCount",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.networkpolicy.count{} by (namespace)",
        legendFormat: "Policies",
        seriesKey: "__name__",
      },
    ],
    view: "monitoring/network-map/k8s-policies.vue",
    position: "k8s-policies-stat",
    toggleable: false,
  },
  {
    graphId: "NWM10014",
    module: "NWM",
    title: "K8S Ingress Traffic",
    component: "TimeSeriesChart",
    chartType: "timeseries",
    signalType: "kubernetes",
    unit: "MB/s",
    description: "Ingress traffic per ingress resource",
    dataSource: "k8sIngressTraffic",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.ingress.rule_count{} by (ingress)",
        legendFormat: "{{ingress}}",
        seriesKey: "ingress",
      },
    ],
    view: "monitoring/network-map/k8s-flows.vue",
    position: "k8s-flows-row2-col2",
    toggleable: true,
  },
  {
    graphId: "NWM10015",
    module: "NWM",
    title: "K8S Service Endpoint Count",
    component: "TimeSeriesChart",
    chartType: "bar",
    signalType: "kubernetes",
    unit: "endpoints",
    description: "Ready endpoints per service over time",
    dataSource: "k8sEndpointCount",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.endpoint.count{} by (service)",
        legendFormat: "{{service}}",
        seriesKey: "service",
      },
    ],
    view: "monitoring/network-map/k8s-flows.vue",
    position: "k8s-flows-row3-col1",
    toggleable: true,
  },
  {
    graphId: "NWM10016",
    module: "NWM",
    title: "K8S Service Count by Type",
    component: "TimeSeriesChart",
    chartType: "bar",
    signalType: "kubernetes",
    unit: "services",
    description: "Service count by type (ClusterIP, NodePort, LoadBalancer)",
    dataSource: "k8sServiceCountByType",
    defaultQueries: [
      {
        dialect: "tfql",
        expression: "k8s.service.count{} by (type)",
        legendFormat: "{{type}}",
        seriesKey: "type",
      },
    ],
    view: "monitoring/network-map/k8s-flows.vue",
    position: "k8s-flows-row3-col2",
    toggleable: true,
  },
  {
    graphId: "NWM10017",
    module: "NWM",
    title: "K8S Topology (Full Stack)",
    component: "NetworkNodeGraph",
    chartType: "topology",
    signalType: "kubernetes",
    unit: "",
    description:
      "Full K8S topology: Ingress → Service → Pod → Node with live traffic data",
    dataSource: "k8sTopology",
    defaultQueries: [
      {
        dialect: "tfql",
        expression:
          "FETCH network_nodes WHERE kubernetes_resource_type IS NOT NULL AGGREGATE count(*) GROUP BY kubernetes_resource_type",
        legend: "K8S Topology",
        legendFormat: "{{kubernetes_resource_type}}",
        seriesKey: "kubernetes_resource_type",
      },
    ],
    view: "monitoring/network-map/K8sTopologyGraph.vue",
    position: "k8s-topology-main",
    toggleable: false,
  },
];
