/**
 * DataTable Registry — KUBERNETES (K8S)
 * 8 datatable registry definitions
 */

import type { DataTableDefinition } from "./types";

export const K8S_DATATABLE_REGISTRY: DataTableDefinition[] = [
  // │ KUBERNETES (K8S) — 5 datatables
  // └──────────────────────────────────────────────────────────────────────────────
  {
    datatableId: "K8S30001",
    module: "K8S",
    title: "Pods",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Pod Name",
        width: 280,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "namespace",
        title: "Namespace",
        width: 140,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "status",
        title: "Status",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "restarts",
        title: "Restarts",
        width: 100,
        sortable: true,
        renderType: "text",
      },
      {
        key: "cpu",
        title: "CPU",
        width: 100,
        sortable: true,
        renderType: "progress",
      },
      {
        key: "memory",
        title: "Memory",
        width: 100,
        sortable: true,
        renderType: "progress",
      },
      {
        key: "age",
        title: "Age",
        width: 100,
        sortable: true,
        renderType: "text",
      },
    ],
    dataSource: "filteredPods",
    features: {
      pagination: true,
      pageSize: 20,
      pageSizes: [10, 20, 50, 100, 200, 500],
      search: true,
      filter: true,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 1100,
    },
    description:
      "Kubernetes pods list with status, resource usage, and restart count",
    view: "monitoring/kubernetes/pods.vue",
    position: "main-table",
  },
  {
    datatableId: "K8S30002",
    module: "K8S",
    title: "Nodes",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Node Name",
        width: 250,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "status",
        title: "Status",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "role",
        title: "Role",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "cpu",
        title: "CPU",
        width: 120,
        sortable: true,
        renderType: "progress",
      },
      {
        key: "memory",
        title: "Memory",
        width: 120,
        sortable: true,
        renderType: "progress",
      },
      {
        key: "pods",
        title: "Pods",
        width: 80,
        sortable: true,
        renderType: "text",
      },
      {
        key: "age",
        title: "Age",
        width: 100,
        sortable: true,
        renderType: "text",
      },
    ],
    dataSource: "filteredNodes",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: true,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 1000,
    },
    description:
      "Kubernetes nodes list with resource utilization and pod count",
    view: "monitoring/kubernetes/nodes.vue",
    position: "main-table",
  },
  {
    datatableId: "K8S30003",
    module: "K8S",
    title: "Deployments",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Deployment",
        width: 250,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "namespace",
        title: "Namespace",
        width: 140,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "ready",
        title: "Ready",
        width: 100,
        sortable: true,
        renderType: "text",
      },
      {
        key: "available",
        title: "Available",
        width: 100,
        sortable: true,
        renderType: "text",
      },
      {
        key: "age",
        title: "Age",
        width: 100,
        sortable: true,
        renderType: "text",
      },
    ],
    dataSource: "filteredDeployments",
    features: {
      pagination: true,
      pageSize: 20,
      search: true,
      filter: true,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 800,
    },
    description: "Kubernetes deployments with replica status",
    view: "monitoring/kubernetes/deployment.vue",
    position: "main-table",
  },
  {
    datatableId: "K8S30004",
    module: "K8S",
    title: "Namespaces",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Namespace",
        width: 200,
        sortable: true,
        renderType: "text",
      },
      {
        key: "status",
        title: "Status",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "pods",
        title: "Pods",
        width: 80,
        sortable: true,
        renderType: "text",
      },
      {
        key: "cpu",
        title: "CPU Usage",
        width: 120,
        sortable: true,
        renderType: "progress",
      },
      {
        key: "memory",
        title: "Memory",
        width: 120,
        sortable: true,
        renderType: "progress",
      },
      {
        key: "age",
        title: "Age",
        width: 100,
        sortable: true,
        renderType: "text",
      },
    ],
    dataSource: "filteredNamespaces",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: false,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 900,
    },
    description: "Kubernetes namespaces with resource usage summary",
    view: "monitoring/kubernetes/namespace.vue",
    position: "main-table",
  },
  {
    datatableId: "K8S30005",
    module: "K8S",
    title: "Persistent Volumes",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "PV Name",
        width: 250,
        sortable: true,
        renderType: "text",
      },
      {
        key: "status",
        title: "Status",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "capacity",
        title: "Capacity",
        width: 120,
        sortable: true,
        renderType: "text",
      },
      {
        key: "storageClass",
        title: "Storage Class",
        width: 160,
        sortable: true,
        renderType: "text",
      },
      {
        key: "claim",
        title: "Claim",
        width: 200,
        sortable: true,
        renderType: "text",
      },
      {
        key: "age",
        title: "Age",
        width: 100,
        sortable: true,
        renderType: "text",
      },
    ],
    dataSource: "filteredPVs",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: false,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 1000,
    },
    description: "Kubernetes persistent volumes with capacity and claim info",
    view: "monitoring/kubernetes/pv.vue",
    position: "main-table",
  },

  {
    datatableId: "K8S30006",
    module: "K8S",
    title: "Services",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Service",
        width: 250,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "namespace",
        title: "Namespace",
        width: 150,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "type",
        title: "Type",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "clusterIP",
        title: "Cluster IP",
        width: 160,
        sortable: false,
        renderType: "text",
      },
      {
        key: "externalIP",
        title: "External IP",
        width: 140,
        sortable: false,
        renderType: "text",
      },
      {
        key: "ports",
        title: "Ports",
        width: 280,
        sortable: false,
        renderType: "text",
      },
      {
        key: "endpoints",
        title: "Endpoints",
        width: 100,
        sortable: true,
        renderType: "text",
      },
      {
        key: "age",
        title: "Age",
        width: 80,
        sortable: true,
        renderType: "text",
      },
    ],
    dataSource: "filteredServices",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: true,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 1280,
    },
    description:
      "Kubernetes services with type, ports, cluster IP, external IP, and endpoint count",
    view: "monitoring/kubernetes/services.vue",
    position: "main-table",
  },
  {
    datatableId: "K8S30007",
    module: "K8S",
    title: "Endpoints",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Endpoint",
        width: 250,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "namespace",
        title: "Namespace",
        width: 150,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "readyAddresses",
        title: "Ready",
        width: 80,
        sortable: true,
        renderType: "text",
      },
      {
        key: "notReadyAddresses",
        title: "Not Ready",
        width: 100,
        sortable: true,
        renderType: "text",
      },
      {
        key: "endpoints",
        title: "Addresses",
        width: 320,
        sortable: false,
        renderType: "text",
      },
      {
        key: "ports",
        title: "Ports",
        width: 200,
        sortable: false,
        renderType: "text",
      },
      {
        key: "age",
        title: "Age",
        width: 100,
        sortable: true,
        renderType: "text",
      },
    ],
    dataSource: "filteredEndpoints",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: true,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 1200,
    },
    description:
      "Kubernetes endpoints with ready/not-ready addresses and port mappings",
    view: "monitoring/kubernetes/endpoints.vue",
    position: "main-table",
  },
  {
    datatableId: "K8S30008",
    module: "K8S",
    title: "Ingresses",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Ingress",
        width: 250,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "namespace",
        title: "Namespace",
        width: 150,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "ingressClass",
        title: "Class",
        width: 120,
        sortable: true,
        renderType: "text",
      },
      {
        key: "hosts",
        title: "Hosts",
        width: 260,
        sortable: false,
        renderType: "text",
      },
      {
        key: "loadBalancers",
        title: "Load Balancers",
        width: 200,
        sortable: false,
        renderType: "text",
      },
      {
        key: "tls",
        title: "TLS",
        width: 80,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "rules",
        title: "Rules",
        width: 80,
        sortable: true,
        renderType: "text",
      },
      {
        key: "age",
        title: "Age",
        width: 100,
        sortable: true,
        renderType: "text",
      },
    ],
    dataSource: "filteredIngresses",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: true,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 1240,
    },
    description:
      "Kubernetes ingresses with hosts, rules, TLS config, and load balancer addresses",
    view: "monitoring/kubernetes/ingress.vue",
    position: "main-table",
  },
];
