/**
 * DataTable Registry — REPORTS (RPT)
 * 3 datatable registry definitions
 */

import type { DataTableDefinition } from "./types";

export const RPT_DATATABLE_REGISTRY: DataTableDefinition[] = [
  // │ REPORTS (RPT) — 3 datatables
  // └──────────────────────────────────────────────────────────────────────────────
  {
    datatableId: "RPT30001",
    module: "RPT",
    title: "Report Definitions",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Name",
        width: 250,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "type",
        title: "Type",
        width: 180,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "schedule",
        title: "Schedule",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "format",
        title: "Format",
        width: 90,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "enabled",
        title: "Enabled",
        width: 100,
        sortable: true,
        renderType: "tag",
      },
    ],
    dataSource: "filteredDefinitions",
    features: {
      pagination: true,
      pageSize: 10,
      pageSizes: [10, 20, 50, 100, 200, 500],
      search: true,
      filter: false,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 800,
    },
    description: "Report definitions list (Definitions tab)",
    view: "reports/index.vue",
    position: "definitions-tab",
  },
  {
    datatableId: "RPT30002",
    module: "RPT",
    title: "Report Executions",
    component: "NDataTable",
    columns: [
      {
        key: "reportName",
        title: "Report Name",
        width: 250,
        sortable: true,
        renderType: "text",
      },
      {
        key: "status",
        title: "Status",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "period",
        title: "Period",
        width: 420,
        sortable: false,
        renderType: "date",
      },
      {
        key: "triggeredBy",
        title: "Triggered By",
        width: 130,
        sortable: false,
        renderType: "tag",
      },
      {
        key: "executionTimeMs",
        title: "Execution Time",
        width: 150,
        sortable: true,
        renderType: "text",
      },
      {
        key: "createdAt",
        title: "Created At",
        width: 180,
        sortable: true,
        renderType: "date",
      },
      {
        key: "actions",
        title: "",
        width: 100,
        sortable: false,
        align: "center",
        renderType: "actions",
      },
    ],
    dataSource: "filteredExecutions",
    features: {
      pagination: true,
      pageSize: 10,
      pageSizes: [10, 20, 50, 100, 200, 500],
      search: true,
      filter: false,
      export: true,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 800,
    },
    description:
      "Report execution history with status and period (Executions tab)",
    view: "reports/index.vue",
    position: "executions-tab",
  },
  {
    datatableId: "RPT30003",
    module: "RPT",
    title: "Report Schedules",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Name",
        width: 250,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "type",
        title: "Type",
        width: 180,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "schedule",
        title: "Schedule",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "nextRun",
        title: "Next Run",
        width: 280,
        sortable: false,
        renderType: "date",
      },
      {
        key: "lastExecution",
        title: "Last Execution",
        width: 150,
        sortable: false,
        renderType: "tag",
      },
      {
        key: "enabled",
        title: "Enabled",
        width: 100,
        sortable: false,
        align: "center",
        renderType: "switch",
      },
    ],
    dataSource: "filteredDefinitions",
    features: {
      pagination: true,
      pageSize: 10,
      pageSizes: [10, 20, 50, 100, 200, 500],
      search: true,
      filter: false,
      export: true,
      rowClick: false,
      rowSelection: false,
      striped: true,
      expandable: false,
    },
    description:
      "Report schedules with enable/disable toggle and next run time",
    view: "reports/schedules.vue",
    position: "main-table",
  },
];
