/**
 * DataTable Registry — AI INTELLIGENCE (AID + PRM)
 * 4 datatable registry definitions
 */

import type { DataTableDefinition } from "./types";

export const PRM_DATATABLE_REGISTRY: DataTableDefinition[] = [
  // │ PREDICTIVE MAINTENANCE (PRM) — 2 datatables
  // └──────────────────────────────────────────────────────────────────────────────
  {
    datatableId: "PRM30001",
    module: "PRM",
    title: "Prediction Models",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Model Name",
        width: 200,
        sortable: true,
        fixed: "left",
        renderType: "text",
      },
      {
        key: "resourceType",
        title: "Resource",
        width: 100,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "algorithm",
        title: "Algorithm",
        width: 140,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "alertThreshold",
        title: "Alert Threshold",
        width: 120,
        sortable: true,
        renderType: "badge",
      },
      {
        key: "state",
        title: "State",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "isEnabled",
        title: "Enabled",
        width: 80,
        sortable: false,
        renderType: "switch",
      },
      {
        key: "lastEvaluatedAt",
        title: "Last Run",
        width: 160,
        sortable: true,
        renderType: "date",
      },
      {
        key: "actions",
        title: "Actions",
        width: 140,
        sortable: false,
        fixed: "right",
        renderType: "actions",
      },
    ],
    dataSource: "predictiveMaintenanceStore.models",
    features: {
      pagination: true,
      pageSize: 20,
      pageSizes: [10, 20, 50],
      search: true,
      filter: true,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 1100,
    },
    description: "Prediction model configurations and runtime state",
    view: "ai-intelligence/predictive-maintenance/models.vue",
    position: "main",
  },
  {
    datatableId: "PRM30002",
    module: "PRM",
    title: "Predictions",
    component: "NDataTable",
    columns: [
      {
        key: "timestamp",
        title: "Time",
        width: 160,
        sortable: true,
        renderType: "date",
      },
      {
        key: "resourceType",
        title: "Resource Type",
        width: 110,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "resourceIdentifier",
        title: "Resource",
        width: 200,
        sortable: true,
        renderType: "text",
      },
      {
        key: "horizon",
        title: "Horizon",
        width: 90,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "failureProbability",
        title: "Failure Prob.",
        width: 120,
        sortable: true,
        renderType: "badge",
      },
      {
        key: "healthScore",
        title: "Health Score",
        width: 110,
        sortable: true,
        renderType: "badge",
      },
      {
        key: "healthStatus",
        title: "Status",
        width: 100,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "rSquared",
        title: "R²",
        width: 70,
        sortable: true,
        renderType: "text",
      },
    ],
    dataSource: "predictiveMaintenanceStore.predictions",
    features: {
      pagination: true,
      pageSize: 20,
      pageSizes: [10, 20, 50],
      search: true,
      filter: true,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 1060,
    },
    description: "Prediction results with failure probability and health scores",
    view: "ai-intelligence/predictive-maintenance/index.vue",
    position: "main",
  },
];

export const AID_DATATABLE_REGISTRY: DataTableDefinition[] = [
  // │ AI INTELLIGENCE (AID) — 2 datatables
  // └──────────────────────────────────────────────────────────────────────────────
  {
    datatableId: "AID30001",
    module: "AID",
    title: "Anomaly Events",
    component: "NDataTable",
    columns: [
      {
        key: "timestamp",
        title: "Time",
        width: 160,
        sortable: true,
        renderType: "date",
      },
      {
        key: "metricName",
        title: "Metric",
        width: 220,
        sortable: true,
        renderType: "text",
      },
      {
        key: "severity",
        title: "Severity",
        width: 100,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "anomalyScore",
        title: "Score",
        width: 90,
        sortable: true,
        renderType: "badge",
      },
      {
        key: "sigmaLevel",
        title: "Sigma",
        width: 80,
        sortable: true,
        renderType: "text",
      },
      {
        key: "observedValue",
        title: "Observed",
        width: 100,
        sortable: false,
        renderType: "text",
      },
      {
        key: "expectedValue",
        title: "Expected",
        width: 100,
        sortable: false,
        renderType: "text",
      },
      {
        key: "detectionMethod",
        title: "Method",
        width: 100,
        sortable: true,
        renderType: "tag",
      },
    ],
    dataSource: "aiIntelligenceStore.events",
    features: {
      pagination: true,
      pageSize: 20,
      pageSizes: [10, 20, 50],
      search: true,
      filter: true,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 900,
    },
    description: "Anomaly events detected by statistical analysis",
    view: "ai-intelligence/anomaly-detection/index.vue",
    position: "main",
  },
  {
    datatableId: "AID30002",
    module: "AID",
    title: "Detection Rules",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Rule Name",
        width: 200,
        sortable: true,
        fixed: "left",
        renderType: "text",
      },
      {
        key: "metricName",
        title: "Metric",
        width: 220,
        sortable: true,
        renderType: "text",
      },
      {
        key: "signalType",
        title: "Signal",
        width: 90,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "detectionMethod",
        title: "Method",
        width: 100,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "state",
        title: "State",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "baselineStatus",
        title: "Baseline",
        width: 100,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "enabled",
        title: "Enabled",
        width: 80,
        sortable: false,
        renderType: "switch",
      },
      {
        key: "lastAnomalyScore",
        title: "Last Score",
        width: 100,
        sortable: true,
        renderType: "badge",
      },
      {
        key: "actions",
        title: "Actions",
        width: 120,
        sortable: false,
        fixed: "right",
        renderType: "actions",
      },
    ],
    dataSource: "aiIntelligenceStore.rules",
    features: {
      pagination: true,
      pageSize: 20,
      pageSizes: [10, 20, 50],
      search: true,
      filter: true,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 1100,
    },
    description: "Anomaly detection rules and their baseline status",
    view: "ai-intelligence/anomaly-detection/rules.vue",
    position: "main",
  },
];
