/**
 * DataTable Registry — TENANCY (TEN)
 * 4 datatable registry definitions
 */

import type { DataTableDefinition } from "./types";

export const TEN_DATATABLE_REGISTRY: DataTableDefinition[] = [
  // │ TENANCY (TEN) — 4 datatables
  // └──────────────────────────────────────────────────────────────────────────────
  {
    datatableId: "TEN30001",
    module: "TEN",
    title: "Organizations",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Organization",
        width: 220,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "status",
        title: "Status",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "plan",
        title: "Plan",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "members",
        title: "Members",
        width: 100,
        sortable: true,
        renderType: "text",
      },
      {
        key: "workspaces",
        title: "Workspaces",
        width: 120,
        sortable: true,
        renderType: "text",
      },
      {
        key: "actions",
        title: "",
        width: 80,
        sortable: false,
        fixed: "right",
        renderType: "actions",
      },
    ],
    dataSource: "filteredOrganizations",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: true,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 900,
    },
    description:
      "Organization management with plan, member count, and workspace count",
    view: "tenancy/organizations/index.vue",
    position: "main-table",
  },
  {
    datatableId: "TEN30002",
    module: "TEN",
    title: "Regions",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Region",
        width: 200,
        sortable: true,
        renderType: "text",
      },
      {
        key: "code",
        title: "Code",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "status",
        title: "Status",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "provider",
        title: "Provider",
        width: 140,
        sortable: true,
        renderType: "text",
      },
      {
        key: "tenants",
        title: "Tenants",
        width: 100,
        sortable: true,
        renderType: "text",
      },
      {
        key: "actions",
        title: "",
        width: 80,
        sortable: false,
        fixed: "right",
        renderType: "actions",
      },
    ],
    dataSource: "filteredRegions",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: false,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 800,
    },
    description: "Region management with provider and tenant count",
    view: "tenancy/regions/index.vue",
    position: "main-table",
  },
  {
    datatableId: "TEN30003",
    module: "TEN",
    title: "Tenants",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Tenant",
        width: 200,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "organization",
        title: "Organization",
        width: 180,
        sortable: true,
        renderType: "text",
      },
      {
        key: "region",
        title: "Region",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "status",
        title: "Status",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "users",
        title: "Users",
        width: 80,
        sortable: true,
        renderType: "text",
      },
      {
        key: "actions",
        title: "",
        width: 80,
        sortable: false,
        fixed: "right",
        renderType: "actions",
      },
    ],
    dataSource: "filteredTenants",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: true,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 900,
    },
    description: "Tenant management with organization, region, and user count",
    view: "tenancy/tenants/index.vue",
    position: "main-table",
  },
  {
    datatableId: "TEN30004",
    module: "TEN",
    title: "Workspaces",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Workspace",
        width: 200,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "organization",
        title: "Organization",
        width: 180,
        sortable: true,
        renderType: "text",
      },
      {
        key: "status",
        title: "Status",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "members",
        title: "Members",
        width: 100,
        sortable: true,
        renderType: "text",
      },
      {
        key: "createdAt",
        title: "Created",
        width: 160,
        sortable: true,
        renderType: "date",
      },
      {
        key: "actions",
        title: "",
        width: 80,
        sortable: false,
        fixed: "right",
        renderType: "actions",
      },
    ],
    dataSource: "filteredWorkspaces",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: true,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 900,
    },
    description:
      "Workspace management with organization, member count, and creation date",
    view: "tenancy/workspaces/index.vue",
    position: "main-table",
  },
];
