/**
 * DataTable Registry — IAM (IAM)
 * 3 datatable registry definitions
 */

import type { DataTableDefinition } from "./types";

export const IAM_DATATABLE_REGISTRY: DataTableDefinition[] = [
  // │ IAM (IAM) — 3 datatables
  // └──────────────────────────────────────────────────────────────────────────────
  {
    datatableId: "IAM30001",
    module: "IAM",
    title: "Users",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Name",
        width: 200,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "email",
        title: "Email",
        width: 220,
        sortable: true,
        renderType: "text",
      },
      {
        key: "role",
        title: "Role",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "status",
        title: "Status",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "lastLogin",
        title: "Last Login",
        width: 160,
        sortable: true,
        renderType: "date",
      },
      {
        key: "actions",
        title: "",
        width: 80,
        sortable: false,
        fixed: "right",
        renderType: "actions",
      },
    ],
    dataSource: "filteredUsers",
    features: {
      pagination: true,
      pageSize: 10,
      pageSizes: [10, 20, 50, 100, 200, 500],
      search: true,
      filter: true,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 1000,
    },
    description: "User management table with role, status, and activity",
    view: "iam/users/index.vue",
    position: "main-table",
  },
  {
    datatableId: "IAM30002",
    module: "IAM",
    title: "Roles",
    component: "NDataTable",
    columns: [
      {
        key: "name",
        title: "Role",
        width: 200,
        sortable: true,
        renderType: "text",
      },
      {
        key: "description",
        title: "Description",
        width: 300,
        sortable: false,
        renderType: "text",
      },
      {
        key: "permissions",
        title: "Permissions",
        width: 120,
        sortable: true,
        renderType: "text",
      },
      {
        key: "users",
        title: "Users",
        width: 80,
        sortable: true,
        renderType: "text",
      },
      {
        key: "actions",
        title: "",
        width: 80,
        sortable: false,
        fixed: "right",
        renderType: "actions",
      },
    ],
    dataSource: "filteredRoles",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: false,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 800,
    },
    description: "Role definitions with permission count and assigned users",
    view: "iam/roles/index.vue",
    position: "main-table",
  },
  {
    datatableId: "IAM30003",
    module: "IAM",
    title: "Role Assignments",
    component: "NDataTable",
    columns: [
      {
        key: "user",
        title: "User",
        width: 200,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "role",
        title: "Role",
        width: 150,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "scope",
        title: "Scope",
        width: 150,
        sortable: true,
        renderType: "text",
      },
      {
        key: "assignedAt",
        title: "Assigned At",
        width: 160,
        sortable: true,
        renderType: "date",
      },
      {
        key: "actions",
        title: "",
        width: 80,
        sortable: false,
        fixed: "right",
        renderType: "actions",
      },
    ],
    dataSource: "filteredAssignments",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: true,
      export: false,
      rowClick: false,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 800,
    },
    description: "Role assignment management with user, role, and scope",
    view: "iam/assignments/index.vue",
    position: "main-table",
  },
];
