import type { DataTableDefinition } from "./types";

export const DBM_PERCONA_DATATABLES: DataTableDefinition[] = [
  {
    datatableId: "DBM30008",
    module: "DBM",
    title: "Percona User Statistics",
    component: "NDataTable",
    columns: [
      { key: "user", title: "User", sortable: true, renderType: "text" },
      { key: "totalConnections", title: "Total Connections", sortable: true, align: "right", renderType: "text" },
      { key: "concurrentConnections", title: "Concurrent", sortable: true, align: "right", renderType: "text" },
      { key: "cpuTime", title: "CPU Time (s)", sortable: true, align: "right", renderType: "text" },
      { key: "rowsRead", title: "Rows Read", sortable: true, align: "right", renderType: "text" },
      { key: "rowsWritten", title: "Rows Written", sortable: true, align: "right", renderType: "text" },
      { key: "busyTime", title: "Busy Time (s)", sortable: true, align: "right", renderType: "text" },
      { key: "selectCommands", title: "SELECTs", sortable: true, align: "right", renderType: "text" },
      { key: "updateCommands", title: "UPDATEs", sortable: true, align: "right", renderType: "text" },
    ],
    dataSource: "percona.userStats",
    features: { pagination: true, pageSize: 50, pageSizes: [25, 50, 100], search: true, filter: false, export: true, rowClick: true, rowSelection: false, striped: true, expandable: false },
    description: "Percona per-user activity statistics from USERSTAT plugin",
    view: "monitoring/db-mysql/components/PerconaUserStatsTable.vue",
    position: "percona-user-stats",
  },
  {
    datatableId: "DBM30009",
    module: "DBM",
    title: "QRT Bucket Distribution",
    component: "NDataTable",
    columns: [
      { key: "bucket", title: "Time Range", sortable: true, renderType: "text" },
      { key: "count", title: "Query Count", sortable: true, align: "right", renderType: "text" },
      { key: "total", title: "Total Time (s)", sortable: true, align: "right", renderType: "text" },
      { key: "avgTime", title: "Avg Time (ms)", sortable: true, align: "right", renderType: "text" },
      { key: "percentage", title: "% of Total", sortable: true, align: "right", renderType: "progress" },
    ],
    dataSource: "percona.queryResponseTimeBuckets",
    features: { pagination: false, search: false, filter: false, export: true, rowClick: false, rowSelection: false, striped: true, expandable: false },
    description: "Percona Query Response Time histogram bucket distribution",
    view: "monitoring/db-mysql/components/QRTSection.vue",
    position: "percona-qrt",
  },
  {
    datatableId: "DBM30010",
    module: "DBM",
    title: "Audit Event Summary",
    component: "NDataTable",
    columns: [
      { key: "metric", title: "Metric", sortable: true, renderType: "text" },
      { key: "value", title: "Current Value", sortable: true, align: "right", renderType: "text" },
      { key: "status", title: "Status", sortable: false, align: "center", renderType: "tag" },
    ],
    dataSource: "percona.auditSummary",
    features: { pagination: false, search: false, filter: false, export: false, rowClick: false, rowSelection: false, striped: false, expandable: false },
    description: "Percona audit plugin event summary",
    view: "monitoring/db-mysql/components/AuditSection.vue",
    position: "percona-audit",
  },
];
