/**
 * DataTable Registry — MariaDB (DBM)
 * 3 datatable registry definitions
 */

import type { DataTableDefinition } from './types';

export const DBM_MARIADB_DATATABLES: DataTableDefinition[] = [
  {
    datatableId: 'DBM30005',
    module: 'DBM',
    title: 'Replication Channels',
    component: 'NDataTable',
    columns: [
      {
        key: 'name',
        title: 'Channel Name',
        width: 150,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'ioRunning',
        title: 'IO Running',
        width: 100,
        sortable: true,
        renderType: 'tag',
      },
      {
        key: 'sqlRunning',
        title: 'SQL Running',
        width: 100,
        sortable: true,
        renderType: 'tag',
      },
      {
        key: 'lagSeconds',
        title: 'Lag (seconds)',
        width: 100,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'gtidPos',
        title: 'GTID Position',
        width: 200,
        sortable: false,
        renderType: 'text',
      },
      {
        key: 'lastError',
        title: 'Last Error',
        width: 250,
        sortable: false,
        renderType: 'text',
      },
      {
        key: 'masterHost',
        title: 'Master Host',
        width: 200,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'actions',
        title: '',
        width: 80,
        sortable: false,
        fixed: 'right',
        renderType: 'actions',
      },
    ],
    dataSource: 'replicationChannels.channels',
    features: {
      pagination: false,
      pageSize: 0,
      pageSizes: [],
      search: false,
      filter: false,
      export: true,
      rowClick: false,
      rowSelection: false,
      striped: true,
      expandable: true,
      scrollX: 1200,
    },
    description:
      'MariaDB multi-source replication channels status with IO/SQL threads, lag, and error information',
    view: 'monitoring/db-mysql/components/MultiSourceReplicationSection.vue',
    position: 'mariadb-replication-table',
  },
  {
    datatableId: 'DBM30006',
    module: 'DBM',
    title: 'User Statistics',
    component: 'NDataTable',
    columns: [
      {
        key: 'user',
        title: 'Username',
        width: 150,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'totalConnections',
        title: 'Total Connections',
        width: 120,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'concurrentConnections',
        title: 'Current Connections',
        width: 120,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'cpuTime',
        title: 'CPU Time (s)',
        width: 120,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'rowsRead',
        title: 'Rows Read',
        width: 120,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'rowsWritten',
        title: 'Rows Written',
        width: 120,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'busyTime',
        title: 'Busy Time (s)',
        width: 120,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'selectCommands',
        title: 'SELECT Commands',
        width: 120,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'updateCommands',
        title: 'UPDATE Commands',
        width: 120,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'actions',
        title: '',
        width: 80,
        sortable: false,
        fixed: 'right',
        renderType: 'actions',
      },
    ],
    dataSource: 'userStats.users',
    features: {
      pagination: true,
      pageSize: 10,
      pageSizes: [10, 20, 50, 100],
      search: true,
      filter: false,
      export: true,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 1200,
    },
    description:
      'MariaDB user statistics with connection counts, CPU time, row operations, and command counts',
    view: 'monitoring/db-mysql/components/UserStatsTable.vue',
    position: 'mariadb-user-stats-table',
  },
  {
    datatableId: 'DBM30007',
    module: 'DBM',
    title: 'ColumnStore Table Statistics',
    component: 'NDataTable',
    columns: [
      {
        key: 'database',
        title: 'Database',
        width: 150,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'table',
        title: 'Table',
        width: 200,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'totalRows',
        title: 'Total Rows',
        width: 120,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'totalExtents',
        title: 'Total Extents',
        width: 120,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'totalSize',
        title: 'Total Size',
        width: 120,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'avgCompressionRatio',
        title: 'Compression Ratio',
        width: 120,
        sortable: true,
        renderType: 'text',
      },
      {
        key: 'actions',
        title: '',
        width: 80,
        sortable: false,
        fixed: 'right',
        renderType: 'actions',
      },
    ],
    dataSource: 'columnStore.tableStats',
    features: {
      pagination: true,
      pageSize: 20,
      pageSizes: [20, 50, 100, 200],
      search: true,
      filter: true,
      export: true,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 1000,
    },
    description:
      'MariaDB ColumnStore table statistics with row counts, extent usage, storage size, and compression ratios',
    view: 'monitoring/db-mysql/components/ColumnStoreSection.vue',
    position: 'mariadb-columnstore-tables',
  },
];
