/**
 * DataTable Registry — INFRASTRUCTURE (INF)
 * 5 datatable registry definitions
 */

import type { DataTableDefinition } from "./types";

export const INF_DATATABLE_REGISTRY: DataTableDefinition[] = [
  // │ INFRASTRUCTURE (INF) — 5 datatables
  // └──────────────────────────────────────────────────────────────────────────────
  {
    datatableId: "INF30001",
    module: "INF",
    title: "CPU Details",
    component: "NDataTable",
    columns: [
      {
        key: "hostname",
        title: "Host",
        width: 200,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "usage",
        title: "CPU Usage",
        width: 140,
        sortable: true,
        renderType: "progress",
      },
      {
        key: "cores",
        title: "Cores",
        width: 80,
        sortable: true,
        renderType: "text",
      },
      {
        key: "model",
        title: "Model",
        width: 200,
        sortable: true,
        renderType: "text",
      },
      {
        key: "loadAvg",
        title: "Load Avg",
        width: 120,
        sortable: true,
        renderType: "text",
      },
    ],
    dataSource: "filteredCPUData",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: false,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 800,
    },
    description: "Per-host CPU utilization details",
    view: "monitoring/infra/cpu.vue",
    position: "main-table",
  },
  {
    datatableId: "INF30002",
    module: "INF",
    title: "RAM Details",
    component: "NDataTable",
    columns: [
      {
        key: "hostname",
        title: "Host",
        width: 200,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "usage",
        title: "Memory Usage",
        width: 140,
        sortable: true,
        renderType: "progress",
      },
      {
        key: "total",
        title: "Total",
        width: 100,
        sortable: true,
        renderType: "text",
      },
      {
        key: "used",
        title: "Used",
        width: 100,
        sortable: true,
        renderType: "text",
      },
      {
        key: "available",
        title: "Available",
        width: 100,
        sortable: true,
        renderType: "text",
      },
    ],
    dataSource: "filteredRAMData",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: false,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 800,
    },
    description: "Per-host memory utilization details",
    view: "monitoring/infra/ram.vue",
    position: "main-table",
  },
  {
    datatableId: "INF30003",
    module: "INF",
    title: "Storage Details",
    component: "NDataTable",
    columns: [
      {
        key: "hostname",
        title: "Host",
        width: 200,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "usage",
        title: "Disk Usage",
        width: 140,
        sortable: true,
        renderType: "progress",
      },
      {
        key: "total",
        title: "Total",
        width: 100,
        sortable: true,
        renderType: "text",
      },
      {
        key: "used",
        title: "Used",
        width: 100,
        sortable: true,
        renderType: "text",
      },
      {
        key: "mountpoint",
        title: "Mount",
        width: 140,
        sortable: true,
        renderType: "text",
      },
    ],
    dataSource: "filteredStorageData",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: false,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 800,
    },
    description: "Per-host disk/storage utilization details",
    view: "monitoring/infra/storage.vue",
    position: "main-table",
  },
  {
    datatableId: "INF30004",
    module: "INF",
    title: "Network Details",
    component: "NDataTable",
    columns: [
      {
        key: "hostname",
        title: "Host",
        width: 200,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "interface",
        title: "Interface",
        width: 120,
        sortable: true,
        renderType: "text",
      },
      {
        key: "rxRate",
        title: "RX Rate",
        width: 120,
        sortable: true,
        renderType: "text",
      },
      {
        key: "txRate",
        title: "TX Rate",
        width: 120,
        sortable: true,
        renderType: "text",
      },
      {
        key: "totalRx",
        title: "Total RX",
        width: 120,
        sortable: true,
        renderType: "text",
      },
      {
        key: "totalTx",
        title: "Total TX",
        width: 120,
        sortable: true,
        renderType: "text",
      },
    ],
    dataSource: "filteredNetworkData",
    features: {
      pagination: true,
      pageSize: 10,
      search: true,
      filter: false,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
      scrollX: 900,
    },
    description: "Per-host network interface throughput details",
    view: "monitoring/infra/network.vue",
    position: "main-table",
  },
  {
    datatableId: "INF30005",
    module: "INF",
    title: "Latest Agents",
    component: "NDataTable",
    columns: [
      {
        key: "hostname",
        title: "Host",
        width: 200,
        sortable: true,
        renderType: "custom",
      },
      {
        key: "status",
        title: "Status",
        width: 120,
        sortable: true,
        renderType: "tag",
      },
      {
        key: "version",
        title: "Version",
        width: 100,
        sortable: true,
        renderType: "text",
      },
      {
        key: "lastSeen",
        title: "Last Seen",
        width: 160,
        sortable: true,
        renderType: "date",
      },
    ],
    dataSource: "latestAgents",
    features: {
      pagination: false,
      search: false,
      filter: false,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
    },
    description: "Latest agent activity in overview section",
    view: "monitoring/infra/overview-components/LatestAgentsSection.vue",
    position: "overview-agents",
  },
];
