import type { DataTableDefinition } from './types';

// Allocated ID range: DBM30801-DBM30804
export const DBM_MONGODB_COMMUNITY_DATATABLES: DataTableDefinition[] = [
  {
    datatableId: "DBM30801",
    module: "DBM",
    title: "MongoDB Instances",
    component: "DataTableCard",
    columns: [
      { key: "instanceAddress", title: "Address", sortable: true, renderType: "text" },
      { key: "replicaSet", title: "Replica Set", sortable: true, renderType: "text" },
      { key: "memberState", title: "State", sortable: true, renderType: "badge" },
      { key: "mongodbVersion", title: "Version", sortable: true, renderType: "text" },
      { key: "status", title: "Status", sortable: true, renderType: "tag" },
      { key: "lastSeenAt", title: "Last Seen", sortable: true, renderType: "date" },
      { key: "actions", title: "", width: 80, sortable: false, fixed: "right", renderType: "actions" },
    ],
    dataSource: "dbMongodbCommunityStore.instances",
    features: {
      pagination: true,
      pageSize: 20,
      pageSizes: [10, 20, 50],
      search: true,
      filter: true,
      export: true,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
    },
    description: "List of registered MongoDB Community instances",
    view: "/db-monitoring/mongodb-community",
    position: "instance-list",
  },
  {
    datatableId: "DBM30802",
    module: "DBM",
    title: "Replica Set Members",
    component: "DataTableCard",
    columns: [
      { key: "instanceAddress", title: "Address", sortable: true, renderType: "text" },
      { key: "memberState", title: "State", sortable: true, renderType: "badge" },
      { key: "mongodbVersion", title: "Version", sortable: true, renderType: "text" },
      { key: "status", title: "Health", sortable: true, renderType: "tag" },
      { key: "lastSeenAt", title: "Last Seen", sortable: true, renderType: "date" },
    ],
    dataSource: "dbMongodbCommunityStore.selectedReplicaSet.members",
    features: {
      pagination: false,
      search: false,
      filter: false,
      export: false,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
    },
    description: "Members of the selected replica set",
    view: "/db-monitoring/mongodb-community/replica-set",
    position: "replica-set-members",
  },
  {
    datatableId: "DBM30803",
    module: "DBM",
    title: "Slow Queries",
    component: "DataTableCard",
    columns: [
      { key: "timestamp", title: "Time", sortable: true, renderType: "date" },
      { key: "database", title: "Database", sortable: true, renderType: "text" },
      { key: "collection", title: "Collection", sortable: true, renderType: "text" },
      { key: "operation", title: "Operation", sortable: true, renderType: "badge" },
      { key: "fingerprint", title: "Fingerprint", sortable: false, renderType: "text" },
      { key: "millis", title: "Duration (ms)", sortable: true, align: "right", renderType: "text" },
      { key: "docsExamined", title: "Docs Examined", sortable: true, align: "right", renderType: "text" },
      { key: "docsReturned", title: "Docs Returned", sortable: true, align: "right", renderType: "text" },
    ],
    dataSource: "dbMongodbCommunityStore.slowQueries",
    features: {
      pagination: true,
      pageSize: 20,
      pageSizes: [10, 20, 50, 100],
      search: true,
      filter: true,
      export: true,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: true,
    },
    description: "Slow queries from MongoDB profiler",
    view: "/db-monitoring/mongodb-community/query-analytics",
    position: "slow-queries",
  },
  {
    datatableId: "DBM30804",
    module: "DBM",
    title: "Collections",
    component: "DataTableCard",
    columns: [
      { key: "database", title: "Database", sortable: true, renderType: "text" },
      { key: "collection", title: "Collection", sortable: true, renderType: "text" },
      { key: "documentCount", title: "Documents", sortable: true, align: "right", renderType: "text" },
      { key: "dataSize", title: "Data Size", sortable: true, align: "right", renderType: "text" },
      { key: "indexSize", title: "Index Size", sortable: true, align: "right", renderType: "text" },
      { key: "avgDocSize", title: "Avg Doc Size", sortable: true, align: "right", renderType: "text" },
      { key: "indexCount", title: "Indexes", sortable: true, align: "center", renderType: "text" },
      { key: "actions", title: "", width: 80, sortable: false, fixed: "right", renderType: "actions" },
    ],
    dataSource: "dbMongodbCommunityStore.collections",
    features: {
      pagination: true,
      pageSize: 20,
      pageSizes: [10, 20, 50],
      search: true,
      filter: true,
      export: true,
      rowClick: true,
      rowSelection: false,
      striped: true,
      expandable: false,
    },
    description: "Collection statistics overview",
    view: "/db-monitoring/mongodb-community/collections",
    position: "collection-list",
  },
];
