/**
 * Mini-Graph Registry — KUBERNETES (K8S)
 * 11 mini-graph definitions
 *
 * Covers inline trend charts in:
 *   - Pods detail drawer   (K8S40001–K8S40003)
 *   - Nodes detail drawer  (K8S40004–K8S40006)
 *   - Namespace detail     (K8S40007–K8S40008)
 *   - PV detail drawer     (K8S40009–K8S40011)
 */

import type { MiniGraphDefinition } from "./types";

export const K8S_MINI_GRAPHS: MiniGraphDefinition[] = [
  // ── Pods detail panel ────────────────────────────────────────────────────────
  {
    miniGraphId: "K8S40001",
    module: "K8S",
    title: "CPU Usage",
    icon: "carbon:chip",
    iconClass: "cpu",
    unit: "m",
    chartType: "timeseries",
    signalType: "kubernetes",
    description: "Per-container CPU usage in millicores for the selected pod",
    dataSource: "selectedPodCpuSeries",
    metricExpression: "container.cpu.usage{pod=~'{{pod}}'} by (container)",
    view: "views/monitoring/kubernetes/pods.vue",
    context: "pod-detail",
  },
  {
    miniGraphId: "K8S40002",
    module: "K8S",
    title: "Memory Usage",
    icon: "ph:memory-fill",
    iconClass: "memory",
    unit: "Mi",
    chartType: "timeseries",
    signalType: "kubernetes",
    description: "Per-container memory usage (working set) in MiB for the selected pod",
    dataSource: "selectedPodMemorySeries",
    metricExpression: "container.memory.working_set{pod=~'{{pod}}'} by (container)",
    view: "views/monitoring/kubernetes/pods.vue",
    context: "pod-detail",
  },
  {
    miniGraphId: "K8S40003",
    module: "K8S",
    title: "Ephemeral Storage",
    icon: "carbon:archive",
    iconClass: "ephemeral",
    unit: "Gi",
    chartType: "timeseries",
    signalType: "kubernetes",
    description: "Ephemeral storage usage in GiB for the selected pod",
    dataSource: "selectedPodDiskSeries",
    metricExpression: "container.ephemeral_storage.usage{pod=~'{{pod}}'} by (container)",
    view: "views/monitoring/kubernetes/pods.vue",
    context: "pod-detail",
  },

  // ── Nodes detail panel ────────────────────────────────────────────────────────
  {
    miniGraphId: "K8S40004",
    module: "K8S",
    title: "CPU Usage",
    icon: "carbon:chip",
    iconClass: "cpu",
    unit: "%",
    chartType: "timeseries",
    signalType: "kubernetes",
    description: "CPU utilization percentage for the selected node",
    dataSource: "selectedNodeCpuSeries",
    metricExpression: "k8s.node.cpu.usage{resource_name='{{node}}'}",
    view: "views/monitoring/kubernetes/nodes.vue",
    context: "node-detail",
  },
  {
    miniGraphId: "K8S40005",
    module: "K8S",
    title: "Memory Usage",
    icon: "ph:memory-fill",
    iconClass: "memory",
    unit: "%",
    chartType: "timeseries",
    signalType: "kubernetes",
    description: "Memory utilization percentage for the selected node",
    dataSource: "selectedNodeMemorySeries",
    metricExpression: "k8s.node.memory.usage{resource_name='{{node}}'}",
    view: "views/monitoring/kubernetes/nodes.vue",
    context: "node-detail",
  },
  {
    miniGraphId: "K8S40006",
    module: "K8S",
    title: "Disk Usage",
    icon: "mdi:harddisk",
    iconClass: "disk",
    unit: "Gi",
    chartType: "timeseries",
    signalType: "kubernetes",
    description: "Disk usage in GiB for the selected node",
    dataSource: "selectedNodeDiskSeries",
    metricExpression: "k8s.node.filesystem.usage{resource_name='{{node}}'}",
    view: "views/monitoring/kubernetes/nodes.vue",
    context: "node-detail",
  },

  // ── Namespace detail panel ────────────────────────────────────────────────────
  {
    miniGraphId: "K8S40007",
    module: "K8S",
    title: "CPU Usage",
    icon: "carbon:chip",
    iconClass: "cpu",
    chartType: "timeseries",
    signalType: "kubernetes",
    description: "CPU usage for all workloads in the selected namespace",
    dataSource: "selectedNamespaceCpuSeries",
    metricExpression: "k8s.pod.cpu.usage{namespace='{{namespace}}'}",
    view: "views/monitoring/kubernetes/namespace.vue",
    context: "namespace-detail",
  },
  {
    miniGraphId: "K8S40008",
    module: "K8S",
    title: "Memory Usage",
    icon: "ph:memory-fill",
    iconClass: "memory",
    chartType: "timeseries",
    signalType: "kubernetes",
    description: "Memory usage for all workloads in the selected namespace",
    dataSource: "selectedNamespaceMemorySeries",
    metricExpression: "k8s.pod.memory.usage{namespace='{{namespace}}'}",
    view: "views/monitoring/kubernetes/namespace.vue",
    context: "namespace-detail",
  },

  // ── PV detail panel ────────────────────────────────────────────────────────────
  {
    miniGraphId: "K8S40009",
    module: "K8S",
    title: "Capacity Usage",
    icon: "carbon:data-volume",
    iconClass: "capacity",
    unit: "Gi",
    chartType: "timeseries",
    signalType: "kubernetes",
    description: "Used vs total capacity in GiB for the selected PersistentVolume",
    dataSource: "selectedPVCapacitySeries",
    metricExpression: "k8s.pv.inodes_used{resource_name='{{pv}}'}",
    view: "views/monitoring/kubernetes/pv.vue",
    context: "pv-detail",
  },
  {
    miniGraphId: "K8S40010",
    module: "K8S",
    title: "Inodes Used",
    icon: "carbon:document",
    iconClass: "iops",
    chartType: "timeseries",
    signalType: "kubernetes",
    description: "Inode usage count for the selected PersistentVolume",
    dataSource: "selectedPVInodesSeries",
    metricExpression: "k8s.pv.inodes_used{resource_name='{{pv}}'}",
    view: "views/monitoring/kubernetes/pv.vue",
    context: "pv-detail",
  },
  {
    miniGraphId: "K8S40011",
    module: "K8S",
    title: "Available",
    icon: "carbon:data-check",
    iconClass: "throughput",
    chartType: "timeseries",
    signalType: "kubernetes",
    description: "Available bytes remaining for the selected PersistentVolume",
    dataSource: "selectedPVAvailableSeries",
    metricExpression: "k8s.pv.capacity{resource_name='{{pv}}'}",
    view: "views/monitoring/kubernetes/pv.vue",
    context: "pv-detail",
  },
];
